| irsim_test_main_noforce.cmd -- write 0xA5 then read 0x3C, mirrors
| script/test_i2c_slave_async.py exactly (SLAVE_ADDR=0x50).
| ** EXPERIMENT VARIANT: 2nd START uses group_a_mode="none" **
| (design_notes.md 89.6 -- see start()'s docstring in gen_irsim_cmd_v9.py)
| Auto-generated by script/gen_irsim_cmd_v9.py -- do not hand-edit.
| Ties VDD/VSS, releases SDA to the (now sda_oe-gated) weak pull-up,
| forces a known-0 tx_data bus and scl=1 idle, then pulses rst_n.
| Reset is held for 3000ns (not just a few stepsizes) --
| this design's "busy" is a cross-coupled SR latch (not a DFFRB),
| and RSTB for 9 of the 33 DFFRBs (incl. sda_oe's) is gated as
| "busy AND rst_n", so busy's own latch must resolve out of its
| post-power-up X state before those registers' clear is well-
| defined again after rst_n releases (see design_notes.md 76.10).
| SDA needs no explicit "h" override here: the SDA pull-up PMOS's
| gate is the pad's own real drive-gate node (gen_irsim_sim_v9.py),
| and sda_oe is held at a genuinely DEFINED 0 throughout this whole
| window by AND-domination alone (Group-B RSTB=busy AND rst_n=0
| while rst_n=0, and stays 0 even after rst_n releases as long as
| busy hasn't gone high yet) -- so the pull-up's gate is never X
| here, and SDA resolves cleanly on its own.
| DIS (P7) is forced H -- normal operation, not the loopback/test
| mode where DIS=L makes the read-data register echo back whatever
| was last written instead of the real RX shift register (76.19).
| settle 50: IRSIM's own documented fix for back-to-back-
| inverter nodes like DFFRB's QM/QS (76.32) -- gives IRSIM time to
| see a node hold its value before declaring it X, instead of
| reacting to the first instant of an apparent conflict.
stepsize 20
settle 50
h Vdd
l Gnd
x P13
h P2
h P7
l P12
l P11
l P5
l P6
l P4
l P1
l P3
l P14
l P15
s 3000
| check: slave held in reset -- busy/addr_match/rw/sda_oe must all
| read a DEFINED 0 here, and SDA a DEFINED 1 (via the sda_oe-gated
| pull-up), not X. If still X at this point, reset itself isn't
| resolving (see design_notes.md 76.10) -- report back before
| proceeding, since nothing downstream will make sense yet.
d P13 SDA_O NC_CORE_busy NC_CORE_rw NC_CORE_addr_match
h P15
s
| DFFRB (the 33x-instantiated flip-flop cell) has the SAME cold-X
| feedback problem as BUFTH's OLD (pre-substitution) topology, one
| level deeper: RSTB only force-drives QB/Q directly, never the
| internal master/slave storage nodes (QM/QS), so once RSTB
| genuinely releases -- with this design's async, never-yet-toggled
| clocking -- Q can stay stuck at X forever even though 0 (nothing
| has been clocked in yet) is the only physically sensible value.
| QS is the actual independent root (QB/Q are plain inverters of it
| once RSTB=1); confirmed via a real run on this cell (76.13).
| Force/release all 24 Group-A instances (RSTB="_008_") here; the
| 9 Group-B instances (RSTB="_009_"=busy AND rst_n, incl. sda_oe's)
| only release once busy actually goes high, so those get the same
| treatment in start(), right after the first START condition.
l x2.x_269_.QS
l x2.x_270_.QS
l x2.x_271_.QS
l x2.x_272_.QS
l x2.x_273_.QS
l x2.x_274_.QS
l x2.x_275_.QS
l x2.x_276_.QS
l x2.x_285_.QS
l x2.x_286_.QS
l x2.x_287_.QS
l x2.x_288_.QS
l x2.x_289_.QS
l x2.x_290_.QS
l x2.x_291_.QS
l x2.x_292_.QS
l x2.x_294_.QS
l x2.x_295_.QS
l x2.x_296_.QS
l x2.x_297_.QS
l x2.x_298_.QS
l x2.x_299_.QS
l x2.x_300_.QS
l x2.x_301_.QS
s
x x2.x_269_.QS
x x2.x_270_.QS
x x2.x_271_.QS
x x2.x_272_.QS
x x2.x_273_.QS
x x2.x_274_.QS
x x2.x_275_.QS
x x2.x_276_.QS
x x2.x_285_.QS
x x2.x_286_.QS
x x2.x_287_.QS
x x2.x_288_.QS
x x2.x_289_.QS
x x2.x_290_.QS
x x2.x_291_.QS
x x2.x_292_.QS
x x2.x_294_.QS
x x2.x_295_.QS
x x2.x_296_.QS
x x2.x_297_.QS
x x2.x_298_.QS
x x2.x_299_.QS
x x2.x_300_.QS
x x2.x_301_.QS
s
s 100
| check: still defined immediately after release
d SDA_O NC_CORE_busy NC_CORE_rw NC_CORE_addr_match

| watch the whole transaction
d P2 P13 SDA_O P15 NC_CORE_busy NC_CORE_rw NC_CORE_addr_match
ana P2 P13 SDA_O P15 NC_CORE_busy NC_CORE_rw NC_CORE_addr_match

| ==================== WRITE TRANSACTION ====================
| ---- START ----
h P2
x P13
s
l P13
s 40
| check: busy asserted after START
d NC_CORE_busy
| first START of this run: busy just went high for the first
| time, which releases the 9 Group-B DFFRBs (RSTB="_009_"=busy
| AND rst_n, incl. sda_oe's own register). Same cold-X QS
| deadlock as Group-A in preamble() -- see 76.13 -- give them
| the same one-time force/release now that Group-B has actually
| released.
l x2.x_277_.QS
l x2.x_278_.QS
l x2.x_279_.QS
l x2.x_280_.QS
l x2.x_281_.QS
l x2.x_282_.QS
l x2.x_283_.QS
l x2.x_284_.QS
l x2.x_293_.QS
s
x x2.x_277_.QS
x x2.x_278_.QS
x x2.x_279_.QS
x x2.x_280_.QS
x x2.x_281_.QS
x x2.x_282_.QS
x x2.x_283_.QS
x x2.x_284_.QS
x x2.x_293_.QS
s
| check: sda_oe now holds a defined value instead of X
d SDA_O
| The core's phase/bit_cnt/shreg/addr_ok/rw_bit register bank is
| async-reset via a NOR2-derived net (gate-level Group-A RSTB,
| "_008_") that is structurally intended to pulse briefly on every
| START condition (RTL: rst_scl_domain = ~rst_n | start_pulse).
| Two independent real runs on the OLD .sim (incl. substituting the
| delay cell with a symmetric buffer cascade) proved this pulse
| structurally never fires under IRSIM at this simulation
| granularity -- not a settling-time shortfall, but IRSIM's ternary
| solver settling the whole combinational cone within one timestep
| (design_notes.md 76.22-76.24). busy's OWN edge-detect (a
| differently-shaped network) is unaffected and just proved START
| WAS correctly detected at the gate level (busy=1 above).
| First attempt (on the OLD .sim): force/release the RSTB net
| itself directly -- this FAILED on a real run (stale value read
| back immediately after release), because RSTB only force-drives
| Q/QB WHILE asserted, never the internal QM/QS storage (76.13).
| Fix: force/release each instance's OWN QS node directly (same
| proven technique as preamble()'s cold-start fix), bypassing RSTB
| entirely, for all 24 Group-A instances (this also covers
| rw/addr_match's own registers, which share this same group).
| first START: SCL has only ever been held high so far (never
| toggled low-high for a real bit yet), so Group-A's own
| row-clock nets are still at their cold-start X -- both of
| QS's transmission gates are still X-gated (genuinely floating),
| same as preamble()'s cold-start fix -- plain force_release() is
| valid here.
l x2.x_269_.QS
l x2.x_270_.QS
l x2.x_271_.QS
l x2.x_272_.QS
l x2.x_273_.QS
l x2.x_274_.QS
l x2.x_275_.QS
l x2.x_276_.QS
l x2.x_285_.QS
l x2.x_286_.QS
l x2.x_287_.QS
l x2.x_288_.QS
l x2.x_289_.QS
l x2.x_290_.QS
l x2.x_291_.QS
l x2.x_292_.QS
l x2.x_294_.QS
l x2.x_295_.QS
l x2.x_296_.QS
l x2.x_297_.QS
l x2.x_298_.QS
l x2.x_299_.QS
l x2.x_300_.QS
l x2.x_301_.QS
s
x x2.x_269_.QS
x x2.x_270_.QS
x x2.x_271_.QS
x x2.x_272_.QS
x x2.x_273_.QS
x x2.x_274_.QS
x x2.x_275_.QS
x x2.x_276_.QS
x x2.x_285_.QS
x x2.x_286_.QS
x x2.x_287_.QS
x x2.x_288_.QS
x x2.x_289_.QS
x x2.x_290_.QS
x x2.x_291_.QS
x x2.x_292_.QS
x x2.x_294_.QS
x x2.x_295_.QS
x x2.x_296_.QS
x x2.x_297_.QS
x x2.x_298_.QS
x x2.x_299_.QS
x x2.x_300_.QS
x x2.x_301_.QS
s
| check: phase/bit_cnt-owning registers cleared (rw/addr_match are
| in this same Group-A, so also visible here)
d NC_CORE_rw NC_CORE_addr_match
| ADDR+W = 0xA0
s
l P2
x P13
s 500
h P2
s 40
s
l P2
l P13
s 500
h P2
s 40
s
l P2
x P13
s 500
h P2
s 40
s
l P2
l P13
s 500
h P2
s 40
s
l P2
l P13
s 500
h P2
s 40
s
l P2
l P13
s 500
h P2
s 40
s
l P2
l P13
s 500
h P2
s 40
s
l P2
l P13
s 500
h P2
s 40
l P2
x P13
s 500
h P2
s
| check: slave ACKed matching address (write); also check addr_match=1, rw=0 (SDA low = ACK)
d P13
s
l P2
d NC_CORE_addr_match NC_CORE_rw
| DATA byte = 0xA5
s
l P2
x P13
s 500
h P2
s 40
s
l P2
l P13
s 500
h P2
s 40
s
l P2
x P13
s 500
h P2
s 40
s
l P2
l P13
s 500
h P2
s 40
s
l P2
l P13
s 500
h P2
s 40
s
l P2
x P13
s 500
h P2
s 40
s
l P2
l P13
s 500
h P2
s 40
s
l P2
x P13
s 500
h P2
s 40
l P2
x P13
s 500
h P2
s
| check: slave ACKed data byte (SDA low = ACK)
d P13
s
l P2
| check: rx_data == 0xA5 (bit0..bit7 nodes below, MSB last)
d NET_0 NET_1 NET_2 NET_3 NET_4 NET_5 NET_6 NET_7
| STOP's edge-detect path routes through a real intentional delay
| element (design_notes.md 76.10/76.13/76.20/76.21). A short
| settle (500ns) is inserted first so any residual
| propagation from the immediately-preceding bit's SDA activity
| clears before the STOP sequence starts counting its own hold.
| SDA is then held low 8000ns (not just one 20ns
| stepsize) before releasing it, so the falling edge has time to
| actually propagate through the delay cell before the rising
| (STOP) edge arrives -- otherwise the edge gets "swallowed" and
| busy never clears (see design_notes.md 76.20/76.21 for the real
| run that found this on the OLD .sim's same DEL1-based topology).
s 500
l P13
h P2
s 8000
x P13
| same real SDA pull-up RC recovery margin as send_bit() etc.
| (76.39) -- give SDA time to actually finish rising under the
| calibrated TR-1um.prm pull-up before checking busy below.
s 500
| check: busy cleared after STOP (after write)
d NC_CORE_busy
| ==================== READ TRANSACTION ====================
| preload tx_data = 0x3C (what the slave will transmit)
l P12
l P11
h P5
h P6
h P4
h P1
l P3
l P14
s 40
| ---- START ----
h P2
x P13
s
l P13
s 40
| check: busy asserted after START
d NC_CORE_busy
| The core's phase/bit_cnt/shreg/addr_ok/rw_bit register bank is
| async-reset via a NOR2-derived net (gate-level Group-A RSTB,
| "_008_") that is structurally intended to pulse briefly on every
| START condition (RTL: rst_scl_domain = ~rst_n | start_pulse).
| Two independent real runs on the OLD .sim (incl. substituting the
| delay cell with a symmetric buffer cascade) proved this pulse
| structurally never fires under IRSIM at this simulation
| granularity -- not a settling-time shortfall, but IRSIM's ternary
| solver settling the whole combinational cone within one timestep
| (design_notes.md 76.22-76.24). busy's OWN edge-detect (a
| differently-shaped network) is unaffected and just proved START
| WAS correctly detected at the gate level (busy=1 above).
| First attempt (on the OLD .sim): force/release the RSTB net
| itself directly -- this FAILED on a real run (stale value read
| back immediately after release), because RSTB only force-drives
| Q/QB WHILE asserted, never the internal QM/QS storage (76.13).
| Fix: force/release each instance's OWN QS node directly (same
| proven technique as preamble()'s cold-start fix), bypassing RSTB
| entirely, for all 24 Group-A instances (this also covers
| rw/addr_match's own registers, which share this same group).
| NOT the first START, group_a_mode="none" (EXPERIMENT,
| design_notes.md 89.6): skipping Group-A QS force/release
| entirely here, testing the hypothesis that this
| re-synthesized netlist doesn't have the old design's cold-X
| QM/QS deadlock at all (irsim_reset_check.cmd resolved cleanly
| with zero forcing anywhere -- 89.1). If addr_match/rw now
| assert correctly for this 2nd START where the "gated" mode
| previously did not (89.3), that confirms force_release_gated()
| was unnecessary (or actively harmful) on this netlist, not
| that the design itself has a bug.
| check: phase/bit_cnt-owning registers cleared (rw/addr_match are
| in this same Group-A, so also visible here)
d NC_CORE_rw NC_CORE_addr_match
| ADDR+R = 0xA1
s
l P2
x P13
s 500
h P2
s 40
s
l P2
l P13
s 500
h P2
s 40
s
l P2
x P13
s 500
h P2
s 40
s
l P2
l P13
s 500
h P2
s 40
s
l P2
l P13
s 500
h P2
s 40
s
l P2
l P13
s 500
h P2
s 40
s
l P2
l P13
s 500
h P2
s 40
s
l P2
x P13
s 500
h P2
s 40
l P2
x P13
s 500
h P2
s
| check: slave ACKed matching address (read); also check rw=1 (SDA low = ACK)
d P13
s
l P2
d NC_CORE_rw
s
l P2
x P13
s 500
h P2
s
| sample read-data bit 7 (MSB first)
d P13
s
s
l P2
x P13
s 500
h P2
s
| sample read-data bit 6 (MSB first)
d P13
s
s
l P2
x P13
s 500
h P2
s
| sample read-data bit 5 (MSB first)
d P13
s
s
l P2
x P13
s 500
h P2
s
| sample read-data bit 4 (MSB first)
d P13
s
s
l P2
x P13
s 500
h P2
s
| sample read-data bit 3 (MSB first)
d P13
s
s
l P2
x P13
s 500
h P2
s
| sample read-data bit 2 (MSB first)
d P13
s
s
l P2
x P13
s 500
h P2
s
| sample read-data bit 1 (MSB first)
d P13
s
s
l P2
x P13
s 500
h P2
s
| sample read-data bit 0 (MSB first)
d P13
s
| expected read byte == 0x3C (reconstruct MSB..LSB from the
| SDA samples logged above)
s
l P2
x P13
s 500
h P2
s 40
l P2
x P13
| STOP's edge-detect path routes through a real intentional delay
| element (design_notes.md 76.10/76.13/76.20/76.21). A short
| settle (500ns) is inserted first so any residual
| propagation from the immediately-preceding bit's SDA activity
| clears before the STOP sequence starts counting its own hold.
| SDA is then held low 8000ns (not just one 20ns
| stepsize) before releasing it, so the falling edge has time to
| actually propagate through the delay cell before the rising
| (STOP) edge arrives -- otherwise the edge gets "swallowed" and
| busy never clears (see design_notes.md 76.20/76.21 for the real
| run that found this on the OLD .sim's same DEL1-based topology).
s 500
l P13
h P2
s 8000
x P13
| same real SDA pull-up RC recovery margin as send_bit() etc.
| (76.39) -- give SDA time to actually finish rising under the
| calibrated TR-1um.prm pull-up before checking busy below.
s 500
| check: busy cleared after STOP (after final STOP)
d NC_CORE_busy

| end of irsim_test_main_noforce.cmd
