| irsim_debug_addrmatch2.cmd -- fine-grained trace of addr_match's
| own QS/D/CK (XN16, D=N642, CK=N635) around the SECOND start()'s
| $28-group force/release, to see whether the force never takes
| effect, or takes effect then gets immediately re-driven back to
| 1 (e.g. by a real clock edge re-latching a stale compare result
| before shreg's own concurrent force/release has caught up).
| See design_notes.md 76.40/76.41. Runs the REAL, unmodified
| WRITE transaction first (same primitives as irsim_test_main.cmd)
| so the state going into the second start() is realistic.
| Auto-generated by script/irsim/gen_irsim_cmd.py -- do not hand-edit.
| Ties VDD/VSS, releases SDA to the (now sda_oe-gated) weak pull-up,
| forces a known-0 tx_data bus and scl=1 idle, then pulses rst_n.
| Reset is held for 3000ns (not just a few stepsizes) --
| this design's "busy" is a cross-coupled NOR2 SR latch (not a
| DFFRB), and RSTB for 9 of the 33 DFFRBs (incl. sda_oe's) is
| gated as "busy AND rst_n", so busy's own latch must resolve out
| of its post-power-up X state before those registers' clear is
| well-defined again after rst_n releases (see design_notes.md 76.10).
| SDA no longer needs an explicit "h" override here (unlike an
| earlier version of this script -- see design_notes.md 76.11/76.16):
| the SDA pull-up PMOS's gate is sda_oe itself (gen_irsim_sim.py), and
| sda_oe is held at a genuinely DEFINED 0 throughout this whole window
| by AND-domination alone (RSTB2=busy AND rst_n=0 while rst_n=0, and
| stays 0 even after rst_n releases as long as busy hasn't gone high
| yet -- true regardless of BUFTH/DFFRB internals). So the pull-up's
| gate is never X here, and SDA resolves cleanly on its own.
| DIS (P7, N2) is forced H -- normal operation, not the loopback/
| test mode where DIS=L makes the read-data register echo back
| whatever was last written instead of the real RX shift register
| (design_notes.md 76.19).
| settle 50: IRSIM's own documented fix for back-to-back-
| inverter nodes like DFFRB's QM/QS (76.32) -- gives IRSIM time to
| see a node hold its value before declaring it X, instead of
| reacting to the first instant of an apparent conflict.
stepsize 20
settle 50
h Vdd
l Gnd
x N58
h N102
h N2
l N26
l N19
l N21
l N22
l N57
l N103
l N72
l N68
l N106
s 3000
| check: slave held in reset -- busy/addr_match/rw/sda_oe must all
| read a DEFINED 0 here, and SDA a DEFINED 1 (via the sda_oe-gated
| pull-up), not X. If still X at this point, reset itself isn't
| resolving (see design_notes.md 76.10) -- report back before
| proceeding, since nothing downstream will make sense yet.
d N58 N45 XN3.busy XN3.rw XN3.addr_match
h N106
s
| DFFRB (the 33x-instantiated flip-flop cell) has the SAME cold-X
| feedback problem as BUFTH, one level deeper: RSTB only force-
| drives QB/Q directly, never the internal master/slave storage
| nodes (QM/QS), so once RSTB genuinely releases -- with this
| design's async, never-yet-toggled clocking -- Q can stay stuck
| at X forever even though 0 (nothing has been clocked in yet) is
| the only physically sensible value. QS is the actual independent
| root (QB/Q are plain inverters of it once RSTB=1); confirmed via
| irsim_debug_dffrb.cmd on rw's own DFFRB (design_notes.md 76.13).
| Force/release all 24 instances whose RSTB=$28 (this net has just
| released, above) here; the 9 whose RSTB=$227=busy AND rst_n only
| release once busy actually goes high, so those get the same
| treatment in start(), right after the first START condition.
l XN3.XN2.QS
l XN3.XN16.QS
l XN3.XN32.QS
l XN3.XN46.QS
l XN3.XN104.QS
l XN3.XN105.QS
l XN3.XN106.QS
l XN3.XN107.QS
l XN3.XN108.QS
l XN3.XN109.QS
l XN3.XN110.QS
l XN3.XN111.QS
l XN3.XN112.QS
l XN3.XN113.QS
l XN3.XN114.QS
l XN3.XN115.QS
l XN3.XN116.QS
l XN3.XN117.QS
l XN3.XN118.QS
l XN3.XN119.QS
l XN3.XN120.QS
l XN3.XN121.QS
l XN3.XN122.QS
l XN3.XN123.QS
s
x XN3.XN2.QS
x XN3.XN16.QS
x XN3.XN32.QS
x XN3.XN46.QS
x XN3.XN104.QS
x XN3.XN105.QS
x XN3.XN106.QS
x XN3.XN107.QS
x XN3.XN108.QS
x XN3.XN109.QS
x XN3.XN110.QS
x XN3.XN111.QS
x XN3.XN112.QS
x XN3.XN113.QS
x XN3.XN114.QS
x XN3.XN115.QS
x XN3.XN116.QS
x XN3.XN117.QS
x XN3.XN118.QS
x XN3.XN119.QS
x XN3.XN120.QS
x XN3.XN121.QS
x XN3.XN122.QS
x XN3.XN123.QS
s
s 100
| check: still defined immediately after release
d N45 XN3.busy XN3.rw XN3.addr_match

d N102 N58 XN3.busy XN3.rw XN3.addr_match

| ==================== WRITE TRANSACTION (real, unmodified) ====================
| ---- START ----
h N102
x N58
s
l N58
s 40
| check: busy asserted after START
d XN3.busy
| first START of this run: busy just went high for the first
| time, which releases RSTB=$227 (=busy AND rst_n) for the 9
| DFFRBs gated on it (incl. sda_oe's own register). Same cold-X
| QS deadlock as the $28 group in preamble() -- see 76.13 --
| give them the same one-time force/release now that $227 has
| actually released.
l XN3.XN314.QS
l XN3.XN315.QS
l XN3.XN316.QS
l XN3.XN317.QS
l XN3.XN318.QS
l XN3.XN319.QS
l XN3.XN320.QS
l XN3.XN321.QS
l XN3.XN322.QS
s
x XN3.XN314.QS
x XN3.XN315.QS
x XN3.XN316.QS
x XN3.XN317.QS
x XN3.XN318.QS
x XN3.XN319.QS
x XN3.XN320.QS
x XN3.XN321.QS
x XN3.XN322.QS
s
| check: sda_oe now holds a defined value instead of X
d N45
| The core's phase/bit_cnt/shreg/addr_ok/rw_bit register bank is
| async-reset by rst_scl_domain = ~rst_n | start_pulse (RTL:
| src/i2c_slave_async.v ~L103), gate-level equivalent RSTB=$28.
| start_pulse's gate-level source ($813=NOR2($697,$703)) was proven
| (two independent real runs, incl. substituting DEL1 with a
| symmetric BUF_X1 cascade) to NEVER pulse under IRSIM at all --
| not a settling-time shortfall, but IRSIM's ternary solver settling
| the whole combinational cone within one timestep, so the transient
| window $813 needs never opens here regardless of wait time (design
| notes 76.22-76.24). busy's OWN edge-detect (differently-shaped
| network, $695/$696) is unaffected and just proved START WAS
| correctly detected at the gate level (busy=1 above).
| First attempt: force/release RSTB28 (=$28) directly -- this FAILED
| on a real run (addr_match read back as the STALE prior-transaction
| value immediately after release). Root cause: per 76.13, RSTB only
| force-drives Q/QB WHILE asserted -- it never touches the internal
| QM/QS storage nodes. Releasing RSTB after one stepsize lets Q revert
| to whatever QM/QS still hold (the stale value, since no clock edge
| has loaded a fresh D into them) -- the exact same failure mode as
| 76.13's cold-start deadlock, just re-triggered mid-run instead of at
| power-up. Fix: force/release each instance's OWN QS node directly
| (same proven technique as preamble()'s $28-group cold-start fix),
| bypassing RSTB entirely, for all 24 $28-group instances (this also
| covers rw/addr_match's own registers, which share this same group).
l XN3.XN2.QS
l XN3.XN16.QS
l XN3.XN32.QS
l XN3.XN46.QS
l XN3.XN104.QS
l XN3.XN105.QS
l XN3.XN106.QS
l XN3.XN107.QS
l XN3.XN108.QS
l XN3.XN109.QS
l XN3.XN110.QS
l XN3.XN111.QS
l XN3.XN112.QS
l XN3.XN113.QS
l XN3.XN114.QS
l XN3.XN115.QS
l XN3.XN116.QS
l XN3.XN117.QS
l XN3.XN118.QS
l XN3.XN119.QS
l XN3.XN120.QS
l XN3.XN121.QS
l XN3.XN122.QS
l XN3.XN123.QS
s
x XN3.XN2.QS
x XN3.XN16.QS
x XN3.XN32.QS
x XN3.XN46.QS
x XN3.XN104.QS
x XN3.XN105.QS
x XN3.XN106.QS
x XN3.XN107.QS
x XN3.XN108.QS
x XN3.XN109.QS
x XN3.XN110.QS
x XN3.XN111.QS
x XN3.XN112.QS
x XN3.XN113.QS
x XN3.XN114.QS
x XN3.XN115.QS
x XN3.XN116.QS
x XN3.XN117.QS
x XN3.XN118.QS
x XN3.XN119.QS
x XN3.XN120.QS
x XN3.XN121.QS
x XN3.XN122.QS
x XN3.XN123.QS
s
| check: phase/bit_cnt-owning registers cleared (rw/addr_match are
| in this same $28 group, so also visible here)
d XN3.rw XN3.addr_match
s
l N102
x N58
s 500
h N102
s 40
s
l N102
l N58
s 500
h N102
s 40
s
l N102
x N58
s 500
h N102
s 40
s
l N102
l N58
s 500
h N102
s 40
s
l N102
l N58
s 500
h N102
s 40
s
l N102
l N58
s 500
h N102
s 40
s
l N102
l N58
s 500
h N102
s 40
s
l N102
l N58
s 500
h N102
s 40
l N102
x N58
s 500
h N102
s
| check: address ack (SDA low = ACK)
d N58
s
l N102
d XN3.addr_match XN3.rw
s
l N102
x N58
s 500
h N102
s 40
s
l N102
l N58
s 500
h N102
s 40
s
l N102
x N58
s 500
h N102
s 40
s
l N102
l N58
s 500
h N102
s 40
s
l N102
l N58
s 500
h N102
s 40
s
l N102
x N58
s 500
h N102
s 40
s
l N102
l N58
s 500
h N102
s 40
s
l N102
x N58
s 500
h N102
s 40
l N102
x N58
s 500
h N102
s
| check: data ack (SDA low = ACK)
d N58
s
l N102
| STOP's edge-detect path routes through DEL1 (N704=DEL1(N697),
| a real intentional delay element -- design_notes.md 76.10/76.13).
| A short settle (500ns) is inserted first so any
| residual DEL1 propagation from the immediately-preceding bit's
| SDA activity clears before the STOP sequence starts counting its
| own hold. SDA is then held low 8000ns (not just one
| 20ns stepsize) before releasing it, so the falling edge has time
| to actually propagate through DEL1 before the rising (STOP) edge
| arrives -- otherwise the edge gets "swallowed" and busy never
| clears. A real run confirmed busy stays stuck at 1 forever with a
| 2000ns hold measured in isolation right after START, but the SAME
| 2000ns was NOT enough once real address/data bit traffic preceded
| it (see design_notes.md 76.20/76.21) -- hence the added settle gap
| and a larger hold as a safety margin against the unknown real DEL1
| delay (placeholder .prm, no characterized timing yet).
s 500
l N58
h N102
s 8000
x N58
| same real SDA pull-up RC recovery margin as send_bit() etc.
| (76.39) -- this exact check used to fire only 2*T=40ns after
| x(SDA), too soon for SDA to have actually finished rising
| under the recalibrated TR-1um.prm pull-up: a real run showed
| busy STILL reading 1 here (STOP not yet detected), not 0 --
| missed this same margin class when send_bit()/read_ack()/
| recv_bit()/send_ack_from_master() were fixed (76.40).
s 500
| check: busy cleared after STOP (after write)
d XN3.busy
| check: after STOP settles, addr_match/rw BEFORE the next START
d XN3.busy XN3.rw XN3.addr_match
| ==================== READ TRANSACTION START (manually unrolled) ====================
h N102
x N58
s
l N58
s 40
| ---- busy just reasserted ----
d XN3.busy XN3.XN16.QS XN3.N642 XN3.N635 XN3.XN2.QS XN3.addr_match XN3.rw
| ---- forcing $28-group QS=0 (all instances incl. addr_match's XN16) ----
l XN3.XN2.QS
l XN3.XN16.QS
l XN3.XN32.QS
l XN3.XN46.QS
l XN3.XN104.QS
l XN3.XN105.QS
l XN3.XN106.QS
l XN3.XN107.QS
l XN3.XN108.QS
l XN3.XN109.QS
l XN3.XN110.QS
l XN3.XN111.QS
l XN3.XN112.QS
l XN3.XN113.QS
l XN3.XN114.QS
l XN3.XN115.QS
l XN3.XN116.QS
l XN3.XN117.QS
l XN3.XN118.QS
l XN3.XN119.QS
l XN3.XN120.QS
l XN3.XN121.QS
l XN3.XN122.QS
l XN3.XN123.QS
s
| ---- forced, still held: addr_match's own QS/D/CK ----
d XN3.XN16.QS XN3.N642 XN3.N635 XN3.XN2.QS XN3.addr_match XN3.rw
x XN3.XN2.QS
x XN3.XN16.QS
x XN3.XN32.QS
x XN3.XN46.QS
x XN3.XN104.QS
x XN3.XN105.QS
x XN3.XN106.QS
x XN3.XN107.QS
x XN3.XN108.QS
x XN3.XN109.QS
x XN3.XN110.QS
x XN3.XN111.QS
x XN3.XN112.QS
x XN3.XN113.QS
x XN3.XN114.QS
x XN3.XN115.QS
x XN3.XN116.QS
x XN3.XN117.QS
x XN3.XN118.QS
x XN3.XN119.QS
x XN3.XN120.QS
x XN3.XN121.QS
x XN3.XN122.QS
x XN3.XN123.QS
s
| ---- +20ns after release ----
d XN3.XN16.QS XN3.N642 XN3.N635 XN3.XN2.QS XN3.addr_match XN3.rw
s
| ---- +40ns after release ----
d XN3.XN16.QS XN3.N642 XN3.N635 XN3.XN2.QS XN3.addr_match XN3.rw
s
| ---- +60ns after release ----
d XN3.XN16.QS XN3.N642 XN3.N635 XN3.XN2.QS XN3.addr_match XN3.rw
s
| ---- +80ns after release ----
d XN3.XN16.QS XN3.N642 XN3.N635 XN3.XN2.QS XN3.addr_match XN3.rw
s
| ---- +100ns after release ----
d XN3.XN16.QS XN3.N642 XN3.N635 XN3.XN2.QS XN3.addr_match XN3.rw
s
| ---- +120ns after release ----
d XN3.XN16.QS XN3.N642 XN3.N635 XN3.XN2.QS XN3.addr_match XN3.rw
s
| ---- +140ns after release ----
d XN3.XN16.QS XN3.N642 XN3.N635 XN3.XN2.QS XN3.addr_match XN3.rw
s
| ---- +160ns after release ----
d XN3.XN16.QS XN3.N642 XN3.N635 XN3.XN2.QS XN3.addr_match XN3.rw
s
| ---- +180ns after release ----
d XN3.XN16.QS XN3.N642 XN3.N635 XN3.XN2.QS XN3.addr_match XN3.rw
s
| ---- +200ns after release ----
d XN3.XN16.QS XN3.N642 XN3.N635 XN3.XN2.QS XN3.addr_match XN3.rw

| end of irsim_debug_addrmatch2.cmd
