| irsim_debug_stop.cmd -- does busy ever clear after WRITE's STOP?
| irsim_test_main.cmd showed busy=1 still 40ns after STOP, and the
| following READ transaction's rw stayed 0 / all read bits came back 1
| -- checking whether busy just needs more settling time.
| Auto-generated by script/irsim/gen_irsim_cmd.py -- do not hand-edit.
| Ties VDD/VSS, releases SDA to the (now sda_oe-gated) weak pull-up,
| forces a known-0 tx_data bus and scl=1 idle, then pulses rst_n.
| Reset is held for 3000ns (not just a few stepsizes) --
| this design's "busy" is a cross-coupled NOR2 SR latch (not a
| DFFRB), and RSTB for 9 of the 33 DFFRBs (incl. sda_oe's) is
| gated as "busy AND rst_n", so busy's own latch must resolve out
| of its post-power-up X state before those registers' clear is
| well-defined again after rst_n releases (see design_notes.md 76.10).
| SDA no longer needs an explicit "h" override here (unlike an
| earlier version of this script -- see design_notes.md 76.11/76.16):
| the SDA pull-up PMOS's gate is sda_oe itself (gen_irsim_sim.py), and
| sda_oe is held at a genuinely DEFINED 0 throughout this whole window
| by AND-domination alone (RSTB2=busy AND rst_n=0 while rst_n=0, and
| stays 0 even after rst_n releases as long as busy hasn't gone high
| yet -- true regardless of BUFTH/DFFRB internals). So the pull-up's
| gate is never X here, and SDA resolves cleanly on its own.
stepsize 20
h Vdd
l Gnd
x N58
h N102
l N26
l N19
l N21
l N22
l N57
l N103
l N72
l N68
l N106
s 3000
| check: slave held in reset -- busy/addr_match/rw/sda_oe must all
| read a DEFINED 0 here, and SDA a DEFINED 1 (via the sda_oe-gated
| pull-up), not X. If still X at this point, reset itself isn't
| resolving (see design_notes.md 76.10) -- report back before
| proceeding, since nothing downstream will make sense yet.
d N58 N45 XN3.busy XN3.rw XN3.addr_match
h N106
s
| DFFRB (the 33x-instantiated flip-flop cell) has the SAME cold-X
| feedback problem as BUFTH, one level deeper: RSTB only force-
| drives QB/Q directly, never the internal master/slave storage
| nodes (QM/QS), so once RSTB genuinely releases -- with this
| design's async, never-yet-toggled clocking -- Q can stay stuck
| at X forever even though 0 (nothing has been clocked in yet) is
| the only physically sensible value. QS is the actual independent
| root (QB/Q are plain inverters of it once RSTB=1); confirmed via
| irsim_debug_dffrb.cmd on rw's own DFFRB (design_notes.md 76.13).
| Force/release all 24 instances whose RSTB=$28 (this net has just
| released, above) here; the 9 whose RSTB=$227=busy AND rst_n only
| release once busy actually goes high, so those get the same
| treatment in start(), right after the first START condition.
l XN3.XN2.QS
l XN3.XN16.QS
l XN3.XN32.QS
l XN3.XN46.QS
l XN3.XN104.QS
l XN3.XN105.QS
l XN3.XN106.QS
l XN3.XN107.QS
l XN3.XN108.QS
l XN3.XN109.QS
l XN3.XN110.QS
l XN3.XN111.QS
l XN3.XN112.QS
l XN3.XN113.QS
l XN3.XN114.QS
l XN3.XN115.QS
l XN3.XN116.QS
l XN3.XN117.QS
l XN3.XN118.QS
l XN3.XN119.QS
l XN3.XN120.QS
l XN3.XN121.QS
l XN3.XN122.QS
l XN3.XN123.QS
s
x XN3.XN2.QS
x XN3.XN16.QS
x XN3.XN32.QS
x XN3.XN46.QS
x XN3.XN104.QS
x XN3.XN105.QS
x XN3.XN106.QS
x XN3.XN107.QS
x XN3.XN108.QS
x XN3.XN109.QS
x XN3.XN110.QS
x XN3.XN111.QS
x XN3.XN112.QS
x XN3.XN113.QS
x XN3.XN114.QS
x XN3.XN115.QS
x XN3.XN116.QS
x XN3.XN117.QS
x XN3.XN118.QS
x XN3.XN119.QS
x XN3.XN120.QS
x XN3.XN121.QS
x XN3.XN122.QS
x XN3.XN123.QS
s
s 100
| check: still defined immediately after release
d N45 XN3.busy XN3.rw XN3.addr_match

d XN3.busy
| ==================== WRITE TRANSACTION ====================
| ---- START ----
h N102
x N58
s
l N58
s 40
| check: busy asserted after START
d XN3.busy
| first START of this run: busy just went high for the first
| time, which releases RSTB=$227 (=busy AND rst_n) for the 9
| DFFRBs gated on it (incl. sda_oe's own register). Same cold-X
| QS deadlock as the $28 group in preamble() -- see 76.13 --
| give them the same one-time force/release now that $227 has
| actually released.
l XN3.XN314.QS
l XN3.XN315.QS
l XN3.XN316.QS
l XN3.XN317.QS
l XN3.XN318.QS
l XN3.XN319.QS
l XN3.XN320.QS
l XN3.XN321.QS
l XN3.XN322.QS
s
x XN3.XN314.QS
x XN3.XN315.QS
x XN3.XN316.QS
x XN3.XN317.QS
x XN3.XN318.QS
x XN3.XN319.QS
x XN3.XN320.QS
x XN3.XN321.QS
x XN3.XN322.QS
s
| check: sda_oe now holds a defined value instead of X
d N45
s
l N102
x N58
s
h N102
s 40
s
l N102
l N58
s
h N102
s 40
s
l N102
x N58
s
h N102
s 40
s
l N102
l N58
s
h N102
s 40
s
l N102
l N58
s
h N102
s 40
s
l N102
l N58
s
h N102
s 40
s
l N102
l N58
s
h N102
s 40
s
l N102
l N58
s
h N102
s 40
l N102
x N58
s
h N102
s
| check: addr ACK (SDA low = ACK)
d N58
s
l N102
s
l N102
x N58
s
h N102
s 40
s
l N102
l N58
s
h N102
s 40
s
l N102
x N58
s
h N102
s 40
s
l N102
l N58
s
h N102
s 40
s
l N102
l N58
s
h N102
s 40
s
l N102
x N58
s
h N102
s 40
s
l N102
l N58
s
h N102
s 40
s
l N102
x N58
s
h N102
s 40
l N102
x N58
s
h N102
s
| check: data ACK (SDA low = ACK)
d N58
s
l N102
l N58
h N102
s
x N58
s 40
| check: busy cleared after STOP (after write (immediate check))
d XN3.busy
s 60
| ---- t=+100ns since STOP ----
d XN3.busy
s 400
| ---- t=+500ns since STOP ----
d XN3.busy
s 500
| ---- t=+1000ns since STOP ----
d XN3.busy
s 2000
| ---- t=+3000ns since STOP ----
d XN3.busy
s 5000
| ---- t=+8000ns since STOP ----
d XN3.busy

| end of irsim_debug_stop.cmd
