"""
gen_irsim_verilog_equiv_tb.py

Builds irsim/irsim_tb.cmd: a SINGLE combined IRSIM run that mirrors
src/i2c_slave_async_tb.v (and src/i2c_slave_async_net_tb.v, identical
except for one elaboration-only detail -- see that file's header)
exactly: same 3 scenarios, same order, in ONE session --

  1. write transaction  : S, ADDR+W(0x50), ACK, 0xA5, ACK, P
  2. read transaction    : S, ADDR+R(0x50), ACK, slave drives 0x3C, NACK, P
  3. wrong-address write : S, ADDR+W(0x11), NACK, P

-- and the same 14 checks the Verilog testbench's check() task asserts,
in the same order:

  1. busy asserted after START
  2. slave ACKed matching address (write)
  3. addr_match asserted
  4. rw indicates WRITE
  5. slave ACKed data byte
  6. rx_data == 0xA5
  7. busy cleared after STOP
  8. slave ACKed matching address (read)
  9. rw indicates READ
  10. read byte == 0x3C
  11. busy cleared after final STOP
  12. unmatched address -> NACK (no slave ack)
  13. addr_match not asserted for foreign address
  14. busy cleared after STOP following NACK

IRSIM's own .cmd language has no conditionals or arithmetic, so it
cannot itself total up an error count and print a final PASS/FAIL line
the way the Verilog testbench's `check()` task does. This script's
CmdGen.checked_dump() calls (see gen_irsim_cmd_v9.py) instead record
each check's expected {node: 0/1} values into irsim_tb_expected.json,
alongside the .cmd; the companion script/check_irsim_tb_log.py reads
BOTH a real run's log and that JSON and prints the equivalent
[t=...] OK/FAIL lines plus a final "N check(s) FAILED" / "All checks
PASSED" summary, entirely offline (no IRSIM changes needed).
"""
import json
import sys

sys.path.insert(0, ".")
from gen_irsim_cmd_v9 import (
    CmdGen, VDD, GND, RST_N, SCL, SDA, SDA_OE, DIS, TX, RX,
    BUSY, RW, ADDR_MATCH, SLAVE_ADDR, T, SDA_RELEASE_SETTLE_NS,
)

WRONG_ADDR = 0x11
DATA_WR = 0xA5
DATA_RD = 0x3C


def checked_read_ack(g, label, expect_ack):
    """Same sequence as CmdGen.read_ack(), but records the ACK/NACK
    expectation on SDA (0=ACK, 1=NACK) instead of an untracked d()."""
    g.l(SCL)
    g.x(SDA)
    g.s(SDA_RELEASE_SETTLE_NS)
    g.h(SCL)
    g.s()
    g.checked_dump(label, {SDA: 0 if expect_ack else 1})
    g.s()
    g.l(SCL)


def checked_recv_bit(g, idx, expect_bit, group):
    """Same sequence as CmdGen.recv_bit(), but records the expected bit
    value, tagged with `group` so the checker can also print one
    synthesized byte-level check (matching read_byte()'s Verilog
    behavior: 8 bits sampled internally, only the reconstructed byte is
    actually asserted)."""
    g.s()
    g.l(SCL)
    g.x(SDA)
    g.s(SDA_RELEASE_SETTLE_NS)
    g.h(SCL)
    g.s()
    g.checked_dump(f"sample read-data bit {idx} (MSB first)", {SDA: expect_bit}, group=group)
    g.s()


def gen():
    g = CmdGen()
    g.note("irsim_tb.cmd -- IRSIM equivalent of src/i2c_slave_async_tb.v /")
    g.note("src/i2c_slave_async_net_tb.v: identical 3 scenarios (write")
    g.note("0xA5, read 0x3C, wrong-address NACK), identical order, run")
    g.note("against the chip-level tr_1um_i2c_slave_async.sim in one")
    g.note("session. Auto-generated by script/gen_irsim_verilog_equiv_tb.py")
    g.note("-- do not hand-edit. See design_notes.md 98.x.")
    g.note("")
    g.note("After a real run, verify automatically with:")
    g.note("  python3 script/check_irsim_tb_log.py irsim/<your-log> \\")
    g.note("      irsim/irsim_tb_expected.json")
    g.note("(mirrors the Verilog testbench's check()/errors/RESULT --")
    g.note("IRSIM's .cmd language itself has no conditionals/arithmetic")
    g.note("to total up a pass/fail count on its own.)")
    g.preamble()

    g.d(SCL, SDA, SDA_OE, RST_N, BUSY, RW, ADDR_MATCH)
    g.raw("ana " + " ".join([SCL, SDA, SDA_OE, RST_N, BUSY, RW, ADDR_MATCH]))
    g.raw("")

    # ==================== Scenario 1: write 0xA5 ====================
    g.note("==================== Scenario 1: write 0xA5 ====================")
    g.start(first=True)
    g.checked_dump("busy asserted after START", {BUSY: 1})

    addr_byte = (SLAVE_ADDR << 1) | 0
    g.note(f"ADDR+W = 0x{addr_byte:02X}")
    g.send_byte(addr_byte)
    checked_read_ack(g, "slave ACKed matching address (write)", expect_ack=True)
    g.checked_dump("addr_match asserted", {ADDR_MATCH: 1})
    g.checked_dump("rw indicates WRITE", {RW: 0})

    g.note(f"DATA byte = 0x{DATA_WR:02X}")
    g.send_byte(DATA_WR)
    checked_read_ack(g, "slave ACKed data byte", expect_ack=True)
    rx_expect = {RX[i]: (DATA_WR >> i) & 1 for i in range(8)}  # RX[i] = bit i
    g.checked_dump(f"rx_data == 0x{DATA_WR:02X}", rx_expect)

    g.stop("after write")
    g.checked_dump("busy cleared after STOP", {BUSY: 0})

    # ==================== Scenario 2: read 0x3C, then NACK ====================
    g.note("==================== Scenario 2: read 0x3C, then NACK ====================")
    g.note(f"preload tx_data = 0x{DATA_RD:02X} (what the slave will transmit)")
    for i in range(8):
        bit = (DATA_RD >> i) & 1
        (g.h if bit else g.l)(TX[i])
    g.s(2 * T)

    g.start(group_a_mode="gated")
    addr_byte = (SLAVE_ADDR << 1) | 1
    g.note(f"ADDR+R = 0x{addr_byte:02X}")
    g.send_byte(addr_byte)
    checked_read_ack(g, "slave ACKed matching address (read)", expect_ack=True)
    g.checked_dump("rw indicates READ", {RW: 1})

    for i in range(8):
        bit = (DATA_RD >> (7 - i)) & 1  # MSB first, matches Verilog's read_byte()
        checked_recv_bit(g, 7 - i, bit, group="read_byte_0x3C")

    g.send_ack_from_master(1)  # master NACKs -> ends read
    g.stop("after final STOP")
    g.checked_dump("busy cleared after final STOP", {BUSY: 0})

    # ==================== Scenario 3: wrong address -> NACK ====================
    g.note("==================== Scenario 3: wrong address -> NACK ====================")
    g.start(group_a_mode="gated")
    addr_byte = (WRONG_ADDR << 1) | 0
    g.note(f"ADDR+W (WRONG) = 0x{addr_byte:02X}")
    g.send_byte(addr_byte)
    checked_read_ack(g, "unmatched address -> NACK (no slave ack)", expect_ack=False)
    g.checked_dump("addr_match not asserted for foreign address", {ADDR_MATCH: 0})

    g.stop("after STOP following NACK")
    g.checked_dump("busy cleared after STOP following NACK", {BUSY: 0})

    g.raw("")
    g.note("end of irsim_tb.cmd")
    return g


if __name__ == "__main__":
    g = gen()
    txt = "\n".join(g.lines) + "\n"
    with open("../irsim/irsim_tb.cmd", "w") as f:
        f.write(txt)

    groups = {
        "read_byte_0x3C": {
            "label": f"read byte == 0x{DATA_RD:02X}",
            "target": DATA_RD,
            "bit_order": "msb_first",  # entries within the group are recorded MSB-first
            "node": SDA,
        },
    }
    out = {"checks": g.checks, "groups": groups}
    with open("../irsim/irsim_tb_expected.json", "w") as f:
        json.dump(out, f, indent=2)

    n_checked = sum(1 for c in g.checks if c["expect"] is not None)
    n_headline = sum(1 for c in g.checks if c["expect"] is not None and c["group"] is None)
    n_headline += len(groups)
    print(f"wrote irsim_tb.cmd: {len(txt.splitlines())} lines")
    print(f"wrote irsim_tb_expected.json: {len(g.checks)} dump entries "
          f"({n_checked} with recorded expectations, {n_headline} headline checks)")
