#!/usr/bin/env python3
"""
gen_prm_characterize.py -- generates the ngspice deck(s) needed to build a
REAL irsim/TR-1um.prm (replacing the scmos100.prm placeholder currently in
use -- design_notes.md notes throughout this project that its timing
values are not representative of TR-1um).

Methodology: IRSIM's OWN official calibration procedure, exactly as
documented in the irsim source tree (lib/calibrate_spice3/{README,ckt.spi,
findr.c}, https://github.com/RTimothyEdwards/irsim), adapted here for
ngspice's ASCII rawfile output and this project's real TR-1um PMOS/NMOS
model wrappers. Fetched and read directly from the irsim GitHub repo this
session -- see design_notes.md for the full derivation.

The four-subcircuit measurement technique (out1/out2/out3/out4) and the
resistance formulas are IRSIM's own, not invented for this project:
  out1 -- self-driven inverter (in1->out1): fast (<=0.1ns) input edge.
  out2 -- second inverter driven BY out1: realistic/slow input edge.
          Comparing out1 vs out2's delay isolates the transistor's own
          "static" (switching-point) resistance from edge-rate effects.
  out3 -- lone NFET pulling a loaded node UP toward Vdd (source=VDD,
          drain=out3) -- NMOS's weak direction ("n-channel dynamic-high").
  out4 -- lone PFET pulling a loaded node DOWN toward Gnd (source=GND,
          drain=out4) -- PMOS's weak direction ("p-channel dynamic-low").

Run once per (W, L) reference point wanted in the .prm's resistance
interpolation table. This project's real TR-1um transistor-level netlist
(src/tr_1um_i2c_slave_async.extracted) uses L=1u for the overwhelming
majority of devices, and L=2u specifically for DEL1's long-channel PMOS/
NMOS (design_notes.md 76.10/76.20-76.24 -- the delay-line cell whose
asymmetric propagation drove much of this session's IRSIM debugging), so
those are the two L points characterized here. Reference W=10.2u(PMOS)/
3.4u(NMOS) matches BOTH INV_X1's own unit-inverter sizing AND DEL1's own
L=2u device widths exactly (see the real extracted netlist), so this one
W works cleanly for both L points -- IRSIM linearly interpolates/scales
resistance by L/W for every other transistor's actual size from these two
table entries.

Uses the REAL TR-1um SPICE models (not the scmos100.prm placeholder):
  ~/Dropbox/91_OpenPDK/TR-1um/libs.tech/spice/models/ip62_models
(measured/fitted BSIM3v3 PMOS/NMOS -- see models_IP62_mos_v2.lib) via the
SAME .include path and .param vdd=5.0 convention already used by this
project's own existing xschem-generated testbenches (simulations/
BUFTH_X1_AC.spice, simulations/IO_DC.spice, simulations/IO_AC.spice,
simulations/IO_TEST.spice -- all confirmed vdd=5.0 by grep this session).

This script only WRITES the ngspice deck(s) -- ngspice itself must be run
LOCALLY (this environment cannot run ngspice). After running gen_prm_
characterize.py, do, from the irsim/ directory:

    ngspice -b prm_char_L1.spi
    ngspice -b prm_char_L2.spi

Each run writes an ASCII rawfile (prm_char_L1.raw / prm_char_L2.raw,
`set filetype=ascii` + `write ... .raw` in the .control block) that
build_tr1um_prm.py then reads to compute the actual resistance table, and
also computes the capga/capda/cappda/diffext capacitance parameters
directly from the same real model file (tox, cj -- no ngspice run needed
for those), and assembles the final irsim/TR-1um.prm.
"""
import pathlib

MODEL_INCLUDE = "~/Dropbox/91_OpenPDK/TR-1um/libs.tech/spice/models/ip62_models"
VDD = 5.0
CAP_FF = 1000  # 1pF loading cap -- IRSIM's own README: "make sure Cap is
                # sufficiently large (1pf is ok) otherwise the delay will
                # be determined primarily by the internal (parasitic)
                # capacitance of the driving device."

# Reference device sizes: matches INV_X1's unit inverter (PMOS w=10.2u,
# NMOS w=3.4u, both L=1u -- src/tr_1um_i2c_slave_async.extracted) AND
# DEL1's own L=2u long-channel devices (PMOS w=10.2u, NMOS w=3.4u at L=2u
# -- same extracted netlist, XM$1/XM$5 PMOS and XM$6/XM$10 NMOS). One
# reference width covers both L points cleanly.
PWIDTH = 10.2
NWIDTH = 3.4

# um -- covers this design's actual L range (dominant 1u, DEL1's 2u).
L_POINTS = [1.0, 2.0]


DECK_TEMPLATE = """\
* prm_char_L{Lg}.spi -- auto-generated by script/gen_prm_characterize.py
* DO NOT hand-edit -- regenerate instead.
*
* IRSIM's official resistance-table characterization circuit
* (lib/calibrate_spice3/ckt.spi in the irsim source tree,
* https://github.com/RTimothyEdwards/irsim), adapted for ngspice and this
* project's real TR-1um PMOS/NMOS models. See gen_prm_characterize.py's
* module docstring for the full methodology.
*
* W={PWIDTH}u(P)/{NWIDTH}u(N)  L={Lg}u  Cap={CAP_FF}fF  Vdd={VDD}V

.include '{MODEL_INCLUDE}'

* NOTE: the local ground rail is named VSS, not GND -- ngspice (like this
* project's own testbenches, e.g. simulations/IO_DC.spice) treats "gnd"
* as a reserved alias for node 0, so a node literally named GND tied to 0
* via a source is a short-circuit ("shorted VSRC") in ngspice.

* out1 -- self-driven inverter (fast input edge)
XP1 out1 in1 VDD VDD PMOS w={PWIDTH}u l={Lg}u nrd=0 nrs=0
XN1 out1 in1 VSS VSS NMOS w={NWIDTH}u l={Lg}u nrd=0 nrs=0

* out2 -- second inverter, driven BY out1 (realistic/slow input edge)
XP2 out2 out1 VDD VDD PMOS w={PWIDTH}u l={Lg}u nrd=0 nrs=0
XN2 out2 out1 VSS VSS NMOS w={NWIDTH}u l={Lg}u nrd=0 nrs=0

* out3 -- lone NFET pulling UP (source=VDD, drain=out3): n-channel
* dynamic-high (NMOS's weak direction)
XN3 out3 in2 VDD VSS NMOS w={NWIDTH}u l={Lg}u nrd=0 nrs=0

* out4 -- lone PFET pulling DOWN (source=VSS, drain=out4): p-channel
* dynamic-low (PMOS's weak direction)
XP4 out4 in3 VSS VDD PMOS w={PWIDTH}u l={Lg}u nrd=0 nrs=0

Cout1 out1 0 {CAP_FF}f
Cout2 out2 0 {CAP_FF}f
Cout3 out3 0 {CAP_FF}f
Cout4 out4 0 {CAP_FF}f

VVDD VDD 0 DC {VDD}
VVSS VSS 0 DC 0

* fast (<=0.1ns) edges, matching IRSIM's own calibration procedure exactly
Vin1 in1 0 PWL(0n 0 0.1n {VDD} 40n {VDD} 40.1n 0)
Vin2 in2 0 PWL(0n 0 0.1n {VDD})
Vin3 in3 0 PWL(0n {VDD} 0.1n 0)

.ic V(out4)={VDD}

.control
  tran 0.01n 80n
  set filetype=ascii
  write prm_char_L{Lg}.raw
.endc

.end
"""


def gen_deck(L):
    return DECK_TEMPLATE.format(
        Lg=f"{L:g}", PWIDTH=PWIDTH, NWIDTH=NWIDTH, CAP_FF=CAP_FF, VDD=VDD,
        MODEL_INCLUDE=MODEL_INCLUDE,
    )


def main():
    outdir = pathlib.Path(__file__).resolve().parent.parent / "irsim"
    paths = []
    for L in L_POINTS:
        path = outdir / f"prm_char_L{L:g}.spi"
        path.write_text(gen_deck(L))
        paths.append(path)
        print(f"wrote {path}")

    print()
    print("Run locally with ngspice (not available in this sandbox), from")
    print("the irsim/ directory:")
    print()
    for L in L_POINTS:
        print(f"  ngspice -b prm_char_L{L:g}.spi")
    print()
    print("Each run writes an ASCII rawfile (prm_char_L1.raw / prm_char_L2.raw).")
    print("Then run: python3 script/build_tr1um_prm.py")


if __name__ == "__main__":
    main()
