#!/usr/bin/env python3
"""
gen_dffrb_reset_tb.py -- ngspice testbench to directly observe DFFRB's
real analog behavior around reset release, at the transistor level, using
the REAL TR-1um models. This is a follow-up to design_notes.md 76.30:
IRSIM (under both the scmos100.prm placeholder AND the real ngspice-
derived TR-1um.prm) shows the SAME structural fact -- the slave-latch
node QS is held only by two transmission gates gated by CK's derived
clock phases (CKB/CKP), which have never toggled since cold start, so QS
is nominally "floating" once RSTB releases. Under scmos100.prm this
floating node appeared to RETAIN its externally-forced value for the
rest of every test in this session; under the new real TR-1um.prm it
reverted to IRSIM's X (undefined) within a single 20ns stepsize of
release. Since this discrepancy is entirely about how each .prm's RC
values interact with IRSIM's simplified ternary/dynamic-node decay
model, the only way to find out what the REAL transistors actually do is
to simulate them directly.

DFFRB's real transistor-level netlist (26 transistors, subckt body taken
directly from simulations/DFFRB.spice / src/tr_1um_i2c_slave_async.extracted
lines ~1015-1069 -- the ACTUAL cell used in the chip, not a
simplification) shows QS connects ONLY to 4 pass-transistors forming two
complementary transmission gates (QM<->QS gated by CK, QS<->$10 gated by
CK'). With CK held at a fixed level (never toggled) and RSTB released,
QS should be a genuinely high-impedance node from that point on -- what
this testbench checks is whether real subthreshold/junction leakage
through those same "off" transistors is enough to pull it toward a
definite rail (and if so, which one, and how fast), or whether it
realistically stays near mid-rail (genuinely metastable/undefined) for
a problematic length of real time.

D and CK are held at fixed (representative) levels since this test is
about QS's OWN retention, not data capture. RSTB is pulsed low (100ns,
matching a reset assert) then released; QS is given an explicit .ic
matching the "force QS=0" step the .cmd scripts perform, and then just
left alone (no further forcing) for a transient out to 40us (comfortably covers
this session's longest real IRSIM test, irsim_test_main.cmd, which ends
around t=39260ns) to see how long the forced value actually survives in
the real transistor circuit.

Run locally (ngspice not available in this sandbox):
    cd irsim
    ngspice -b dffrb_reset_tb.spi
Then look at qs_v.txt (printed V(qs)/V(qb)/V(q) vs time via .control's
own print/plot -- or open interactively with `ngspice dffrb_reset_tb.spi`
and `plot v(qs) v(qb) v(q) v(rstb)` for a visual look).
"""
import pathlib

MODEL_INCLUDE = "~/Dropbox/91_OpenPDK/TR-1um/libs.tech/spice/models/ip62_models"
VDD = 5.0

# DFFRB's real transistor-level body, copied verbatim from
# simulations/DFFRB.spice (subckt DFFRB VDD QB D Q RSTB GND CK) --
# renamed VDD/GND references below to match this testbench's own VDD/VSS
# rails when instantiated (the subckt's OWN internal VDD/GND pins are
# just its formal port names, unrelated to the VSS-vs-GND ngspice
# reserved-word issue found this session -- only the TESTBENCH's own
# top-level nodes need to avoid the literal name "GND").
DFFRB_BODY = """\
.subckt DFFRB VDD QB D Q RSTB GND CK
XM2 net1 D VDD VDD PMOS w=5.2u l=1u
XM1 net2 CKP net1 VDD PMOS w=5.2u l=1u
XM7 net2 CKB net3 GND NMOS w=3.4u l=1u
XM8 net3 D GND GND NMOS w=3.4u l=1u
XM10 QM net2 VDD VDD PMOS w=5.2u l=1u
XM11 QM net2 GND GND NMOS w=3.4u l=1u
XM13 net4 QM GND GND NMOS w=3.4u l=1u
XM15 net4 CKP net2 GND NMOS w=3.4u l=1u
XM22 QB QS VDD VDD PMOS w=10.4u l=1u
XM3 net4 QM VDD VDD PMOS w=5.2u l=1u
XM4 net2 CKB net4 VDD PMOS w=5.2u l=1u
XM5 QS CKP QM GND NMOS w=3.4u l=1u
XM6 QM CKB QS VDD PMOS w=5.2u l=1u
XM9 net5 QB GND GND NMOS w=3.4u l=1u
XM12 net5 QB VDD VDD PMOS w=5.2u l=1u
XM14 net5 CKB QS GND NMOS w=3.4u l=1u
XM16 QS CKP net5 VDD PMOS w=5.2u l=1u
XM17 QB RSTB net6 GND NMOS w=3.4u l=1u
XM18 Q QB VDD VDD PMOS w=10.4u l=1u
XM19 Q QB GND GND NMOS w=3.4u l=1u
XM20 CKB CK VDD VDD PMOS w=10.4u l=1u
XM21 CKB CK GND GND NMOS w=3.4u l=1u
XM23 CKP CKB VDD VDD PMOS w=10.4u l=1u
XM24 CKP CKB GND GND NMOS w=3.4u l=1u
XM25 net6 QS GND GND NMOS w=3.4u l=1u
XM26 QB RSTB VDD VDD PMOS w=10.4u l=1u
.ends DFFRB
"""

DECK = f"""\
* dffrb_reset_tb.spi -- auto-generated by script/gen_dffrb_reset_tb.py
* DO NOT hand-edit -- regenerate instead.
*
* Real transistor-level check of DFFRB's slave-latch node QS after
* RSTB releases, with CK held fixed (never toggled) -- see
* gen_dffrb_reset_tb.py's module docstring and design_notes.md 76.30/
* 76.31 for the full motivation. Vdd={VDD}V, matching this project's own
* other testbenches (simulations/*_AC.spice, simulations/IO_DC.spice).
*
* NOTE: local ground rail is VSS, not GND -- see the DFFRB_BODY's own
* GND formal pin name is fine (it's a subcircuit-local formal name, not
* a top-level node), but the top-level instantiation below binds it to
* VSS (this testbench's actual ground net), avoiding ngspice's reserved
* "gnd" alias for node 0 (design_notes.md 76.29's ngspice error).

.include '{MODEL_INCLUDE}'

{DFFRB_BODY}
* Instantiate DFFRB, binding its formal GND pin to our real VSS node.
X1 VDD QB D Q RSTB VSS CK DFFRB

VVDD VDD 0 DC {VDD}
VVSS VSS 0 DC 0

* D and CK held fixed -- this test is about QS's own retention, not
* data capture. CK held HIGH, matching this project's SCL-idle-high
* convention (preamble()/gen_reset_check() hold SCL high at rest).
VD D 0 DC 0
VCK CK 0 DC {VDD}

* RSTB: pulsed low (asserted, active-low) for 100ns, then released and
* left high for the rest of a long transient.
VRSTB RSTB 0 PWL(0n 0 1n 0 2n {VDD} 100n {VDD} 101n {VDD})

* Give QS the same "force QS=0" initial condition the .cmd scripts use,
* right before RSTB releases -- then nothing touches it again. Does it
* actually hold near 0V, or drift?
.ic V(x1.qs)=0

* Print interval 10ns, out to 40us -- comfortably covers this session's
* longest real IRSIM test (irsim_test_main.cmd, ends ~t=39260ns), i.e.
* if QS still hasn't drifted through a threshold by 40us, the "force
* once at cold start and let it hold" approach is realistic for every
* test actually run this session. 4000 output points -- small/fast.
.control
  tran 10n 40u uic
  set filetype=ascii
  write dffrb_reset_tb.raw
  print v(rstb) v(x1.qs) v(x1.qb) v(x1.q) > dffrb_reset_tb_print.txt
.endc

.end
"""


def main():
    outdir = pathlib.Path(__file__).resolve().parent.parent / "irsim"
    path = outdir / "dffrb_reset_tb.spi"
    path.write_text(DECK)
    print(f"wrote {path}")
    print()
    print("Run locally with ngspice (not available in this sandbox):")
    print("  cd irsim")
    print("  ngspice -b dffrb_reset_tb.spi")
    print()
    print("Then check dffrb_reset_tb_print.txt (or run interactively and")
    print("`plot v(x1.qs) v(x1.qb) v(x1.q) v(rstb)` for a visual look) --")
    print("does V(x1.qs) stay near 0V for a useful length of time after")
    print("RSTB releases (t>101ns), or does it drift toward mid-rail/the")
    print("opposite rail? At what real time (if any) does it cross a")
    print("logic threshold?")


if __name__ == "__main__":
    main()
