/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, Clang /workspace/YoWASP/yosys/wasi-sdk-33.0-x86_64-linux/share/cmake/../..//bin/clang++ 22.1.0) */

(* top =  1  *)
(* src = "src/i2c_slave_async.v:63.1-196.10" *)
module i2c_slave_async(VDD, GND, rst_n, scl, sda_in, sda_oe, tx_data, rx_data, rx_valid, addr_match, rw, busy);
  (* src = "src/i2c_slave_async.v:66.23-66.26" *)
  input VDD;
  wire VDD;
  (* src = "src/i2c_slave_async.v:66.28-66.31" *)
  input GND;
  wire GND;
  (* src = "src/i2c_slave_async.v:67.23-67.28" *)
  input rst_n;
  wire rst_n;
  (* src = "src/i2c_slave_async.v:68.23-68.26" *)
  input scl;
  wire scl;
  (* src = "src/i2c_slave_async.v:69.23-69.29" *)
  input sda_in;
  wire sda_in;
  (* src = "src/i2c_slave_async.v:70.23-70.29" *)
  output sda_oe;
  wire sda_oe;
  (* src = "src/i2c_slave_async.v:72.23-72.30" *)
  input [7:0] tx_data;
  wire [7:0] tx_data;
  (* src = "src/i2c_slave_async.v:73.23-73.30" *)
  output [7:0] rx_data;
  wire [7:0] rx_data;
  (* src = "src/i2c_slave_async.v:74.23-74.31" *)
  output rx_valid;
  wire rx_valid;
  (* src = "src/i2c_slave_async.v:75.23-75.33" *)
  output addr_match;
  wire addr_match;
  (* src = "src/i2c_slave_async.v:76.23-76.25" *)
  output rw;
  wire rw;
  (* src = "src/i2c_slave_async.v:77.23-77.27" *)
  output busy;
  wire busy;
  (* src = "src/i2c_slave_async.v:113.5-158.8" *)
  wire [3:0] _000_;
  (* src = "src/i2c_slave_async.v:113.5-158.8" *)
  wire [2:0] _001_;
  (* src = "src/i2c_slave_async.v:174.5-193.8" *)
  wire _002_;
  (* src = "src/i2c_slave_async.v:174.5-193.8" *)
  wire _003_;
  (* src = "src/i2c_slave_async.v:108.15-108.22" *)
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  (* src = "src/i2c_slave_async.v:106.15-106.22" *)
  wire _073_;
  (* src = "src/i2c_slave_async.v:106.15-106.22" *)
  wire _074_;
  (* src = "src/i2c_slave_async.v:106.15-106.22" *)
  wire _075_;
  (* src = "src/i2c_slave_async.v:106.15-106.22" *)
  wire _076_;
  (* src = "src/i2c_slave_async.v:77.23-77.27" *)
  wire _077_;
  (* src = "src/i2c_slave_async.v:97.10-97.18" *)
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire RSTB1;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  (* src = "src/i2c_slave_async.v:105.15-105.20" *)
  wire _155_;
  (* src = "src/i2c_slave_async.v:105.15-105.20" *)
  wire _156_;
  (* src = "src/i2c_slave_async.v:105.15-105.20" *)
  wire _157_;
  (* src = "src/i2c_slave_async.v:67.23-67.28" *)
  wire _158_;
  (* src = "src/i2c_slave_async.v:108.24-108.30" *)
  wire _159_;
  (* src = "src/i2c_slave_async.v:109.15-109.24" *)
  wire _160_;
  (* src = "src/i2c_slave_async.v:109.15-109.24" *)
  wire _161_;
  (* src = "src/i2c_slave_async.v:109.15-109.24" *)
  wire _162_;
  (* src = "src/i2c_slave_async.v:109.15-109.24" *)
  wire _163_;
  (* src = "src/i2c_slave_async.v:109.15-109.24" *)
  wire _164_;
  (* src = "src/i2c_slave_async.v:109.15-109.24" *)
  wire _165_;
  (* src = "src/i2c_slave_async.v:109.15-109.24" *)
  wire _166_;
  (* src = "src/i2c_slave_async.v:109.15-109.24" *)
  wire _167_;
  (* src = "src/i2c_slave_async.v:74.23-74.31" *)
  wire _168_;
  (* src = "src/i2c_slave_async.v:68.23-68.26" *)
  wire _169_;
  (* src = "src/i2c_slave_async.v:90.10-90.15" *)
  wire _170_;
  (* src = "src/i2c_slave_async.v:69.23-69.29" *)
  wire _171_;
  (* src = "src/i2c_slave_async.v:107.15-107.20" *)
  wire _172_;
  (* src = "src/i2c_slave_async.v:107.15-107.20" *)
  wire _173_;
  (* src = "src/i2c_slave_async.v:107.15-107.20" *)
  wire _174_;
  (* src = "src/i2c_slave_async.v:107.15-107.20" *)
  wire _175_;
  (* src = "src/i2c_slave_async.v:107.15-107.20" *)
  wire _176_;
  (* src = "src/i2c_slave_async.v:107.15-107.20" *)
  wire _177_;
  (* src = "src/i2c_slave_async.v:107.15-107.20" *)
  wire _178_;
  (* src = "src/i2c_slave_async.v:93.10-93.21" *)
  wire RSTB2;
  (* src = "src/i2c_slave_async.v:72.23-72.30" *)
  wire _180_;
  (* src = "src/i2c_slave_async.v:72.23-72.30" *)
  wire _181_;
  (* src = "src/i2c_slave_async.v:72.23-72.30" *)
  wire _182_;
  (* src = "src/i2c_slave_async.v:72.23-72.30" *)
  wire _183_;
  (* src = "src/i2c_slave_async.v:72.23-72.30" *)
  wire _184_;
  (* src = "src/i2c_slave_async.v:72.23-72.30" *)
  wire _185_;
  (* src = "src/i2c_slave_async.v:72.23-72.30" *)
  wire _186_;
  (* src = "src/i2c_slave_async.v:72.23-72.30" *)
  wire _187_;
  (* src = "src/i2c_slave_async.v:172.15-172.20" *)
  wire _188_;
  (* src = "src/i2c_slave_async.v:172.15-172.20" *)
  wire _189_;
  (* src = "src/i2c_slave_async.v:172.15-172.20" *)
  wire _190_;
  (* src = "src/i2c_slave_async.v:172.15-172.20" *)
  wire _191_;
  (* src = "src/i2c_slave_async.v:172.15-172.20" *)
  wire _192_;
  (* src = "src/i2c_slave_async.v:172.15-172.20" *)
  wire _193_;
  (* src = "src/i2c_slave_async.v:172.15-172.20" *)
  wire _194_;
  (* src = "src/i2c_slave_async.v:172.15-172.20" *)
  wire _195_;
  (* src = "src/i2c_slave_async.v:93.24-93.36" *)
  wire _196_;
  (* src = "src/i2c_slave_async.v:94.24-94.36" *)
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire [1:0] _318_;
  wire _319_;
  wire [2:0] _320_;
  wire [1:0] _321_;
  wire [1:0] _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire [1:0] _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire [2:0] _341_;
  wire _342_;
  wire _343_;
  wire [2:0] _344_;
  wire _345_;
  wire _346_;
  wire [2:0] _347_;
  wire _348_;
  wire _349_;
  wire [2:0] _350_;
  wire _351_;
  wire _352_;
  wire [1:0] _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  (* src = "src/i2c_slave_async.v:126.37-126.66" *)
  wire _371_;
  (* src = "src/i2c_slave_async.v:152.33-152.47" *)
  wire _372_;
  (* src = "src/i2c_slave_async.v:183.25-183.40" *)
  wire _373_;
  (* src = "src/i2c_slave_async.v:103.28-103.34" *)
  wire _374_;
  (* src = "src/i2c_slave_async.v:169.41-169.46" *)
  wire _375_;
  (* src = "src/i2c_slave_async.v:185.37-185.48" *)
  wire _376_;
  (* src = "src/i2c_slave_async.v:187.37-187.56" *)
  wire _377_;
  (* src = "src/i2c_slave_async.v:94.30-94.36" *)
  wire _378_;
  wire [2:0] _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire [3:0] _385_;
  (* force_downto = 32'd1 *)
  (* src = "src/i2c_slave_async.v:187.43-187.56|/share/techmap.v:135.22-135.23" *)
  (* unused_bits = "4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _386_;
  (* force_downto = 32'd1 *)
  (* src = "src/i2c_slave_async.v:187.43-187.56|/share/techmap.v:137.23-137.24" *)
  wire [0:0] _387_;
  (* force_downto = 32'd1 *)
  (* src = "src/i2c_slave_async.v:149.32-149.46|/share/techmap.v:274.23-274.25" *)
  (* unused_bits = "3" *)
  wire [3:0] _388_;
  (* force_downto = 32'd1 *)
  (* src = "src/i2c_slave_async.v:149.32-149.46|/share/techmap.v:270.26-270.27" *)
  wire [3:0] _389_;
  (* src = "src/i2c_slave_async.v:187.43-187.56|/share/techmap.v:157.2-184.5" *)
  (* unused_bits = "16 17 18 19 20 21 22 23" *)
  wire [23:0] _390_;
  (* src = "src/i2c_slave_async.v:187.43-187.56|/share/techmap.v:157.2-184.5" *)
  (* unused_bits = "1 3 5 7 15 16 17 18 19 20 21 22 23" *)
  wire [23:0] _391_;
  (* src = "src/i2c_slave_async.v:187.43-187.56|/share/techmap.v:157.2-184.5" *)
  (* unused_bits = "1 2 3 5 6 7 13 14 15 16 17 18 19 20 21 22 23" *)
  wire [23:0] _392_;
  (* src = "src/i2c_slave_async.v:187.43-187.56|/share/techmap.v:157.2-184.5" *)
  (* unused_bits = "1 2 3 4 5 6 7 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23" *)
  wire [23:0] _393_;
  (* force_downto = 32'd1 *)
  (* src = "src/i2c_slave_async.v:187.44-187.55|/share/techmap.v:279.21-279.23" *)
  wire [31:0] _394_;
  (* force_downto = 32'd1 *)
  (* src = "src/i2c_slave_async.v:187.44-187.55|/share/techmap.v:274.23-274.25" *)
  wire [31:0] _395_;
  (* src = "src/i2c_slave_async.v:187.44-187.55|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _396_;
  (* src = "src/i2c_slave_async.v:187.44-187.55|/share/techmap.v:293.27-293.63|/share/techmap.v:240.19-240.41" *)
  wire _397_;
  (* src = "src/i2c_slave_async.v:133.43-133.75" *)
  wire [2:0] _398_;
  (* src = "src/i2c_slave_async.v:133.32-133.88" *)
  wire [2:0] _399_;
  (* src = "src/i2c_slave_async.v:108.15-108.22" *)
  wire addr_ok;
  (* src = "src/i2c_slave_async.v:106.15-106.22" *)
  wire [3:0] bit_cnt;
  (* src = "src/i2c_slave_async.v:97.10-97.18" *)
  wire busy_clr;
  (* src = "src/i2c_slave_async.v:105.15-105.20" *)
  wire [2:0] phase;
  (* src = "src/i2c_slave_async.v:98.10-98.12" *)
  wire qn;
  (* src = "src/i2c_slave_async.v:103.10-103.24" *)
  wire rst_scl_domain;
  (* src = "src/i2c_slave_async.v:169.10-169.26" *)
  wire rst_sdaoe_domain;
  (* src = "src/i2c_slave_async.v:108.24-108.30" *)
  wire rw_bit;
  (* src = "src/i2c_slave_async.v:109.15-109.24" *)
  wire [7:0] rx_data_r;
  (* src = "src/i2c_slave_async.v:166.10-166.15" *)
  wire scl_n;
  (* src = "src/i2c_slave_async.v:90.10-90.15" *)
  wire sda_d;
  (* src = "src/i2c_slave_async.v:171.9-171.17" *)
  wire sda_oe_r;
  (* src = "src/i2c_slave_async.v:107.15-107.20" *)
  (* unused_bits = "7" *)
  wire [7:0] shreg;
  (* src = "src/i2c_slave_async.v:111.16-111.26" *)
  wire [7:0] shreg_next;
  (* src = "src/i2c_slave_async.v:93.10-93.21" *)
  wire start_pulse;
  (* src = "src/i2c_slave_async.v:94.10-94.20" *)
  wire stop_pulse;
  (* src = "src/i2c_slave_async.v:172.15-172.20" *)
  wire [7:0] txreg;
  wire scl_row0;
  wire scl_row1;
  wire scl_row2;
  wire scl_row3;
  wire scl_n_row1;
  wire scl_n_row2;
  INV_X1 _400_ (
    .A(_073_),
    .Y(_079_)
  );
  INV_X1 _401_ (
    .A(_074_),
    .Y(_080_)
  );
  INV_X1 _402_ (
    .A(_075_),
    .Y(_081_)
  );
  INV_X1 _403_ (
    .A(_014_),
    .Y(_082_)
  );
  INV_X1 _404_ (
    .A(_013_),
    .Y(_083_)
  );
  INV_X1 _405_ (
    .A(_159_),
    .Y(_084_)
  );
  INV_X1 _406_ (
    .A(_158_),
    .Y(RSTB1)
  );
  INV_X1 _407_ (
    .A(_170_),
    .Y(_086_)
  );
  NAND2 _408_ (
    .A(scl_row2),
    .B(_170_),
    .Y(_087_)
  );
  NOR2 _409_ (
    .A(_171_),
    .B(_087_),
    .Y(RSTB2)
  );
  NOR2 _410_ (
    .A(RSTB1),
    .B(RSTB2),
    .Y(_015_)
  );
  AND2_X1 _411_ (
    .A(_077_),
    .B(_158_),
    .Y(_018_)
  );
  OR2 _412_ (
    .A(_157_),
    .B(_011_),
    .Y(_088_)
  );
  NOR2 _413_ (
    .A(_005_),
    .B(_088_),
    .Y(_168_)
  );
  AND2_X1 _414_ (
    .A(_073_),
    .B(_074_),
    .Y(_089_)
  );
  NAND2 _415_ (
    .A(_075_),
    .B(_089_),
    .Y(_090_)
  );
  OR2 _416_ (
    .A(_156_),
    .B(_155_),
    .Y(_091_)
  );
  NOR2 _417_ (
    .A(_012_),
    .B(_091_),
    .Y(_092_)
  );
  INV_X1 _418_ (
    .A(_092_),
    .Y(_093_)
  );
  NOR2 _419_ (
    .A(_157_),
    .B(_091_),
    .Y(_094_)
  );
  NOR2 _420_ (
    .A(_155_),
    .B(_088_),
    .Y(_095_)
  );
  NOR3 _421_ (
    .A(_092_),
    .B(_094_),
    .C(_095_),
    .Y(_096_)
  );
  OR3 _422_ (
    .A(_092_),
    .B(_094_),
    .C(_095_),
    .Y(_097_)
  );
  NOR4 _423_ (
    .A(_076_),
    .B(_010_),
    .C(_008_),
    .D(_009_),
    .Y(_098_)
  );
  OR2 _424_ (
    .A(_096_),
    .B(_098_),
    .Y(_099_)
  );
  AND2_X1 _425_ (
    .A(_093_),
    .B(_099_),
    .Y(_100_)
  );
  NAND2 _426_ (
    .A(_093_),
    .B(_099_),
    .Y(_101_)
  );
  NAND2 _427_ (
    .A(_090_),
    .B(_101_),
    .Y(_102_)
  );
  OR2 _428_ (
    .A(_005_),
    .B(_156_),
    .Y(_103_)
  );
  NOR2 _429_ (
    .A(_012_),
    .B(_103_),
    .Y(_104_)
  );
  NOR2 _430_ (
    .A(_157_),
    .B(_103_),
    .Y(_105_)
  );
  NOR4 _431_ (
    .A(_168_),
    .B(_097_),
    .C(_104_),
    .D(_105_),
    .Y(_106_)
  );
  INV_X1 _432_ (
    .A(_106_),
    .Y(_107_)
  );
  NAND2 _433_ (
    .A(_102_),
    .B(_107_),
    .Y(_108_)
  );
  NAND2 _434_ (
    .A(_089_),
    .B(_101_),
    .Y(_109_)
  );
  NAND2 _435_ (
    .A(_081_),
    .B(_109_),
    .Y(_110_)
  );
  AND2_X1 _436_ (
    .A(_108_),
    .B(_110_),
    .Y(_048_)
  );
  NAND2 _437_ (
    .A(_074_),
    .B(_106_),
    .Y(_111_)
  );
  NOR2 _438_ (
    .A(_073_),
    .B(_074_),
    .Y(_112_)
  );
  OR3 _439_ (
    .A(_089_),
    .B(_100_),
    .C(_112_),
    .Y(_113_)
  );
  NAND2 _440_ (
    .A(_111_),
    .B(_113_),
    .Y(_049_)
  );
  NAND2 _441_ (
    .A(_073_),
    .B(_106_),
    .Y(_114_)
  );
  NAND2 _442_ (
    .A(_010_),
    .B(_097_),
    .Y(_115_)
  );
  NAND2 _443_ (
    .A(_114_),
    .B(_115_),
    .Y(_050_)
  );
  NAND2 _444_ (
    .A(_095_),
    .B(_098_),
    .Y(_116_)
  );
  MUX2 _445_ (
    .A(_177_),
    .B(_166_),
    .S(_116_),
    .Y(_051_)
  );
  MUX2 _446_ (
    .A(_176_),
    .B(_165_),
    .S(_116_),
    .Y(_052_)
  );
  MUX2 _447_ (
    .A(_175_),
    .B(_164_),
    .S(_116_),
    .Y(_053_)
  );
  MUX2 _448_ (
    .A(_174_),
    .B(_163_),
    .S(_116_),
    .Y(_054_)
  );
  MUX2 _449_ (
    .A(_173_),
    .B(_162_),
    .S(_116_),
    .Y(_055_)
  );
  MUX2 _450_ (
    .A(_172_),
    .B(_161_),
    .S(_116_),
    .Y(_056_)
  );
  MUX2 _451_ (
    .A(_171_),
    .B(_160_),
    .S(_116_),
    .Y(_057_)
  );
  NOR2 _452_ (
    .A(_076_),
    .B(_075_),
    .Y(_117_)
  );
  NAND2 _453_ (
    .A(_112_),
    .B(_117_),
    .Y(_118_)
  );
  OR2 _454_ (
    .A(_093_),
    .B(_118_),
    .Y(_119_)
  );
  MUX2 _455_ (
    .A(_186_),
    .B(_194_),
    .S(_119_),
    .Y(_058_)
  );
  MUX2 _456_ (
    .A(_185_),
    .B(_193_),
    .S(_119_),
    .Y(_059_)
  );
  MUX2 _457_ (
    .A(_184_),
    .B(_192_),
    .S(_119_),
    .Y(_060_)
  );
  MUX2 _458_ (
    .A(_183_),
    .B(_191_),
    .S(_119_),
    .Y(_061_)
  );
  MUX2 _459_ (
    .A(_182_),
    .B(_190_),
    .S(_119_),
    .Y(_062_)
  );
  MUX2 _460_ (
    .A(_181_),
    .B(_189_),
    .S(_119_),
    .Y(_063_)
  );
  MUX2 _461_ (
    .A(_180_),
    .B(_188_),
    .S(_119_),
    .Y(_064_)
  );
  NAND2 _462_ (
    .A(_004_),
    .B(_083_),
    .Y(_120_)
  );
  AND2_X1 _463_ (
    .A(_105_),
    .B(_120_),
    .Y(_121_)
  );
  NAND2 _464_ (
    .A(_171_),
    .B(_104_),
    .Y(_122_)
  );
  NAND2 _465_ (
    .A(_116_),
    .B(_122_),
    .Y(_123_)
  );
  NAND2 _466_ (
    .A(_099_),
    .B(_107_),
    .Y(_124_)
  );
  NOR4 _467_ (
    .A(_168_),
    .B(_121_),
    .C(_123_),
    .D(_124_),
    .Y(_125_)
  );
  NOR2 _468_ (
    .A(_156_),
    .B(_099_),
    .Y(_126_)
  );
  NOR2 _469_ (
    .A(_125_),
    .B(_126_),
    .Y(_065_)
  );
  AND2_X1 _470_ (
    .A(_097_),
    .B(_098_),
    .Y(_066_)
  );
  NOR2 _471_ (
    .A(_157_),
    .B(_099_),
    .Y(_127_)
  );
  NAND2 _472_ (
    .A(_004_),
    .B(_084_),
    .Y(_128_)
  );
  AND2_X1 _473_ (
    .A(_105_),
    .B(_128_),
    .Y(_129_)
  );
  NOR4 _474_ (
    .A(_092_),
    .B(_104_),
    .C(_124_),
    .D(_129_),
    .Y(_130_)
  );
  NOR2 _475_ (
    .A(_127_),
    .B(_130_),
    .Y(_067_)
  );
  NAND2 _476_ (
    .A(_094_),
    .B(_098_),
    .Y(_131_)
  );
  MUX2 _477_ (
    .A(_171_),
    .B(_159_),
    .S(_131_),
    .Y(_068_)
  );
  NOR2 _478_ (
    .A(_187_),
    .B(_119_),
    .Y(_132_)
  );
  MUX2 _479_ (
    .A(_187_),
    .B(_195_),
    .S(_119_),
    .Y(_069_)
  );
  MUX2 _480_ (
    .A(_178_),
    .B(_167_),
    .S(_116_),
    .Y(_070_)
  );
  NAND3 _481_ (
    .A(_073_),
    .B(_080_),
    .C(_194_),
    .Y(_133_)
  );
  NAND2 _482_ (
    .A(_195_),
    .B(_112_),
    .Y(_134_)
  );
  NAND2 _483_ (
    .A(_192_),
    .B(_089_),
    .Y(_135_)
  );
  NAND3 _484_ (
    .A(_079_),
    .B(_074_),
    .C(_193_),
    .Y(_136_)
  );
  NAND4 _485_ (
    .A(_133_),
    .B(_134_),
    .C(_135_),
    .D(_136_),
    .Y(_137_)
  );
  NAND2 _486_ (
    .A(_008_),
    .B(_137_),
    .Y(_138_)
  );
  NAND2 _487_ (
    .A(_081_),
    .B(_138_),
    .Y(_139_)
  );
  NAND2 _488_ (
    .A(_191_),
    .B(_112_),
    .Y(_140_)
  );
  NAND3 _489_ (
    .A(_073_),
    .B(_080_),
    .C(_190_),
    .Y(_141_)
  );
  NAND3 _490_ (
    .A(_079_),
    .B(_074_),
    .C(_189_),
    .Y(_142_)
  );
  NAND2 _491_ (
    .A(_188_),
    .B(_089_),
    .Y(_143_)
  );
  NAND4 _492_ (
    .A(_140_),
    .B(_141_),
    .C(_142_),
    .D(_143_),
    .Y(_144_)
  );
  NOR2 _493_ (
    .A(_081_),
    .B(_144_),
    .Y(_145_)
  );
  NOR3 _494_ (
    .A(_076_),
    .B(_082_),
    .C(_145_),
    .Y(_146_)
  );
  NAND2 _495_ (
    .A(_139_),
    .B(_146_),
    .Y(_147_)
  );
  NAND3 _496_ (
    .A(_092_),
    .B(_118_),
    .C(_147_),
    .Y(_148_)
  );
  AND2_X1 _497_ (
    .A(_004_),
    .B(_105_),
    .Y(_149_)
  );
  NOR3 _498_ (
    .A(_168_),
    .B(_132_),
    .C(_149_),
    .Y(_150_)
  );
  NAND2 _499_ (
    .A(_148_),
    .B(_150_),
    .Y(_003_)
  );
  NOR2 _500_ (
    .A(_090_),
    .B(_100_),
    .Y(_151_)
  );
  MUX2 _501_ (
    .A(_151_),
    .B(_108_),
    .S(_076_),
    .Y(_071_)
  );
  NAND3 _502_ (
    .A(_171_),
    .B(scl_row2),
    .C(_086_),
    .Y(_152_)
  );
  NAND2 _503_ (
    .A(_158_),
    .B(_152_),
    .Y(_078_)
  );
  OR4 _504_ (
    .A(_006_),
    .B(_007_),
    .C(_177_),
    .D(_174_),
    .Y(_153_)
  );
  NOR4 _505_ (
    .A(_175_),
    .B(_172_),
    .C(_173_),
    .D(_153_),
    .Y(_154_)
  );
  MUX2 _506_ (
    .A(_154_),
    .B(_004_),
    .S(_131_),
    .Y(_072_)
  );
  NOR2 _507_ (
    .A(RSTB1),
    .B(RSTB2),
    .Y(_016_)
  );
  NOR2 _508_ (
    .A(RSTB1),
    .B(RSTB2),
    .Y(_017_)
  );
  NOR2 _509_ (
    .A(RSTB1),
    .B(RSTB2),
    .Y(_019_)
  );
  NOR2 _510_ (
    .A(RSTB1),
    .B(RSTB2),
    .Y(_020_)
  );
  NOR2 _511_ (
    .A(RSTB1),
    .B(RSTB2),
    .Y(_021_)
  );
  NOR2 _512_ (
    .A(RSTB1),
    .B(RSTB2),
    .Y(_022_)
  );
  AND2_X1 _513_ (
    .A(_077_),
    .B(_158_),
    .Y(_023_)
  );
  AND2_X1 _514_ (
    .A(_077_),
    .B(_158_),
    .Y(_024_)
  );
  AND2_X1 _515_ (
    .A(_077_),
    .B(_158_),
    .Y(_025_)
  );
  AND2_X1 _516_ (
    .A(_077_),
    .B(_158_),
    .Y(_026_)
  );
  AND2_X1 _517_ (
    .A(_077_),
    .B(_158_),
    .Y(_027_)
  );
  AND2_X1 _518_ (
    .A(_077_),
    .B(_158_),
    .Y(_028_)
  );
  AND2_X1 _519_ (
    .A(_077_),
    .B(_158_),
    .Y(_029_)
  );
  NOR2 _520_ (
    .A(RSTB1),
    .B(RSTB2),
    .Y(_030_)
  );
  NOR2 _521_ (
    .A(RSTB1),
    .B(RSTB2),
    .Y(_031_)
  );
  NOR2 _522_ (
    .A(RSTB1),
    .B(RSTB2),
    .Y(_032_)
  );
  NOR2 _523_ (
    .A(RSTB1),
    .B(RSTB2),
    .Y(_033_)
  );
  NOR2 _524_ (
    .A(RSTB1),
    .B(RSTB2),
    .Y(_034_)
  );
  NOR2 _525_ (
    .A(RSTB1),
    .B(RSTB2),
    .Y(_035_)
  );
  NOR2 _526_ (
    .A(RSTB1),
    .B(RSTB2),
    .Y(_036_)
  );
  NOR2 _527_ (
    .A(RSTB1),
    .B(RSTB2),
    .Y(_037_)
  );
  NOR2 _528_ (
    .A(RSTB1),
    .B(RSTB2),
    .Y(_038_)
  );
  NOR2 _529_ (
    .A(RSTB1),
    .B(RSTB2),
    .Y(_039_)
  );
  NOR2 _530_ (
    .A(RSTB1),
    .B(RSTB2),
    .Y(_040_)
  );
  NOR2 _531_ (
    .A(RSTB1),
    .B(RSTB2),
    .Y(_041_)
  );
  NOR2 _532_ (
    .A(RSTB1),
    .B(RSTB2),
    .Y(_042_)
  );
  NOR2 _533_ (
    .A(RSTB1),
    .B(RSTB2),
    .Y(_043_)
  );
  NOR2 _534_ (
    .A(RSTB1),
    .B(RSTB2),
    .Y(_044_)
  );
  AND2_X1 _535_ (
    .A(_077_),
    .B(_158_),
    .Y(_045_)
  );
  NOR2 _536_ (
    .A(RSTB1),
    .B(RSTB2),
    .Y(_046_)
  );
  NOR2 _537_ (
    .A(RSTB1),
    .B(RSTB2),
    .Y(_047_)
  );
  (* src = "src/i2c_slave_async.v:113.5-158.8" *)
  DFFR _538_ (
    .CK(scl_row0),
    .D(_310_),
    .Q(phase[0]),
    .QB(_202_),
    .RSTB(_287_)
  );
  (* src = "src/i2c_slave_async.v:113.5-158.8" *)
  DFFR _539_ (
    .CK(scl_row0),
    .D(_309_),
    .Q(phase[1]),
    .QB(_223_),
    .RSTB(_266_)
  );
  (* src = "src/i2c_slave_async.v:113.5-158.8" *)
  DFFR _540_ (
    .CK(scl_row0),
    .D(_311_),
    .Q(phase[2]),
    .QB(_225_),
    .RSTB(_264_)
  );
  (* src = "src/i2c_slave_async.v:113.5-158.8" *)
  DFFR _541_ (
    .CK(scl_row0),
    .D(_312_),
    .Q(rw_bit),
    .QB(_226_),
    .RSTB(_263_)
  );
  (* src = "src/i2c_slave_async.v:174.5-193.8" *)
  DFFR _542_ (
    .CK(scl_n_row2),
    .D(_308_),
    .Q(txreg[0]),
    .QB(_222_),
    .RSTB(_267_)
  );
  (* src = "src/i2c_slave_async.v:174.5-193.8" *)
  DFFR _543_ (
    .CK(scl_n_row2),
    .D(_307_),
    .Q(txreg[1]),
    .QB(_221_),
    .RSTB(_268_)
  );
  (* src = "src/i2c_slave_async.v:174.5-193.8" *)
  DFFR _544_ (
    .CK(scl_n_row2),
    .D(_306_),
    .Q(txreg[2]),
    .QB(_220_),
    .RSTB(_269_)
  );
  (* src = "src/i2c_slave_async.v:174.5-193.8" *)
  DFFR _545_ (
    .CK(scl_n_row1),
    .D(_305_),
    .Q(txreg[3]),
    .QB(_219_),
    .RSTB(_270_)
  );
  (* src = "src/i2c_slave_async.v:174.5-193.8" *)
  DFFR _546_ (
    .CK(scl_n_row2),
    .D(_304_),
    .Q(txreg[4]),
    .QB(_218_),
    .RSTB(_271_)
  );
  (* src = "src/i2c_slave_async.v:174.5-193.8" *)
  DFFR _547_ (
    .CK(scl_n_row2),
    .D(_303_),
    .Q(txreg[5]),
    .QB(_217_),
    .RSTB(_272_)
  );
  (* src = "src/i2c_slave_async.v:174.5-193.8" *)
  DFFR _548_ (
    .CK(scl_n_row2),
    .D(_302_),
    .Q(txreg[6]),
    .QB(_216_),
    .RSTB(_273_)
  );
  (* src = "src/i2c_slave_async.v:174.5-193.8" *)
  DFFR _549_ (
    .CK(scl_n_row1),
    .D(_313_),
    .Q(txreg[7]),
    .QB(_200_),
    .RSTB(_289_)
  );
  (* src = "src/i2c_slave_async.v:113.5-158.8" *)
  DFFR _550_ (
    .CK(scl_row0),
    .D(_301_),
    .Q(rx_data_r[0]),
    .QB(_215_),
    .RSTB(_274_)
  );
  (* src = "src/i2c_slave_async.v:113.5-158.8" *)
  DFFR _551_ (
    .CK(scl_row3),
    .D(_300_),
    .Q(rx_data_r[1]),
    .QB(_214_),
    .RSTB(_275_)
  );
  (* src = "src/i2c_slave_async.v:113.5-158.8" *)
  DFFR _552_ (
    .CK(scl_row3),
    .D(_299_),
    .Q(rx_data_r[2]),
    .QB(_213_),
    .RSTB(_276_)
  );
  (* src = "src/i2c_slave_async.v:113.5-158.8" *)
  DFFR _553_ (
    .CK(scl_row3),
    .D(_298_),
    .Q(rx_data_r[3]),
    .QB(_212_),
    .RSTB(_277_)
  );
  (* src = "src/i2c_slave_async.v:113.5-158.8" *)
  DFFR _554_ (
    .CK(scl_row2),
    .D(_297_),
    .Q(rx_data_r[4]),
    .QB(_211_),
    .RSTB(_278_)
  );
  (* src = "src/i2c_slave_async.v:113.5-158.8" *)
  DFFR _555_ (
    .CK(scl_row3),
    .D(_296_),
    .Q(rx_data_r[5]),
    .QB(_210_),
    .RSTB(_279_)
  );
  (* src = "src/i2c_slave_async.v:113.5-158.8" *)
  DFFR _556_ (
    .CK(scl_row3),
    .D(_295_),
    .Q(rx_data_r[6]),
    .QB(_209_),
    .RSTB(_280_)
  );
  (* src = "src/i2c_slave_async.v:113.5-158.8" *)
  DFFR _557_ (
    .CK(scl_row2),
    .D(_314_),
    .Q(rx_data_r[7]),
    .QB(_199_),
    .RSTB(_290_)
  );
  (* src = "src/i2c_slave_async.v:113.5-158.8" *)
  DFFR _558_ (
    .CK(scl_row1),
    .D(_294_),
    .Q(bit_cnt[0]),
    .QB(_208_),
    .RSTB(_281_)
  );
  (* src = "src/i2c_slave_async.v:113.5-158.8" *)
  DFFR _559_ (
    .CK(scl_row1),
    .D(_293_),
    .Q(bit_cnt[1]),
    .QB(_207_),
    .RSTB(_282_)
  );
  (* src = "src/i2c_slave_async.v:113.5-158.8" *)
  DFFR _560_ (
    .CK(scl_row1),
    .D(_292_),
    .Q(bit_cnt[2]),
    .QB(_206_),
    .RSTB(_283_)
  );
  (* src = "src/i2c_slave_async.v:113.5-158.8" *)
  DFFR _561_ (
    .CK(scl_row1),
    .D(_315_),
    .Q(bit_cnt[3]),
    .QB(_229_),
    .RSTB(_260_)
  );
  (* src = "src/i2c_slave_async.v:113.5-158.8" *)
  DFFR _562_ (
    .CK(scl_row0),
    .D(_316_),
    .Q(addr_ok),
    .QB(_230_),
    .RSTB(_259_)
  );
  (* src = "src/i2c_slave_async.v:174.5-193.8" *)
  DFFR _563_ (
    .CK(scl_n_row2),
    .D(_002_),
    .Q(sda_oe_r),
    .QB(_227_),
    .RSTB(_262_)
  );
  (* src = "src/i2c_slave_async.v:113.5-158.8" *)
  DFFR _564_ (
    .CK(scl_row3),
    .D(sda_in),
    .Q(shreg[0]),
    .QB(_228_),
    .RSTB(_261_)
  );
  (* src = "src/i2c_slave_async.v:113.5-158.8" *)
  DFFR _565_ (
    .CK(scl_row3),
    .D(shreg[0]),
    .Q(shreg[1]),
    .QB(_198_),
    .RSTB(_291_)
  );
  (* src = "src/i2c_slave_async.v:113.5-158.8" *)
  DFFR _566_ (
    .CK(scl_row3),
    .D(shreg[1]),
    .Q(shreg[2]),
    .QB(_224_),
    .RSTB(_265_)
  );
  (* src = "src/i2c_slave_async.v:113.5-158.8" *)
  DFFR _567_ (
    .CK(scl_row3),
    .D(shreg[2]),
    .Q(shreg[3]),
    .QB(_201_),
    .RSTB(_288_)
  );
  (* src = "src/i2c_slave_async.v:113.5-158.8" *)
  DFFR _568_ (
    .CK(scl_row3),
    .D(shreg[3]),
    .Q(shreg[4]),
    .QB(_205_),
    .RSTB(_284_)
  );
  (* src = "src/i2c_slave_async.v:113.5-158.8" *)
  DFFR _569_ (
    .CK(scl_row3),
    .D(shreg[4]),
    .Q(shreg[5]),
    .QB(_204_),
    .RSTB(_285_)
  );
  (* src = "src/i2c_slave_async.v:113.5-158.8" *)
  DFFR _570_ (
    .CK(scl_row3),
    .D(shreg[5]),
    .Q(shreg[6]),
    .QB(_203_),
    .RSTB(_286_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/i2c_slave_async.v:91.10-91.65" *)
  DEL1 u_del_sda (
    .A(sda_in),
    .GND(GND),
    .VDD(VDD),
    .Y(sda_d)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/i2c_slave_async.v:167.12-167.64" *)
  INV_X1 u_inv_scl (
    .A(scl_row2),
    .GND(GND),
    .VDD(VDD),
    .Y(scl_n)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/i2c_slave_async.v:99.10-99.78" *)
  NOR2 u_lat_q (
    .A(busy_clr),
    .B(qn),
    .GND(GND),
    .VDD(VDD),
    .Y(busy)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/i2c_slave_async.v:100.10-100.78" *)
  NOR2 u_lat_qn (
    .A(start_pulse),
    .B(busy),
    .GND(GND),
    .VDD(VDD),
    .Y(qn)
  );
  assign { _386_[31:5], _386_[3] } = { _386_[4], _386_[4], _386_[4], _386_[4], _386_[4], _386_[4], _386_[4], _386_[4], _386_[4], _386_[4], _386_[4], _386_[4], _386_[4], _386_[4], _386_[4], _386_[4], _386_[4], _386_[4], _386_[4], _386_[4], _386_[4], _386_[4], _386_[4], _386_[4], _386_[4], _386_[4], _386_[4], bit_cnt[3] };
  assign _393_[8] = 1'hx;
  assign _392_[12:8] = 5'hxx;
  assign _390_[15:8] = 8'hxx;
  assign _391_[14:8] = 7'hxx;
  assign _389_[0] = _386_[0];
  assign { _394_[31:4], _394_[2:0] } = { 28'hfffffff, _386_[2:0] };
  assign _318_[1] = _250_;
  assign _353_[1] = _258_;
  assign _379_[1] = _379_[0];
  assign { _395_[31:4], _395_[2:0] } = { _395_[3], _395_[3], _395_[3], _395_[3], _395_[3], _395_[3], _395_[3], _395_[3], _395_[3], _395_[3], _395_[3], _395_[3], _395_[3], _395_[3], _395_[3], _395_[3], _395_[3], _395_[3], _395_[3], _395_[3], _395_[3], _395_[3], _395_[3], _395_[3], _395_[3], _395_[3], _395_[3], _395_[3], 3'h7 };
  assign _399_[0] = 1'h0;
  assign { _398_[2], _398_[0] } = { rw_bit, 1'h0 };
  assign _388_[0] = bit_cnt[0];
  assign shreg_next = { shreg[6:0], sda_in };
  assign rw = rw_bit;
  assign addr_match = addr_ok;
  assign rx_data = rx_data_r;
  assign sda_oe = sda_oe_r;
  assign _251_ = _202_;
  assign _255_ = _203_;
  assign _254_ = _205_;
  assign _386_[2] = _206_;
  assign _386_[1] = _207_;
  assign _386_[0] = _208_;
  assign _252_ = _223_;
  assign _253_ = _225_;
  assign _398_[1] = _226_;
  assign _394_[3] = _229_;
  assign _259_ = _015_;
  assign _260_ = _016_;
  assign _261_ = _017_;
  assign _262_ = _018_;
  assign _263_ = _019_;
  assign _264_ = _020_;
  assign _265_ = _021_;
  assign _266_ = _022_;
  assign _267_ = _023_;
  assign _268_ = _024_;
  assign _269_ = _025_;
  assign _270_ = _026_;
  assign _271_ = _027_;
  assign _272_ = _028_;
  assign _273_ = _029_;
  assign _274_ = _030_;
  assign _275_ = _031_;
  assign _276_ = _032_;
  assign _277_ = _033_;
  assign _278_ = _034_;
  assign _279_ = _035_;
  assign _280_ = _036_;
  assign _281_ = _037_;
  assign _282_ = _038_;
  assign _283_ = _039_;
  assign _284_ = _040_;
  assign rx_valid = _168_;
  assign _073_ = bit_cnt[0];
  assign _171_ = sda_in;
  assign _195_ = txreg[7];
  assign _076_ = bit_cnt[3];
  assign _188_ = txreg[0];
  assign _005_ = _202_;
  assign _156_ = phase[1];
  assign _157_ = phase[2];
  assign _012_ = _225_;
  assign _074_ = bit_cnt[1];
  assign _155_ = phase[0];
  assign _010_ = _208_;
  assign _075_ = bit_cnt[2];
  assign _011_ = _223_;
  assign _191_ = txreg[3];
  assign _004_ = addr_ok;
  assign _014_ = _229_;
  assign _008_ = _206_;
  assign _189_ = txreg[1];
  assign _193_ = txreg[5];
  assign _190_ = txreg[2];
  assign _009_ = _207_;
  assign _285_ = _041_;
  assign _013_ = _226_;
  assign _159_ = rw_bit;
  assign _006_ = _203_;
  assign _007_ = _205_;
  assign _177_ = shreg[5];
  assign _174_ = shreg[2];
  assign _175_ = shreg[3];
  assign _172_ = shreg[0];
  assign _173_ = shreg[1];
  assign _286_ = _042_;
  assign _176_ = shreg[4];
  assign _194_ = txreg[6];
  assign _178_ = shreg[6];
  assign _292_ = _048_;
  assign _293_ = _049_;
  assign _294_ = _050_;
  assign _166_ = rx_data_r[6];
  assign _295_ = _051_;
  assign _165_ = rx_data_r[5];
  assign _296_ = _052_;
  assign _164_ = rx_data_r[4];
  assign _297_ = _053_;
  assign _163_ = rx_data_r[3];
  assign _298_ = _054_;
  assign _162_ = rx_data_r[2];
  assign _299_ = _055_;
  assign _161_ = rx_data_r[1];
  assign _300_ = _056_;
  assign _160_ = rx_data_r[0];
  assign _301_ = _057_;
  assign _186_ = tx_data[6];
  assign _302_ = _058_;
  assign _185_ = tx_data[5];
  assign _303_ = _059_;
  assign _192_ = txreg[4];
  assign _184_ = tx_data[4];
  assign _304_ = _060_;
  assign _183_ = tx_data[3];
  assign _305_ = _061_;
  assign _182_ = tx_data[2];
  assign _306_ = _062_;
  assign _181_ = tx_data[1];
  assign _307_ = _063_;
  assign _180_ = tx_data[0];
  assign _308_ = _064_;
  assign _309_ = _065_;
  assign _310_ = _066_;
  assign _287_ = _043_;
  assign _288_ = _044_;
  assign _311_ = _067_;
  assign _312_ = _068_;
  assign _187_ = tx_data[7];
  assign _313_ = _069_;
  assign _289_ = _045_;
  assign _167_ = rx_data_r[7];
  assign _314_ = _070_;
  assign _290_ = _046_;
  assign _002_ = _003_;
  assign _291_ = _047_;
  assign _077_ = busy;
  assign _158_ = rst_n;
  assign start_pulse = RSTB2;
  assign _315_ = _071_;
  assign busy_clr = _078_;
  assign _169_ = scl;
  assign _170_ = sda_d;
  assign _316_ = _072_;

  BUF_X1 u_buf_scl_row0 (
    .A(scl),
    .Y(scl_row0),
    .VDD(VDD),
    .GND(GND)
  );

  BUF_X1 u_buf_scl_row1 (
    .A(scl),
    .Y(scl_row1),
    .VDD(VDD),
    .GND(GND)
  );

  BUF_X1 u_buf_scl_row2 (
    .A(scl),
    .Y(scl_row2),
    .VDD(VDD),
    .GND(GND)
  );

  BUF_X1 u_buf_scl_row3 (
    .A(scl),
    .Y(scl_row3),
    .VDD(VDD),
    .GND(GND)
  );

  BUF_X1 u_buf_scl_n_row1 (
    .A(scl_n),
    .Y(scl_n_row1),
    .VDD(VDD),
    .GND(GND)
  );

  BUF_X1 u_buf_scl_n_row2 (
    .A(scl_n),
    .Y(scl_n_row2),
    .VDD(VDD),
    .GND(GND)
  );

endmodule
