/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, Clang /workspace/YoWASP/yosys/wasi-sdk-33.0-x86_64-linux/share/cmake/../..//bin/clang++ 22.1.0) */

(* top =  1  *)
(* src = "src/i2c_slave_async.v:107.1-284.10" *)
module i2c_slave_async(VDD, GND, rst_n, scl, sda_in, sda_oe, tx_data, rx_data, rx_valid, addr_match, rw, busy);
  (* src = "src/i2c_slave_async.v:110.23-110.26" *)
  input VDD;
  wire VDD;
  (* src = "src/i2c_slave_async.v:110.28-110.31" *)
  input GND;
  wire GND;
  (* src = "src/i2c_slave_async.v:111.23-111.28" *)
  input rst_n;
  wire rst_n;
  (* src = "src/i2c_slave_async.v:112.23-112.26" *)
  input scl;
  wire scl;
  (* src = "src/i2c_slave_async.v:113.23-113.29" *)
  input sda_in;
  wire sda_in;
  (* src = "src/i2c_slave_async.v:114.23-114.29" *)
  output sda_oe;
  wire sda_oe;
  (* src = "src/i2c_slave_async.v:118.23-118.30" *)
  input [7:0] tx_data;
  wire [7:0] tx_data;
  (* src = "src/i2c_slave_async.v:119.23-119.30" *)
  output [7:0] rx_data;
  wire [7:0] rx_data;
  (* src = "src/i2c_slave_async.v:120.23-120.31" *)
  output rx_valid;
  wire rx_valid;
  (* src = "src/i2c_slave_async.v:121.23-121.33" *)
  output addr_match;
  wire addr_match;
  (* src = "src/i2c_slave_async.v:122.23-122.25" *)
  output rw;
  wire rw;
  (* src = "src/i2c_slave_async.v:123.23-123.27" *)
  output busy;
  wire busy;
  (* src = "src/i2c_slave_async.v:175.5-229.8" *)
  wire _000_;
  (* src = "src/i2c_slave_async.v:258.5-277.8" *)
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  (* force_downto = 32'd1 *)
  (* src = "src/i2c_slave_async.v:271.43-271.56|/share/techmap.v:135.22-135.23" *)
  wire [31:0] _147_;
  (* src = "src/i2c_slave_async.v:169.15-169.22" *)
  wire addr_ok;
  (* src = "src/i2c_slave_async.v:166.15-166.22" *)
  wire [2:0] bit_cnt;
  (* src = "src/i2c_slave_async.v:143.10-143.18" *)
  wire busy_clr;
  (* src = "src/i2c_slave_async.v:173.16-173.27" *)
  wire is_last_bit;
  (* src = "src/i2c_slave_async.v:167.15-167.31" *)
  wire last_bit_pending;
  (* src = "src/i2c_slave_async.v:151.15-151.20" *)
  wire [2:0] phase;
  (* src = "src/i2c_slave_async.v:144.10-144.12" *)
  wire qn;
  (* src = "src/i2c_slave_async.v:169.24-169.30" *)
  wire rw_bit;
  (* src = "src/i2c_slave_async.v:170.15-170.24" *)
  wire [7:0] rx_data_r;
  (* src = "src/i2c_slave_async.v:237.10-237.15" *)
  wire scl_n;
  (* src = "src/i2c_slave_async.v:136.10-136.15" *)
  wire sda_d;
  (* src = "src/i2c_slave_async.v:242.9-242.17" *)
  wire sda_oe_r;
  (* src = "src/i2c_slave_async.v:168.15-168.20" *)
  (* unused_bits = "7" *)
  wire [7:0] shreg;
  (* src = "src/i2c_slave_async.v:172.16-172.26" *)
  wire [7:0] shreg_next;
  (* src = "src/i2c_slave_async.v:139.10-139.21" *)
  wire start_pulse;
  (* src = "src/i2c_slave_async.v:243.15-243.20" *)
  wire [7:0] txreg;
  wire scl_row0;
  wire scl_row1;
  wire scl_row2;
  wire scl_row3;
  wire scl_n_row1;
  wire scl_n_row2;
  wire scl_buf;
  wire sda_in_buf;
  wire sda_in_row0;
  wire sda_in_row3;
  INV_X1 _148_ (
    .A(bit_cnt[0]),
    .Y(_065_)
  );
  INV_X1 _149_ (
    .A(addr_ok),
    .Y(_066_)
  );
  INV_X1 _150_ (
    .A(rst_n),
    .Y(_067_)
  );
  INV_X1 _151_ (
    .A(sda_d),
    .Y(_068_)
  );
  NAND2 _152_ (
    .A(scl_row2),
    .B(sda_d),
    .Y(_069_)
  );
  NOR2 _153_ (
    .A(sda_in_row3),
    .B(_069_),
    .Y(start_pulse)
  );
  NOR2 _154_ (
    .A(_067_),
    .B(start_pulse),
    .Y(_008_)
  );
  AND2_X1 _155_ (
    .A(busy),
    .B(rst_n),
    .Y(_009_)
  );
  OR2 _156_ (
    .A(phase[2]),
    .B(_004_),
    .Y(_070_)
  );
  OR2 _157_ (
    .A(_005_),
    .B(_070_),
    .Y(_071_)
  );
  INV_X1 _158_ (
    .A(_071_),
    .Y(rx_valid)
  );
  NOR3 _159_ (
    .A(phase[2]),
    .B(phase[0]),
    .C(_004_),
    .Y(_072_)
  );
  NAND2 _160_ (
    .A(last_bit_pending),
    .B(_072_),
    .Y(_073_)
  );
  MUX2 _161_ (
    .A(shreg[5]),
    .B(rx_data_r[6]),
    .S(_073_),
    .Y(_041_)
  );
  MUX2 _162_ (
    .A(shreg[4]),
    .B(rx_data_r[5]),
    .S(_073_),
    .Y(_042_)
  );
  MUX2 _163_ (
    .A(shreg[3]),
    .B(rx_data_r[4]),
    .S(_073_),
    .Y(_043_)
  );
  MUX2 _164_ (
    .A(shreg[2]),
    .B(rx_data_r[3]),
    .S(_073_),
    .Y(_044_)
  );
  MUX2 _165_ (
    .A(shreg[1]),
    .B(rx_data_r[2]),
    .S(_073_),
    .Y(_045_)
  );
  MUX2 _166_ (
    .A(shreg[0]),
    .B(rx_data_r[1]),
    .S(_073_),
    .Y(_046_)
  );
  MUX2 _167_ (
    .A(sda_in_row3),
    .B(rx_data_r[0]),
    .S(_073_),
    .Y(_047_)
  );
  NOR2 _168_ (
    .A(bit_cnt[1]),
    .B(bit_cnt[0]),
    .Y(_074_)
  );
  NOR3 _169_ (
    .A(_007_),
    .B(phase[0]),
    .C(phase[1]),
    .Y(_075_)
  );
  OR3 _170_ (
    .A(_007_),
    .B(phase[0]),
    .C(phase[1]),
    .Y(_076_)
  );
  NOR2 _171_ (
    .A(bit_cnt[2]),
    .B(_076_),
    .Y(_077_)
  );
  NAND2 _172_ (
    .A(_074_),
    .B(_077_),
    .Y(_078_)
  );
  MUX2 _173_ (
    .A(tx_data[6]),
    .B(txreg[6]),
    .S(_078_),
    .Y(_048_)
  );
  MUX2 _174_ (
    .A(tx_data[5]),
    .B(txreg[5]),
    .S(_078_),
    .Y(_049_)
  );
  MUX2 _175_ (
    .A(tx_data[4]),
    .B(txreg[4]),
    .S(_078_),
    .Y(_050_)
  );
  MUX2 _176_ (
    .A(tx_data[3]),
    .B(txreg[3]),
    .S(_078_),
    .Y(_051_)
  );
  MUX2 _177_ (
    .A(tx_data[2]),
    .B(txreg[2]),
    .S(_078_),
    .Y(_052_)
  );
  MUX2 _178_ (
    .A(tx_data[1]),
    .B(txreg[1]),
    .S(_078_),
    .Y(_053_)
  );
  MUX2 _179_ (
    .A(tx_data[0]),
    .B(txreg[0]),
    .S(_078_),
    .Y(_054_)
  );
  NOR3 _180_ (
    .A(phase[2]),
    .B(phase[0]),
    .C(phase[1]),
    .Y(_079_)
  );
  NOR3 _181_ (
    .A(_072_),
    .B(_075_),
    .C(_079_),
    .Y(_080_)
  );
  NOR2 _182_ (
    .A(last_bit_pending),
    .B(_080_),
    .Y(_081_)
  );
  OR2 _183_ (
    .A(_005_),
    .B(phase[1]),
    .Y(_082_)
  );
  NOR3 _184_ (
    .A(_007_),
    .B(_005_),
    .C(phase[1]),
    .Y(_083_)
  );
  OR2 _185_ (
    .A(_007_),
    .B(_082_),
    .Y(_084_)
  );
  OR2 _186_ (
    .A(phase[2]),
    .B(_082_),
    .Y(_085_)
  );
  AND4_X1 _187_ (
    .A(_071_),
    .B(_080_),
    .C(_084_),
    .D(_085_),
    .Y(_086_)
  );
  NAND2 _188_ (
    .A(sda_in_row0),
    .B(_083_),
    .Y(_087_)
  );
  NOR2 _189_ (
    .A(_066_),
    .B(_006_),
    .Y(_088_)
  );
  NOR2 _190_ (
    .A(_085_),
    .B(_088_),
    .Y(_089_)
  );
  NAND2 _191_ (
    .A(_073_),
    .B(_087_),
    .Y(_090_)
  );
  OR4 _192_ (
    .A(rx_valid),
    .B(_086_),
    .C(_089_),
    .D(_090_),
    .Y(_091_)
  );
  MUX2 _193_ (
    .A(_091_),
    .B(phase[1]),
    .S(_081_),
    .Y(_055_)
  );
  NAND2 _194_ (
    .A(last_bit_pending),
    .B(_079_),
    .Y(_092_)
  );
  NAND2 _195_ (
    .A(last_bit_pending),
    .B(_075_),
    .Y(_093_)
  );
  NAND3 _196_ (
    .A(_073_),
    .B(_092_),
    .C(_093_),
    .Y(_056_)
  );
  NAND2 _197_ (
    .A(bit_cnt[1]),
    .B(_086_),
    .Y(_094_)
  );
  NOR3 _198_ (
    .A(phase[2]),
    .B(last_bit_pending),
    .C(_080_),
    .Y(_095_)
  );
  AND2_X1 _199_ (
    .A(last_bit_pending),
    .B(_076_),
    .Y(_096_)
  );
  NOR2 _200_ (
    .A(_080_),
    .B(_096_),
    .Y(_097_)
  );
  NAND2 _201_ (
    .A(bit_cnt[1]),
    .B(bit_cnt[0]),
    .Y(_098_)
  );
  XOR2 _202_ (
    .A(bit_cnt[1]),
    .B(bit_cnt[0]),
    .Y(_099_)
  );
  NAND2 _203_ (
    .A(_097_),
    .B(_099_),
    .Y(_100_)
  );
  NAND2 _204_ (
    .A(_094_),
    .B(_100_),
    .Y(_057_)
  );
  NAND2 _205_ (
    .A(bit_cnt[0]),
    .B(_086_),
    .Y(_101_)
  );
  NAND2 _206_ (
    .A(_147_[0]),
    .B(_097_),
    .Y(_102_)
  );
  NAND2 _207_ (
    .A(_101_),
    .B(_102_),
    .Y(_058_)
  );
  OR4 _208_ (
    .A(_003_),
    .B(_002_),
    .C(shreg[5]),
    .D(shreg[2]),
    .Y(_103_)
  );
  NOR4 _209_ (
    .A(shreg[3]),
    .B(shreg[0]),
    .C(shreg[1]),
    .D(_103_),
    .Y(_104_)
  );
  MUX2 _210_ (
    .A(_104_),
    .B(addr_ok),
    .S(_092_),
    .Y(_059_)
  );
  NAND2 _211_ (
    .A(bit_cnt[2]),
    .B(_086_),
    .Y(_105_)
  );
  XNOR2 _212_ (
    .A(bit_cnt[2]),
    .B(_098_),
    .Y(_106_)
  );
  NAND2 _213_ (
    .A(_097_),
    .B(_106_),
    .Y(_107_)
  );
  NAND2 _214_ (
    .A(_105_),
    .B(_107_),
    .Y(_060_)
  );
  MUX2 _215_ (
    .A(sda_in_row0),
    .B(rw_bit),
    .S(_092_),
    .Y(_061_)
  );
  NOR2 _216_ (
    .A(_066_),
    .B(rw_bit),
    .Y(_108_)
  );
  NOR2 _217_ (
    .A(_085_),
    .B(_108_),
    .Y(_109_)
  );
  NOR4 _218_ (
    .A(_083_),
    .B(_086_),
    .C(_097_),
    .D(_109_),
    .Y(_110_)
  );
  NOR2 _219_ (
    .A(_095_),
    .B(_110_),
    .Y(_062_)
  );
  MUX2 _220_ (
    .A(tx_data[7]),
    .B(txreg[7]),
    .S(_078_),
    .Y(_063_)
  );
  MUX2 _221_ (
    .A(shreg[6]),
    .B(rx_data_r[7]),
    .S(_073_),
    .Y(_064_)
  );
  MUX2 _222_ (
    .A(tx_data[7]),
    .B(txreg[5]),
    .S(bit_cnt[1]),
    .Y(_111_)
  );
  NAND2 _223_ (
    .A(_065_),
    .B(_111_),
    .Y(_112_)
  );
  MUX2 _224_ (
    .A(txreg[6]),
    .B(txreg[4]),
    .S(bit_cnt[1]),
    .Y(_113_)
  );
  NAND2 _225_ (
    .A(bit_cnt[0]),
    .B(_113_),
    .Y(_114_)
  );
  NAND3 _226_ (
    .A(_077_),
    .B(_112_),
    .C(_114_),
    .Y(_115_)
  );
  NAND2 _227_ (
    .A(bit_cnt[2]),
    .B(_075_),
    .Y(_116_)
  );
  MUX2 _228_ (
    .A(txreg[2]),
    .B(txreg[0]),
    .S(bit_cnt[1]),
    .Y(_117_)
  );
  MUX2 _229_ (
    .A(txreg[3]),
    .B(txreg[1]),
    .S(bit_cnt[1]),
    .Y(_118_)
  );
  MUX2 _230_ (
    .A(_117_),
    .B(_118_),
    .S(_065_),
    .Y(_119_)
  );
  NOR2 _231_ (
    .A(_116_),
    .B(_119_),
    .Y(_120_)
  );
  NOR2 _232_ (
    .A(_066_),
    .B(_085_),
    .Y(_121_)
  );
  NOR3 _233_ (
    .A(rx_valid),
    .B(_120_),
    .C(_121_),
    .Y(_122_)
  );
  NAND2 _234_ (
    .A(_115_),
    .B(_122_),
    .Y(_001_)
  );
  NOR3 _235_ (
    .A(bit_cnt[0]),
    .B(_147_[1]),
    .C(_147_[2]),
    .Y(_000_)
  );
  NAND3 _236_ (
    .A(sda_in_row3),
    .B(scl_row2),
    .C(_068_),
    .Y(_123_)
  );
  NAND2 _237_ (
    .A(rst_n),
    .B(_123_),
    .Y(busy_clr)
  );
  (* src = "src/i2c_slave_async.v:175.5-229.8" *)
  DFFRB _269_ (
    .CK(scl_row0),
    .D(_059_),
    .Q(addr_ok),
    .QB(_144_),
    .RSTB(_008_)
  );
  (* src = "src/i2c_slave_async.v:175.5-229.8" *)
  DFFRB _270_ (
    .CK(scl_row1),
    .D(_058_),
    .Q(bit_cnt[0]),
    .QB(_147_[0]),
    .RSTB(_008_)
  );
  (* src = "src/i2c_slave_async.v:175.5-229.8" *)
  DFFRB _271_ (
    .CK(scl_row1),
    .D(_057_),
    .Q(bit_cnt[1]),
    .QB(_147_[1]),
    .RSTB(_008_)
  );
  (* src = "src/i2c_slave_async.v:175.5-229.8" *)
  DFFRB _272_ (
    .CK(scl_row1),
    .D(_060_),
    .Q(bit_cnt[2]),
    .QB(_147_[2]),
    .RSTB(_008_)
  );
  (* src = "src/i2c_slave_async.v:175.5-229.8" *)
  DFFRB _273_ (
    .CK(scl_row0),
    .D(_061_),
    .Q(rw_bit),
    .QB(_006_),
    .RSTB(_008_)
  );
  (* src = "src/i2c_slave_async.v:175.5-229.8" *)
  DFFRB _274_ (
    .CK(scl_row0),
    .D(_056_),
    .Q(phase[0]),
    .QB(_005_),
    .RSTB(_008_)
  );
  (* src = "src/i2c_slave_async.v:175.5-229.8" *)
  DFFRB _275_ (
    .CK(scl_row0),
    .D(_055_),
    .Q(phase[1]),
    .QB(_004_),
    .RSTB(_008_)
  );
  (* src = "src/i2c_slave_async.v:175.5-229.8" *)
  DFFRB _276_ (
    .CK(scl_row0),
    .D(_062_),
    .Q(phase[2]),
    .QB(_007_),
    .RSTB(_008_)
  );
  (* src = "src/i2c_slave_async.v:258.5-277.8" *)
  DFFRB _277_ (
    .CK(scl_n_row2),
    .D(_054_),
    .Q(txreg[0]),
    .QB(_143_),
    .RSTB(_009_)
  );
  (* src = "src/i2c_slave_async.v:258.5-277.8" *)
  DFFRB _278_ (
    .CK(scl_n_row2),
    .D(_053_),
    .Q(txreg[1]),
    .QB(_142_),
    .RSTB(_009_)
  );
  (* src = "src/i2c_slave_async.v:258.5-277.8" *)
  DFFRB _279_ (
    .CK(scl_n_row2),
    .D(_052_),
    .Q(txreg[2]),
    .QB(_141_),
    .RSTB(_009_)
  );
  (* src = "src/i2c_slave_async.v:258.5-277.8" *)
  DFFRB _280_ (
    .CK(scl_n_row2),
    .D(_051_),
    .Q(txreg[3]),
    .QB(_140_),
    .RSTB(_009_)
  );
  (* src = "src/i2c_slave_async.v:258.5-277.8" *)
  DFFRB _281_ (
    .CK(scl_n_row2),
    .D(_050_),
    .Q(txreg[4]),
    .QB(_139_),
    .RSTB(_009_)
  );
  (* src = "src/i2c_slave_async.v:258.5-277.8" *)
  DFFRB _282_ (
    .CK(scl_n_row1),
    .D(_049_),
    .Q(txreg[5]),
    .QB(_138_),
    .RSTB(_009_)
  );
  (* src = "src/i2c_slave_async.v:258.5-277.8" *)
  DFFRB _283_ (
    .CK(scl_n_row2),
    .D(_048_),
    .Q(txreg[6]),
    .QB(_137_),
    .RSTB(_009_)
  );
  (* src = "src/i2c_slave_async.v:258.5-277.8" *)
  DFFRB _284_ (
    .CK(scl_n_row1),
    .D(_063_),
    .Q(txreg[7]),
    .QB(_145_),
    .RSTB(_009_)
  );
  (* src = "src/i2c_slave_async.v:175.5-229.8" *)
  DFFRB _285_ (
    .CK(scl_row2),
    .D(_047_),
    .Q(rx_data_r[0]),
    .QB(_136_),
    .RSTB(_008_)
  );
  (* src = "src/i2c_slave_async.v:175.5-229.8" *)
  DFFRB _286_ (
    .CK(scl_row3),
    .D(_046_),
    .Q(rx_data_r[1]),
    .QB(_135_),
    .RSTB(_008_)
  );
  (* src = "src/i2c_slave_async.v:175.5-229.8" *)
  DFFRB _287_ (
    .CK(scl_row3),
    .D(_045_),
    .Q(rx_data_r[2]),
    .QB(_134_),
    .RSTB(_008_)
  );
  (* src = "src/i2c_slave_async.v:175.5-229.8" *)
  DFFRB _288_ (
    .CK(scl_row3),
    .D(_044_),
    .Q(rx_data_r[3]),
    .QB(_133_),
    .RSTB(_008_)
  );
  (* src = "src/i2c_slave_async.v:175.5-229.8" *)
  DFFRB _289_ (
    .CK(scl_row3),
    .D(_043_),
    .Q(rx_data_r[4]),
    .QB(_132_),
    .RSTB(_008_)
  );
  (* src = "src/i2c_slave_async.v:175.5-229.8" *)
  DFFRB _290_ (
    .CK(scl_row3),
    .D(_042_),
    .Q(rx_data_r[5]),
    .QB(_131_),
    .RSTB(_008_)
  );
  (* src = "src/i2c_slave_async.v:175.5-229.8" *)
  DFFRB _291_ (
    .CK(scl_row3),
    .D(_041_),
    .Q(rx_data_r[6]),
    .QB(_130_),
    .RSTB(_008_)
  );
  (* src = "src/i2c_slave_async.v:175.5-229.8" *)
  DFFRB _292_ (
    .CK(scl_row3),
    .D(_064_),
    .Q(rx_data_r[7]),
    .QB(_125_),
    .RSTB(_008_)
  );
  (* src = "src/i2c_slave_async.v:258.5-277.8" *)
  DFFRB _293_ (
    .CK(scl_n_row1),
    .D(_001_),
    .Q(sda_oe_r),
    .QB(sda_oe),
    .RSTB(_009_)
  );
  (* src = "src/i2c_slave_async.v:175.5-229.8" *)
  DFFRB _294_ (
    .CK(scl_row1),
    .D(_000_),
    .Q(last_bit_pending),
    .QB(_124_),
    .RSTB(_008_)
  );
  (* src = "src/i2c_slave_async.v:175.5-229.8" *)
  DFFRB _295_ (
    .CK(scl_row2),
    .D(sda_in_row3),
    .Q(shreg[0]),
    .QB(_128_),
    .RSTB(_008_)
  );
  (* src = "src/i2c_slave_async.v:175.5-229.8" *)
  DFFRB _296_ (
    .CK(scl_row3),
    .D(shreg[0]),
    .Q(shreg[1]),
    .QB(_126_),
    .RSTB(_008_)
  );
  (* src = "src/i2c_slave_async.v:175.5-229.8" *)
  DFFRB _297_ (
    .CK(scl_row3),
    .D(shreg[1]),
    .Q(shreg[2]),
    .QB(_127_),
    .RSTB(_008_)
  );
  (* src = "src/i2c_slave_async.v:175.5-229.8" *)
  DFFRB _298_ (
    .CK(scl_row3),
    .D(shreg[2]),
    .Q(shreg[3]),
    .QB(_129_),
    .RSTB(_008_)
  );
  (* src = "src/i2c_slave_async.v:175.5-229.8" *)
  DFFRB _299_ (
    .CK(scl_row3),
    .D(shreg[3]),
    .Q(shreg[4]),
    .QB(_002_),
    .RSTB(_008_)
  );
  (* src = "src/i2c_slave_async.v:175.5-229.8" *)
  DFFRB _300_ (
    .CK(scl_row3),
    .D(shreg[4]),
    .Q(shreg[5]),
    .QB(_146_),
    .RSTB(_008_)
  );
  (* src = "src/i2c_slave_async.v:175.5-229.8" *)
  DFFRB _301_ (
    .CK(scl_row3),
    .D(shreg[5]),
    .Q(shreg[6]),
    .QB(_003_),
    .RSTB(_008_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/i2c_slave_async.v:137.10-137.65" *)
  DEL1 u_del_sda (
    .A(sda_in_row3),
    .GND(GND),
    .VDD(VDD),
    .Y(sda_d)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/i2c_slave_async.v:238.12-238.64" *)
  INV_X1 u_inv_scl (
    .A(scl_row2),
    .GND(GND),
    .VDD(VDD),
    .Y(scl_n)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/i2c_slave_async.v:145.10-145.78" *)
  NOR2 u_lat_q (
    .A(busy_clr),
    .B(qn),
    .GND(GND),
    .VDD(VDD),
    .Y(busy)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/i2c_slave_async.v:146.10-146.78" *)
  NOR2 u_lat_qn (
    .A(start_pulse),
    .B(busy),
    .GND(GND),
    .VDD(VDD),
    .Y(qn)
  );
  assign _147_[31:3] = 29'h00000000;
  assign is_last_bit = last_bit_pending;
  assign shreg_next = { shreg[6:0], sda_in_buf };
  assign rw = rw_bit;
  assign addr_match = addr_ok;
  assign rx_data = rx_data_r;

  BUF_X1 u_buf_scl_row0 (
    .A(scl_buf),
    .Y(scl_row0),
    .VDD(VDD),
    .GND(GND)
  );

  BUF_X1 u_buf_scl_row1 (
    .A(scl_buf),
    .Y(scl_row1),
    .VDD(VDD),
    .GND(GND)
  );

  BUF_X1 u_buf_scl_row2 (
    .A(scl_buf),
    .Y(scl_row2),
    .VDD(VDD),
    .GND(GND)
  );

  BUF_X1 u_buf_scl_row3 (
    .A(scl_buf),
    .Y(scl_row3),
    .VDD(VDD),
    .GND(GND)
  );

  BUF_X1 u_buf_scl_n_row1 (
    .A(scl_n),
    .Y(scl_n_row1),
    .VDD(VDD),
    .GND(GND)
  );

  BUF_X1 u_buf_scl_n_row2 (
    .A(scl_n),
    .Y(scl_n_row2),
    .VDD(VDD),
    .GND(GND)
  );


  BUFTH u_bufth_scl (
    .A(scl),
    .Y(scl_buf),
    .VDD(VDD),
    .GND(GND)
  );

  BUFTH u_bufth_sda_in (
    .A(sda_in),
    .Y(sda_in_buf),
    .VDD(VDD),
    .GND(GND)
  );


  BUF_X1 u_buf_sda_in_row0 (
    .A(sda_in_buf),
    .Y(sda_in_row0),
    .VDD(VDD),
    .GND(GND)
  );

  BUF_X1 u_buf_sda_in_row3 (
    .A(sda_in_buf),
    .Y(sda_in_row3),
    .VDD(VDD),
    .GND(GND)
  );

endmodule
