/* Generated by Yosys 0.68+post (git sha1 c12172fbae8af5e20f6fb52e3d4e92d56ed587b6, Release, AppleClang clang++ 21.0.0.21000101) */

(* top =  1  *)
(* src = "../src/i2c_slave_async.v:129.1-354.10" *)
module i2c_slave_async(VDD, GND, rst_n, scl, sda_in, sda_oe, tx_data, rx_data, rx_valid, addr_match, rw, busy);
  (* src = "../src/i2c_slave_async.v:132.23-132.26" *)
  input VDD;
  wire VDD;
  (* src = "../src/i2c_slave_async.v:132.28-132.31" *)
  input GND;
  wire GND;
  (* src = "../src/i2c_slave_async.v:133.23-133.28" *)
  input rst_n;
  wire rst_n;
  (* src = "../src/i2c_slave_async.v:134.23-134.26" *)
  input scl;
  wire scl;
  (* src = "../src/i2c_slave_async.v:135.23-135.29" *)
  input sda_in;
  wire sda_in;
  (* src = "../src/i2c_slave_async.v:136.23-136.29" *)
  output sda_oe;
  wire sda_oe;
  (* src = "../src/i2c_slave_async.v:140.23-140.30" *)
  input [7:0] tx_data;
  wire [7:0] tx_data;
  (* src = "../src/i2c_slave_async.v:141.23-141.30" *)
  output [7:0] rx_data;
  wire [7:0] rx_data;
  (* src = "../src/i2c_slave_async.v:142.23-142.31" *)
  output rx_valid;
  wire rx_valid;
  (* src = "../src/i2c_slave_async.v:143.23-143.33" *)
  output addr_match;
  wire addr_match;
  (* src = "../src/i2c_slave_async.v:144.23-144.25" *)
  output rw;
  wire rw;
  (* src = "../src/i2c_slave_async.v:145.23-145.27" *)
  output busy;
  wire busy;
  (* src = "../src/i2c_slave_async.v:245.5-299.8" *)
  wire [2:0] _000_;
  (* src = "../src/i2c_slave_async.v:245.5-299.8" *)
  wire _001_;
  (* src = "../src/i2c_slave_async.v:245.5-299.8" *)
  wire [2:0] _002_;
  (* src = "../src/i2c_slave_async.v:328.5-347.8" *)
  wire _003_;
  (* src = "../src/i2c_slave_async.v:245.5-299.8" *)
  wire _004_;
  (* src = "../src/i2c_slave_async.v:328.5-347.8" *)
  wire _005_;
  (* src = "../src/i2c_slave_async.v:239.15-239.22" *)
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  (* src = "../src/i2c_slave_async.v:236.15-236.22" *)
  wire _073_;
  (* src = "../src/i2c_slave_async.v:236.15-236.22" *)
  wire _074_;
  (* src = "../src/i2c_slave_async.v:236.15-236.22" *)
  wire _075_;
  (* src = "../src/i2c_slave_async.v:145.23-145.27" *)
  wire _076_;
  (* src = "../src/i2c_slave_async.v:165.10-165.18" *)
  wire _077_;
  (* src = "../src/i2c_slave_async.v:237.15-237.31" *)
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  (* src = "../src/i2c_slave_async.v:221.15-221.20" *)
  wire _138_;
  (* src = "../src/i2c_slave_async.v:221.15-221.20" *)
  wire _139_;
  (* src = "../src/i2c_slave_async.v:221.15-221.20" *)
  wire _140_;
  (* src = "../src/i2c_slave_async.v:133.23-133.28" *)
  wire _141_;
  (* src = "../src/i2c_slave_async.v:208.10-208.29" *)
  wire _142_;
  (* src = "../src/i2c_slave_async.v:205.10-205.28" *)
  wire _143_;
  (* src = "../src/i2c_slave_async.v:206.10-206.25" *)
  wire _144_;
  (* src = "../src/i2c_slave_async.v:239.24-239.30" *)
  wire _145_;
  (* src = "../src/i2c_slave_async.v:240.15-240.24" *)
  wire _146_;
  (* src = "../src/i2c_slave_async.v:240.15-240.24" *)
  wire _147_;
  (* src = "../src/i2c_slave_async.v:240.15-240.24" *)
  wire _148_;
  (* src = "../src/i2c_slave_async.v:240.15-240.24" *)
  wire _149_;
  (* src = "../src/i2c_slave_async.v:240.15-240.24" *)
  wire _150_;
  (* src = "../src/i2c_slave_async.v:240.15-240.24" *)
  wire _151_;
  (* src = "../src/i2c_slave_async.v:240.15-240.24" *)
  wire _152_;
  (* src = "../src/i2c_slave_async.v:240.15-240.24" *)
  wire _153_;
  (* src = "../src/i2c_slave_async.v:142.23-142.31" *)
  wire _154_;
  (* src = "../src/i2c_slave_async.v:134.23-134.26" *)
  wire _155_;
  (* src = "../src/i2c_slave_async.v:219.10-219.19" *)
  wire _156_;
  (* src = "../src/i2c_slave_async.v:158.10-158.15" *)
  wire _157_;
  (* src = "../src/i2c_slave_async.v:135.23-135.29" *)
  wire _158_;
  (* src = "../src/i2c_slave_async.v:312.9-312.17" *)
  wire _159_;
  (* src = "../src/i2c_slave_async.v:238.15-238.20" *)
  wire _160_;
  (* src = "../src/i2c_slave_async.v:238.15-238.20" *)
  wire _161_;
  (* src = "../src/i2c_slave_async.v:238.15-238.20" *)
  wire _162_;
  (* src = "../src/i2c_slave_async.v:238.15-238.20" *)
  wire _163_;
  (* src = "../src/i2c_slave_async.v:238.15-238.20" *)
  wire _164_;
  (* src = "../src/i2c_slave_async.v:238.15-238.20" *)
  wire _165_;
  (* src = "../src/i2c_slave_async.v:238.15-238.20" *)
  wire _166_;
  (* src = "../src/i2c_slave_async.v:161.10-161.21" *)
  wire _167_;
  (* src = "../src/i2c_slave_async.v:140.23-140.30" *)
  wire _168_;
  (* src = "../src/i2c_slave_async.v:140.23-140.30" *)
  wire _169_;
  (* src = "../src/i2c_slave_async.v:140.23-140.30" *)
  wire _170_;
  (* src = "../src/i2c_slave_async.v:140.23-140.30" *)
  wire _171_;
  (* src = "../src/i2c_slave_async.v:140.23-140.30" *)
  wire _172_;
  (* src = "../src/i2c_slave_async.v:140.23-140.30" *)
  wire _173_;
  (* src = "../src/i2c_slave_async.v:140.23-140.30" *)
  wire _174_;
  (* src = "../src/i2c_slave_async.v:140.23-140.30" *)
  wire _175_;
  (* src = "../src/i2c_slave_async.v:313.15-313.20" *)
  wire _176_;
  (* src = "../src/i2c_slave_async.v:313.15-313.20" *)
  wire _177_;
  (* src = "../src/i2c_slave_async.v:313.15-313.20" *)
  wire _178_;
  (* src = "../src/i2c_slave_async.v:313.15-313.20" *)
  wire _179_;
  (* src = "../src/i2c_slave_async.v:313.15-313.20" *)
  wire _180_;
  (* src = "../src/i2c_slave_async.v:313.15-313.20" *)
  wire _181_;
  (* src = "../src/i2c_slave_async.v:313.15-313.20" *)
  wire _182_;
  (* src = "../src/i2c_slave_async.v:313.15-313.20" *)
  wire _183_;
  (* src = "../src/i2c_slave_async.v:161.24-161.36" *)
  wire _184_;
  (* src = "../src/i2c_slave_async.v:162.24-162.36" *)
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire [1:0] _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire [2:0] _308_;
  wire [1:0] _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire [2:0] _326_;
  wire _327_;
  wire _328_;
  wire [2:0] _329_;
  wire _330_;
  wire _331_;
  wire [2:0] _332_;
  wire _333_;
  wire _334_;
  wire [2:0] _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  (* src = "../src/i2c_slave_async.v:267.37-267.66" *)
  wire _354_;
  (* src = "../src/i2c_slave_async.v:293.33-293.47" *)
  wire _355_;
  (* src = "../src/i2c_slave_async.v:337.25-337.40" *)
  wire _356_;
  (* src = "../src/i2c_slave_async.v:162.30-162.36" *)
  wire _357_;
  (* src = "../src/i2c_slave_async.v:165.34-165.40" *)
  wire _358_;
  (* src = "../src/i2c_slave_async.v:206.32-206.51" *)
  wire _359_;
  (* src = "../src/i2c_slave_async.v:206.56-206.60" *)
  wire _360_;
  (* src = "../src/i2c_slave_async.v:219.34-219.49" *)
  wire _361_;
  (* src = "../src/i2c_slave_async.v:310.41-310.46" *)
  wire _362_;
  (* src = "../src/i2c_slave_async.v:339.37-339.48" *)
  wire _363_;
  (* src = "../src/i2c_slave_async.v:341.37-341.56" *)
  wire _364_;
  wire [2:0] _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire [2:0] _371_;
  (* force_downto = 32'd1 *)
  (* src = "../src/i2c_slave_async.v:341.43-341.56|/opt/homebrew/bin/../share/yosys/techmap.v:135.22-135.23" *)
  wire [31:0] _372_;
  (* force_downto = 32'd1 *)
  (* src = "../src/i2c_slave_async.v:341.43-341.56|/opt/homebrew/bin/../share/yosys/techmap.v:137.23-137.24" *)
  wire [0:0] _373_;
  (* force_downto = 32'd1 *)
  (* src = "../src/i2c_slave_async.v:290.32-290.46|/opt/homebrew/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "2" *)
  wire [2:0] _374_;
  (* force_downto = 32'd1 *)
  (* src = "../src/i2c_slave_async.v:290.32-290.46|/opt/homebrew/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [2:0] _375_;
  (* src = "../src/i2c_slave_async.v:341.43-341.56|/opt/homebrew/bin/../share/yosys/techmap.v:157.2-184.5" *)
  (* unused_bits = "1 3 5 7" *)
  wire [23:0] _376_;
  (* src = "../src/i2c_slave_async.v:341.43-341.56|/opt/homebrew/bin/../share/yosys/techmap.v:157.2-184.5" *)
  (* unused_bits = "1 2 3 5 6 7" *)
  wire [23:0] _377_;
  (* src = "../src/i2c_slave_async.v:274.43-274.75" *)
  wire [2:0] _378_;
  (* src = "../src/i2c_slave_async.v:274.32-274.88" *)
  wire [2:0] _379_;
  (* src = "../src/i2c_slave_async.v:239.15-239.22" *)
  wire addr_ok;
  (* src = "../src/i2c_slave_async.v:236.15-236.22" *)
  wire [2:0] bit_cnt;
  (* src = "../src/i2c_slave_async.v:165.10-165.18" *)
  wire busy_clr;
  (* src = "../src/i2c_slave_async.v:243.16-243.27" *)
  wire is_last_bit;
  (* src = "../src/i2c_slave_async.v:237.15-237.31" *)
  wire last_bit_pending;
  (* src = "../src/i2c_slave_async.v:221.15-221.20" *)
  wire [2:0] phase;
  (* src = "../src/i2c_slave_async.v:166.10-166.12" *)
  wire qn;
  (* src = "../src/i2c_slave_async.v:218.10-218.24" *)
  wire rst_scl_domain;
  (* src = "../src/i2c_slave_async.v:208.10-208.29" *)
  wire rst_scl_domain_held;
  (* src = "../src/i2c_slave_async.v:205.10-205.28" *)
  wire rst_scl_domain_raw;
  (* src = "../src/i2c_slave_async.v:310.10-310.26" *)
  wire rst_sdaoe_domain;
  (* src = "../src/i2c_slave_async.v:206.10-206.25" *)
  wire rst_stretch_clr;
  (* src = "../src/i2c_slave_async.v:207.10-207.24" *)
  wire rst_stretch_qn;
  (* src = "../src/i2c_slave_async.v:239.24-239.30" *)
  wire rw_bit;
  (* src = "../src/i2c_slave_async.v:240.15-240.24" *)
  wire [7:0] rx_data_r;
  (* src = "../src/i2c_slave_async.v:219.10-219.19" *)
  wire scl_gated;
  (* src = "../src/i2c_slave_async.v:307.10-307.15" *)
  wire scl_n;
  (* src = "../src/i2c_slave_async.v:158.10-158.15" *)
  wire sda_d;
  (* src = "../src/i2c_slave_async.v:312.9-312.17" *)
  wire sda_oe_r;
  (* src = "../src/i2c_slave_async.v:238.15-238.20" *)
  (* unused_bits = "7" *)
  wire [7:0] shreg;
  (* src = "../src/i2c_slave_async.v:242.16-242.26" *)
  wire [7:0] shreg_next;
  (* src = "../src/i2c_slave_async.v:161.10-161.21" *)
  wire start_pulse;
  (* src = "../src/i2c_slave_async.v:162.10-162.20" *)
  wire stop_pulse;
  (* src = "../src/i2c_slave_async.v:313.15-313.20" *)
  wire [7:0] txreg;
  wire scl_row2;
  wire scl_n_row0;
  wire scl_n_row2;
  wire scl_buf;
  wire sda_in_buf;
  wire sda_in_row1;
  wire sda_in_row2;
  wire _156__row0;
  wire _156__row1;
  wire _156__row2;
  wire _156__row3;
  INV_X1 _380_ (
    .A(_073_),
    .Y(_079_)
  );
  INV_X1 _381_ (
    .A(_006_),
    .Y(_080_)
  );
  INV_X1 _382_ (
    .A(_141_),
    .Y(_081_)
  );
  INV_X1 _383_ (
    .A(_157_),
    .Y(_082_)
  );
  NAND2 _384_ (
    .A(scl_row2),
    .B(_157_),
    .Y(_083_)
  );
  NOR2 _385_ (
    .A(sda_in_row2),
    .B(_083_),
    .Y(_167_)
  );
  OR2 _386_ (
    .A(_081_),
    .B(_167_),
    .Y(_143_)
  );
  NOR2 _387_ (
    .A(_142_),
    .B(_143_),
    .Y(_016_)
  );
  AND2_X1 _388_ (
    .A(_076_),
    .B(_141_),
    .Y(_017_)
  );
  OR2 _389_ (
    .A(_140_),
    .B(_009_),
    .Y(_084_)
  );
  OR2 _390_ (
    .A(_010_),
    .B(_084_),
    .Y(_085_)
  );
  INV_X1 _391_ (
    .A(_085_),
    .Y(_154_)
  );
  NOR3 _392_ (
    .A(_140_),
    .B(_138_),
    .C(_009_),
    .Y(_086_)
  );
  NAND2 _393_ (
    .A(_078_),
    .B(_086_),
    .Y(_087_)
  );
  MUX2 _394_ (
    .A(_165_),
    .B(_152_),
    .S(_087_),
    .Y(_049_)
  );
  MUX2 _395_ (
    .A(_164_),
    .B(_151_),
    .S(_087_),
    .Y(_050_)
  );
  MUX2 _396_ (
    .A(_163_),
    .B(_150_),
    .S(_087_),
    .Y(_051_)
  );
  MUX2 _397_ (
    .A(_162_),
    .B(_149_),
    .S(_087_),
    .Y(_052_)
  );
  MUX2 _398_ (
    .A(_161_),
    .B(_148_),
    .S(_087_),
    .Y(_053_)
  );
  MUX2 _399_ (
    .A(_160_),
    .B(_147_),
    .S(_087_),
    .Y(_054_)
  );
  MUX2 _400_ (
    .A(sda_in_row2),
    .B(_146_),
    .S(_087_),
    .Y(_055_)
  );
  NOR2 _401_ (
    .A(_074_),
    .B(_073_),
    .Y(_088_)
  );
  NOR3 _402_ (
    .A(_015_),
    .B(_138_),
    .C(_139_),
    .Y(_089_)
  );
  OR3 _403_ (
    .A(_015_),
    .B(_138_),
    .C(_139_),
    .Y(_090_)
  );
  NOR2 _404_ (
    .A(_075_),
    .B(_090_),
    .Y(_091_)
  );
  NAND2 _405_ (
    .A(_088_),
    .B(_091_),
    .Y(_092_)
  );
  MUX2 _406_ (
    .A(_174_),
    .B(_182_),
    .S(_092_),
    .Y(_056_)
  );
  MUX2 _407_ (
    .A(_173_),
    .B(_181_),
    .S(_092_),
    .Y(_057_)
  );
  MUX2 _408_ (
    .A(_172_),
    .B(_180_),
    .S(_092_),
    .Y(_058_)
  );
  MUX2 _409_ (
    .A(_171_),
    .B(_179_),
    .S(_092_),
    .Y(_059_)
  );
  MUX2 _410_ (
    .A(_170_),
    .B(_178_),
    .S(_092_),
    .Y(_060_)
  );
  MUX2 _411_ (
    .A(_169_),
    .B(_177_),
    .S(_092_),
    .Y(_061_)
  );
  MUX2 _412_ (
    .A(_168_),
    .B(_176_),
    .S(_092_),
    .Y(_062_)
  );
  NOR3 _413_ (
    .A(_140_),
    .B(_138_),
    .C(_139_),
    .Y(_093_)
  );
  NOR3 _414_ (
    .A(_086_),
    .B(_089_),
    .C(_093_),
    .Y(_094_)
  );
  NOR2 _415_ (
    .A(_078_),
    .B(_094_),
    .Y(_095_)
  );
  OR2 _416_ (
    .A(_010_),
    .B(_139_),
    .Y(_096_)
  );
  NOR3 _417_ (
    .A(_015_),
    .B(_010_),
    .C(_139_),
    .Y(_097_)
  );
  OR2 _418_ (
    .A(_015_),
    .B(_096_),
    .Y(_098_)
  );
  OR2 _419_ (
    .A(_140_),
    .B(_096_),
    .Y(_099_)
  );
  AND4_X1 _420_ (
    .A(_085_),
    .B(_094_),
    .C(_098_),
    .D(_099_),
    .Y(_100_)
  );
  NAND2 _421_ (
    .A(sda_in_row1),
    .B(_097_),
    .Y(_101_)
  );
  NOR2 _422_ (
    .A(_080_),
    .B(_014_),
    .Y(_102_)
  );
  NOR2 _423_ (
    .A(_099_),
    .B(_102_),
    .Y(_103_)
  );
  NAND2 _424_ (
    .A(_087_),
    .B(_101_),
    .Y(_104_)
  );
  OR4 _425_ (
    .A(_154_),
    .B(_100_),
    .C(_103_),
    .D(_104_),
    .Y(_105_)
  );
  MUX2 _426_ (
    .A(_105_),
    .B(_139_),
    .S(_095_),
    .Y(_063_)
  );
  NAND2 _427_ (
    .A(_078_),
    .B(_093_),
    .Y(_106_)
  );
  NAND2 _428_ (
    .A(_078_),
    .B(_089_),
    .Y(_107_)
  );
  NAND3 _429_ (
    .A(_087_),
    .B(_106_),
    .C(_107_),
    .Y(_064_)
  );
  NAND2 _430_ (
    .A(_074_),
    .B(_100_),
    .Y(_108_)
  );
  NOR3 _431_ (
    .A(_140_),
    .B(_078_),
    .C(_094_),
    .Y(_109_)
  );
  AND2_X1 _432_ (
    .A(_078_),
    .B(_090_),
    .Y(_110_)
  );
  NOR2 _433_ (
    .A(_094_),
    .B(_110_),
    .Y(_111_)
  );
  NAND2 _434_ (
    .A(_074_),
    .B(_073_),
    .Y(_112_)
  );
  XOR2 _435_ (
    .A(_074_),
    .B(_073_),
    .Y(_113_)
  );
  NAND2 _436_ (
    .A(_111_),
    .B(_113_),
    .Y(_114_)
  );
  NAND2 _437_ (
    .A(_108_),
    .B(_114_),
    .Y(_065_)
  );
  NAND2 _438_ (
    .A(_073_),
    .B(_100_),
    .Y(_115_)
  );
  NAND2 _439_ (
    .A(_012_),
    .B(_111_),
    .Y(_116_)
  );
  NAND2 _440_ (
    .A(_115_),
    .B(_116_),
    .Y(_066_)
  );
  OR4 _441_ (
    .A(_008_),
    .B(_007_),
    .C(_165_),
    .D(_162_),
    .Y(_117_)
  );
  NOR4 _442_ (
    .A(_163_),
    .B(_160_),
    .C(_161_),
    .D(_117_),
    .Y(_118_)
  );
  MUX2 _443_ (
    .A(_118_),
    .B(_006_),
    .S(_106_),
    .Y(_067_)
  );
  NAND2 _444_ (
    .A(_075_),
    .B(_100_),
    .Y(_119_)
  );
  XNOR2 _445_ (
    .A(_075_),
    .B(_112_),
    .Y(_120_)
  );
  NAND2 _446_ (
    .A(_111_),
    .B(_120_),
    .Y(_121_)
  );
  NAND2 _447_ (
    .A(_119_),
    .B(_121_),
    .Y(_068_)
  );
  MUX2 _448_ (
    .A(sda_in_row1),
    .B(_145_),
    .S(_106_),
    .Y(_069_)
  );
  NOR2 _449_ (
    .A(_080_),
    .B(_145_),
    .Y(_122_)
  );
  NOR2 _450_ (
    .A(_099_),
    .B(_122_),
    .Y(_123_)
  );
  NOR4 _451_ (
    .A(_097_),
    .B(_100_),
    .C(_111_),
    .D(_123_),
    .Y(_124_)
  );
  NOR2 _452_ (
    .A(_109_),
    .B(_124_),
    .Y(_070_)
  );
  MUX2 _453_ (
    .A(_175_),
    .B(_183_),
    .S(_092_),
    .Y(_071_)
  );
  MUX2 _454_ (
    .A(_166_),
    .B(_153_),
    .S(_087_),
    .Y(_072_)
  );
  MUX2 _455_ (
    .A(_175_),
    .B(_181_),
    .S(_074_),
    .Y(_125_)
  );
  NAND2 _456_ (
    .A(_079_),
    .B(_125_),
    .Y(_126_)
  );
  MUX2 _457_ (
    .A(_182_),
    .B(_180_),
    .S(_074_),
    .Y(_127_)
  );
  NAND2 _458_ (
    .A(_073_),
    .B(_127_),
    .Y(_128_)
  );
  NAND3 _459_ (
    .A(_091_),
    .B(_126_),
    .C(_128_),
    .Y(_129_)
  );
  NAND2 _460_ (
    .A(_075_),
    .B(_089_),
    .Y(_130_)
  );
  MUX2 _461_ (
    .A(_178_),
    .B(_176_),
    .S(_074_),
    .Y(_131_)
  );
  MUX2 _462_ (
    .A(_179_),
    .B(_177_),
    .S(_074_),
    .Y(_132_)
  );
  MUX2 _463_ (
    .A(_131_),
    .B(_132_),
    .S(_079_),
    .Y(_133_)
  );
  NOR2 _464_ (
    .A(_130_),
    .B(_133_),
    .Y(_134_)
  );
  NOR2 _465_ (
    .A(_080_),
    .B(_099_),
    .Y(_135_)
  );
  NOR3 _466_ (
    .A(_154_),
    .B(_134_),
    .C(_135_),
    .Y(_136_)
  );
  NAND2 _467_ (
    .A(_129_),
    .B(_136_),
    .Y(_005_)
  );
  NOR3 _468_ (
    .A(_073_),
    .B(_011_),
    .C(_013_),
    .Y(_004_)
  );
  AND2_X1 _469_ (
    .A(scl_row2),
    .B(_016_),
    .Y(_156_)
  );
  NOR2 _470_ (
    .A(_081_),
    .B(scl_row2),
    .Y(_144_)
  );
  NAND3 _471_ (
    .A(sda_in_row2),
    .B(scl_row2),
    .C(_082_),
    .Y(_137_)
  );
  NAND2 _472_ (
    .A(_141_),
    .B(_137_),
    .Y(_077_)
  );
  // MANUAL FIX 2026-09-02: _505_/_506_/_507_/_529_ (bit_cnt[0:2],
  // last_bit_pending) moved from _156__row0 to _156__row1 -- the FM
  // partition insert_row_buffers.py used to re-distribute scl_gated's
  // fanout has no awareness of same-cycle combinational dependencies
  // between flops (same class of issue as design_notes.md section 106),
  // and split this exact 9-signal write-address critical group (bit_cnt/
  // last_bit_pending/phase/addr_ok/rw_bit) across two different row
  // buffers again. Unified onto _156__row1 (where addr_ok/rw_bit/phase
  // already landed) to remove any inter-buffer skew risk between them.
  // Netlist-only fix -- see design_notes.md for the full diagnosis.
  (* src = "../src/i2c_slave_async.v:245.5-299.8" *)
  DFFRB _504_ (
    .CK(_156__row1),
    .D(_298_),
    .Q(addr_ok),
    .QB(_213_),
    .RSTB(_252_)
  );
  (* src = "../src/i2c_slave_async.v:245.5-299.8" *)
  DFFRB _505_ (
    .CK(_156__row1),
    .D(_297_),
    .Q(bit_cnt[0]),
    .QB(_212_),
    .RSTB(_253_)
  );
  (* src = "../src/i2c_slave_async.v:245.5-299.8" *)
  DFFRB _506_ (
    .CK(_156__row1),
    .D(_296_),
    .Q(bit_cnt[1]),
    .QB(_211_),
    .RSTB(_254_)
  );
  (* src = "../src/i2c_slave_async.v:245.5-299.8" *)
  DFFRB _507_ (
    .CK(_156__row1),
    .D(_299_),
    .Q(bit_cnt[2]),
    .QB(_214_),
    .RSTB(_251_)
  );
  (* src = "../src/i2c_slave_async.v:245.5-299.8" *)
  DFFRB _508_ (
    .CK(_156__row1),
    .D(_300_),
    .Q(rw_bit),
    .QB(_215_),
    .RSTB(_250_)
  );
  (* src = "../src/i2c_slave_async.v:245.5-299.8" *)
  DFFRB _509_ (
    .CK(_156__row1),
    .D(_295_),
    .Q(phase[0]),
    .QB(_210_),
    .RSTB(_255_)
  );
  (* src = "../src/i2c_slave_async.v:245.5-299.8" *)
  DFFRB _510_ (
    .CK(_156__row1),
    .D(_294_),
    .Q(phase[1]),
    .QB(_209_),
    .RSTB(_256_)
  );
  (* src = "../src/i2c_slave_async.v:245.5-299.8" *)
  DFFRB _511_ (
    .CK(_156__row1),
    .D(_301_),
    .Q(phase[2]),
    .QB(_216_),
    .RSTB(_249_)
  );
  (* src = "../src/i2c_slave_async.v:328.5-347.8" *)
  DFFRB _512_ (
    .CK(scl_n_row0),
    .D(_293_),
    .Q(txreg[0]),
    .QB(_208_),
    .RSTB(_257_)
  );
  (* src = "../src/i2c_slave_async.v:328.5-347.8" *)
  DFFRB _513_ (
    .CK(scl_n_row0),
    .D(_292_),
    .Q(txreg[1]),
    .QB(_207_),
    .RSTB(_258_)
  );
  (* src = "../src/i2c_slave_async.v:328.5-347.8" *)
  DFFRB _514_ (
    .CK(scl_n_row0),
    .D(_291_),
    .Q(txreg[2]),
    .QB(_206_),
    .RSTB(_259_)
  );
  (* src = "../src/i2c_slave_async.v:328.5-347.8" *)
  DFFRB _515_ (
    .CK(scl_n_row2),
    .D(_290_),
    .Q(txreg[3]),
    .QB(_205_),
    .RSTB(_260_)
  );
  (* src = "../src/i2c_slave_async.v:328.5-347.8" *)
  DFFRB _516_ (
    .CK(scl_n_row2),
    .D(_289_),
    .Q(txreg[4]),
    .QB(_204_),
    .RSTB(_261_)
  );
  (* src = "../src/i2c_slave_async.v:328.5-347.8" *)
  DFFRB _517_ (
    .CK(scl_n_row2),
    .D(_288_),
    .Q(txreg[5]),
    .QB(_203_),
    .RSTB(_262_)
  );
  (* src = "../src/i2c_slave_async.v:328.5-347.8" *)
  DFFRB _518_ (
    .CK(scl_n_row2),
    .D(_287_),
    .Q(txreg[6]),
    .QB(_202_),
    .RSTB(_263_)
  );
  (* src = "../src/i2c_slave_async.v:328.5-347.8" *)
  DFFRB _519_ (
    .CK(scl_n_row2),
    .D(_302_),
    .Q(txreg[7]),
    .QB(_217_),
    .RSTB(_248_)
  );
  (* src = "../src/i2c_slave_async.v:245.5-299.8" *)
  DFFRB _520_ (
    .CK(_156__row2),
    .D(_286_),
    .Q(rx_data_r[0]),
    .QB(_201_),
    .RSTB(_264_)
  );
  (* src = "../src/i2c_slave_async.v:245.5-299.8" *)
  DFFRB _521_ (
    .CK(_156__row3),
    .D(_285_),
    .Q(rx_data_r[1]),
    .QB(_200_),
    .RSTB(_265_)
  );
  (* src = "../src/i2c_slave_async.v:245.5-299.8" *)
  DFFRB _522_ (
    .CK(_156__row3),
    .D(_284_),
    .Q(rx_data_r[2]),
    .QB(_199_),
    .RSTB(_266_)
  );
  (* src = "../src/i2c_slave_async.v:245.5-299.8" *)
  DFFRB _523_ (
    .CK(_156__row3),
    .D(_283_),
    .Q(rx_data_r[3]),
    .QB(_198_),
    .RSTB(_267_)
  );
  (* src = "../src/i2c_slave_async.v:245.5-299.8" *)
  DFFRB _524_ (
    .CK(_156__row3),
    .D(_282_),
    .Q(rx_data_r[4]),
    .QB(_197_),
    .RSTB(_268_)
  );
  (* src = "../src/i2c_slave_async.v:245.5-299.8" *)
  DFFRB _525_ (
    .CK(_156__row3),
    .D(_281_),
    .Q(rx_data_r[5]),
    .QB(_196_),
    .RSTB(_269_)
  );
  (* src = "../src/i2c_slave_async.v:245.5-299.8" *)
  DFFRB _526_ (
    .CK(_156__row3),
    .D(_280_),
    .Q(rx_data_r[6]),
    .QB(_195_),
    .RSTB(_270_)
  );
  (* src = "../src/i2c_slave_async.v:245.5-299.8" *)
  DFFRB _527_ (
    .CK(_156__row3),
    .D(_303_),
    .Q(rx_data_r[7]),
    .QB(_188_),
    .RSTB(_277_)
  );
  (* src = "../src/i2c_slave_async.v:328.5-347.8" *)
  DFFRB _528_ (
    .CK(scl_n_row0),
    .D(_003_),
    .Q(sda_oe_r),
    .QB(_187_),
    .RSTB(_278_)
  );
  (* src = "../src/i2c_slave_async.v:245.5-299.8" *)
  DFFRB _529_ (
    .CK(_156__row1),
    .D(_001_),
    .Q(last_bit_pending),
    .QB(_186_),
    .RSTB(_279_)
  );
  (* src = "../src/i2c_slave_async.v:245.5-299.8" *)
  DFFRB _530_ (
    .CK(_156__row3),
    .D(sda_in_row2),
    .Q(shreg[0]),
    .QB(_192_),
    .RSTB(_273_)
  );
  (* src = "../src/i2c_slave_async.v:245.5-299.8" *)
  DFFRB _531_ (
    .CK(_156__row3),
    .D(shreg[0]),
    .Q(shreg[1]),
    .QB(_189_),
    .RSTB(_276_)
  );
  (* src = "../src/i2c_slave_async.v:245.5-299.8" *)
  DFFRB _532_ (
    .CK(_156__row3),
    .D(shreg[1]),
    .Q(shreg[2]),
    .QB(_190_),
    .RSTB(_275_)
  );
  (* src = "../src/i2c_slave_async.v:245.5-299.8" *)
  DFFRB _533_ (
    .CK(_156__row3),
    .D(shreg[2]),
    .Q(shreg[3]),
    .QB(_193_),
    .RSTB(_272_)
  );
  (* src = "../src/i2c_slave_async.v:245.5-299.8" *)
  DFFRB _534_ (
    .CK(_156__row3),
    .D(shreg[3]),
    .Q(shreg[4]),
    .QB(_191_),
    .RSTB(_274_)
  );
  (* src = "../src/i2c_slave_async.v:245.5-299.8" *)
  DFFRB _535_ (
    .CK(_156__row3),
    .D(shreg[4]),
    .Q(shreg[5]),
    .QB(_218_),
    .RSTB(_247_)
  );
  (* src = "../src/i2c_slave_async.v:245.5-299.8" *)
  DFFRB _536_ (
    .CK(_156__row3),
    .D(shreg[5]),
    .Q(shreg[6]),
    .QB(_194_),
    .RSTB(_271_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../src/i2c_slave_async.v:159.10-159.65" *)
  DEL1 u_del_sda (
    .A(sda_in_row2),
    .GND(GND),
    .VDD(VDD),
    .Y(sda_d)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../src/i2c_slave_async.v:308.12-308.64" *)
  INV_X1 u_inv_scl (
    .A(scl_row2),
    .GND(GND),
    .VDD(VDD),
    .Y(scl_n)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../src/i2c_slave_async.v:167.10-167.78" *)
  NOR2 u_lat_q (
    .A(busy_clr),
    .B(qn),
    .GND(GND),
    .VDD(VDD),
    .Y(busy)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../src/i2c_slave_async.v:168.10-168.78" *)
  NOR2 u_lat_qn (
    .A(start_pulse),
    .B(busy),
    .GND(GND),
    .VDD(VDD),
    .Y(qn)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../src/i2c_slave_async.v:209.10-209.123" *)
  NOR2 u_rst_stretch_q (
    .A(rst_stretch_clr),
    .B(rst_stretch_qn),
    .GND(GND),
    .VDD(VDD),
    .Y(rst_scl_domain_held)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../src/i2c_slave_async.v:210.10-210.123" *)
  NOR2 u_rst_stretch_qn (
    .A(rst_scl_domain_raw),
    .B(rst_scl_domain_held),
    .GND(GND),
    .VDD(VDD),
    .Y(rst_stretch_qn)
  );
  assign _375_[0] = _372_[0];
  assign _372_[31:3] = 29'h00000000;
  assign _377_[23:8] = 16'hxxxx;
  assign _374_[0] = bit_cnt[0];
  assign _376_[23:8] = 16'hxxxx;
  assign _304_[1] = _238_;
  assign _379_[0] = 1'h0;
  assign { _378_[2], _378_[0] } = { rw_bit, 1'h0 };
  assign _365_[2] = _365_[0];
  assign is_last_bit = last_bit_pending;
  assign shreg_next = { shreg[6:0], sda_in_buf };
  assign rw = rw_bit;
  assign addr_match = addr_ok;
  assign rx_data = rx_data_r;
  assign sda_oe = _187_;
  assign _242_ = _191_;
  assign _243_ = _194_;
  assign _240_ = _209_;
  assign _239_ = _210_;
  assign _372_[1] = _211_;
  assign _372_[0] = _212_;
  assign _372_[2] = _214_;
  assign _378_[1] = _215_;
  assign _241_ = _216_;
  assign _247_ = _016_;
  assign _248_ = _017_;
  assign _249_ = _016_;
  assign _250_ = _016_;
  assign _251_ = _016_;
  assign _252_ = _016_;
  assign _253_ = _016_;
  assign _254_ = _016_;
  assign _255_ = _016_;
  assign _256_ = _016_;
  assign _257_ = _017_;
  assign _258_ = _017_;
  assign _259_ = _017_;
  assign _260_ = _017_;
  assign _261_ = _017_;
  assign _262_ = _017_;
  assign _263_ = _017_;
  assign _264_ = _016_;
  assign _265_ = _016_;
  assign _266_ = _016_;
  assign _267_ = _016_;
  assign _268_ = _016_;
  assign _269_ = _016_;
  assign _270_ = _016_;
  assign _271_ = _016_;
  assign _140_ = phase[2];
  assign _272_ = _016_;
  assign _074_ = bit_cnt[1];
  assign _073_ = bit_cnt[0];
  assign _179_ = txreg[3];
  assign _178_ = txreg[2];
  assign rx_valid = _154_;
  assign _273_ = _016_;
  assign _015_ = _216_;
  assign _078_ = last_bit_pending;
  assign _075_ = bit_cnt[2];
  assign _012_ = _212_;
  assign _181_ = txreg[5];
  assign _180_ = txreg[4];
  assign _006_ = addr_ok;
  assign _158_ = sda_in_buf;
  assign _274_ = _016_;
  assign _014_ = _215_;
  assign _177_ = txreg[1];
  assign _176_ = txreg[0];
  assign _145_ = rw_bit;
  assign _275_ = _016_;
  assign _008_ = _194_;
  assign _007_ = _191_;
  assign _165_ = shreg[5];
  assign _162_ = shreg[2];
  assign _163_ = shreg[3];
  assign _160_ = shreg[0];
  assign _161_ = shreg[1];
  assign _164_ = shreg[4];
  assign _138_ = phase[0];
  assign _276_ = _016_;
  assign _166_ = shreg[6];
  assign _011_ = _211_;
  assign _013_ = _214_;
  assign _010_ = _210_;
  assign _009_ = _209_;
  assign _152_ = rx_data_r[6];
  assign _280_ = _049_;
  assign _151_ = rx_data_r[5];
  assign _281_ = _050_;
  assign _150_ = rx_data_r[4];
  assign _282_ = _051_;
  assign _149_ = rx_data_r[3];
  assign _283_ = _052_;
  assign _148_ = rx_data_r[2];
  assign _284_ = _053_;
  assign _147_ = rx_data_r[1];
  assign _285_ = _054_;
  assign _146_ = rx_data_r[0];
  assign _286_ = _055_;
  assign _182_ = txreg[6];
  assign _174_ = tx_data[6];
  assign _287_ = _056_;
  assign _173_ = tx_data[5];
  assign _288_ = _057_;
  assign _172_ = tx_data[4];
  assign _289_ = _058_;
  assign _171_ = tx_data[3];
  assign _290_ = _059_;
  assign _170_ = tx_data[2];
  assign _291_ = _060_;
  assign _169_ = tx_data[1];
  assign _292_ = _061_;
  assign _168_ = tx_data[0];
  assign _293_ = _062_;
  assign _139_ = phase[1];
  assign _294_ = _063_;
  assign _295_ = _064_;
  assign _183_ = txreg[7];
  assign _296_ = _065_;
  assign _297_ = _066_;
  assign _298_ = _067_;
  assign _299_ = _068_;
  assign _300_ = _069_;
  assign _301_ = _070_;
  assign _175_ = tx_data[7];
  assign _302_ = _071_;
  assign _153_ = rx_data_r[7];
  assign _303_ = _072_;
  assign _277_ = _016_;
  assign _278_ = _017_;
  assign _003_ = _005_;
  assign _159_ = sda_oe_r;
  assign _279_ = _016_;
  assign _076_ = busy;
  assign _141_ = rst_n;
  assign _001_ = _004_;
  assign _155_ = scl_buf;
  assign scl_gated = _156_;
  assign rst_scl_domain_raw = _143_;
  assign _142_ = rst_scl_domain_held;
  assign rst_stretch_clr = _144_;
  assign start_pulse = _167_;
  assign busy_clr = _077_;
  assign _157_ = sda_d;

  BUF_X1 u_buf_scl_row2 (
    .A(scl_buf),
    .Y(scl_row2),
    .VDD(VDD),
    .GND(GND)
  );

  BUF_X1 u_buf_scl_n_row0 (
    .A(scl_n),
    .Y(scl_n_row0),
    .VDD(VDD),
    .GND(GND)
  );

  BUF_X1 u_buf_scl_n_row2 (
    .A(scl_n),
    .Y(scl_n_row2),
    .VDD(VDD),
    .GND(GND)
  );


  BUFTH u_bufth_scl (
    .A(scl),
    .Y(scl_buf),
    .VDD(VDD),
    .GND(GND)
  );

  BUFTH u_bufth_sda_in (
    .A(sda_in),
    .Y(sda_in_buf),
    .VDD(VDD),
    .GND(GND)
  );


  BUF_X1 u_buf_sda_in_row1 (
    .A(sda_in_buf),
    .Y(sda_in_row1),
    .VDD(VDD),
    .GND(GND)
  );

  BUF_X1 u_buf_sda_in_row2 (
    .A(sda_in_buf),
    .Y(sda_in_row2),
    .VDD(VDD),
    .GND(GND)
  );


  BUF_X1 u_buf__156__row0 (
    .A(_156_),
    .Y(_156__row0),
    .VDD(VDD),
    .GND(GND)
  );

  BUF_X1 u_buf__156__row1 (
    .A(_156_),
    .Y(_156__row1),
    .VDD(VDD),
    .GND(GND)
  );

  BUF_X1 u_buf__156__row2 (
    .A(_156_),
    .Y(_156__row2),
    .VDD(VDD),
    .GND(GND)
  );

  BUF_X1 u_buf__156__row3 (
    .A(_156_),
    .Y(_156__row3),
    .VDD(VDD),
    .GND(GND)
  );

endmodule
