/* Generated by Yosys 0.68+post (git sha1 c12172fbae8af5e20f6fb52e3d4e92d56ed587b6, Release, AppleClang clang++ 21.0.0.21000101) */

(* top =  1  *)
(* src = "src/i2c_slave_async.v:85.1-245.10" *)
module i2c_slave_async(VDD, GND, rst_n, scl, sda_in, sda_oe, tx_data, rx_data, rx_valid, addr_match, rw, busy);
  (* src = "src/i2c_slave_async.v:88.23-88.26" *)
  input VDD;
  wire VDD;
  (* src = "src/i2c_slave_async.v:88.28-88.31" *)
  input GND;
  wire GND;
  (* src = "src/i2c_slave_async.v:89.23-89.28" *)
  input rst_n;
  wire rst_n;
  (* src = "src/i2c_slave_async.v:90.23-90.26" *)
  input scl;
  wire scl;
  (* src = "src/i2c_slave_async.v:91.23-91.29" *)
  input sda_in;
  wire sda_in;
  (* src = "src/i2c_slave_async.v:92.23-92.29" *)
  output sda_oe;
  wire sda_oe;
  (* src = "src/i2c_slave_async.v:96.23-96.30" *)
  input [7:0] tx_data;
  wire [7:0] tx_data;
  (* src = "src/i2c_slave_async.v:97.23-97.30" *)
  output [7:0] rx_data;
  wire [7:0] rx_data;
  (* src = "src/i2c_slave_async.v:98.23-98.31" *)
  output rx_valid;
  wire rx_valid;
  (* src = "src/i2c_slave_async.v:99.23-99.33" *)
  output addr_match;
  wire addr_match;
  (* src = "src/i2c_slave_async.v:100.23-100.25" *)
  output rw;
  wire rw;
  (* src = "src/i2c_slave_async.v:101.23-101.27" *)
  output busy;
  wire busy;
  (* src = "src/i2c_slave_async.v:147.5-192.8" *)
  wire [7:0] _000_;
  (* src = "src/i2c_slave_async.v:147.5-192.8" *)
  wire [2:0] _001_;
  (* src = "src/i2c_slave_async.v:219.5-238.8" *)
  wire _002_;
  (* src = "src/i2c_slave_async.v:219.5-238.8" *)
  wire _003_;
  (* src = "src/i2c_slave_async.v:141.15-141.22" *)
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  (* src = "src/i2c_slave_async.v:139.15-139.23" *)
  wire _076_;
  (* src = "src/i2c_slave_async.v:139.15-139.23" *)
  wire _077_;
  (* src = "src/i2c_slave_async.v:139.15-139.23" *)
  wire _078_;
  (* src = "src/i2c_slave_async.v:139.15-139.23" *)
  wire _079_;
  (* src = "src/i2c_slave_async.v:139.15-139.23" *)
  wire _080_;
  (* src = "src/i2c_slave_async.v:139.15-139.23" *)
  wire _081_;
  (* src = "src/i2c_slave_async.v:139.15-139.23" *)
  wire _082_;
  (* src = "src/i2c_slave_async.v:139.15-139.23" *)
  wire _083_;
  (* src = "src/i2c_slave_async.v:101.23-101.27" *)
  wire _084_;
  (* src = "src/i2c_slave_async.v:121.10-121.18" *)
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  (* src = "src/i2c_slave_async.v:129.15-129.20" *)
  wire _149_;
  (* src = "src/i2c_slave_async.v:129.15-129.20" *)
  wire _150_;
  (* src = "src/i2c_slave_async.v:129.15-129.20" *)
  wire _151_;
  (* src = "src/i2c_slave_async.v:89.23-89.28" *)
  wire _152_;
  (* src = "src/i2c_slave_async.v:127.10-127.24" *)
  wire _153_;
  (* src = "src/i2c_slave_async.v:141.24-141.30" *)
  wire _154_;
  (* src = "src/i2c_slave_async.v:142.15-142.24" *)
  wire _155_;
  (* src = "src/i2c_slave_async.v:142.15-142.24" *)
  wire _156_;
  (* src = "src/i2c_slave_async.v:142.15-142.24" *)
  wire _157_;
  (* src = "src/i2c_slave_async.v:142.15-142.24" *)
  wire _158_;
  (* src = "src/i2c_slave_async.v:142.15-142.24" *)
  wire _159_;
  (* src = "src/i2c_slave_async.v:142.15-142.24" *)
  wire _160_;
  (* src = "src/i2c_slave_async.v:142.15-142.24" *)
  wire _161_;
  (* src = "src/i2c_slave_async.v:142.15-142.24" *)
  wire _162_;
  (* src = "src/i2c_slave_async.v:98.23-98.31" *)
  wire _163_;
  (* src = "src/i2c_slave_async.v:90.23-90.26" *)
  wire _164_;
  (* src = "src/i2c_slave_async.v:114.10-114.15" *)
  wire _165_;
  (* src = "src/i2c_slave_async.v:91.23-91.29" *)
  wire _166_;
  (* src = "src/i2c_slave_async.v:205.9-205.17" *)
  wire _167_;
  (* src = "src/i2c_slave_async.v:140.15-140.20" *)
  wire _168_;
  (* src = "src/i2c_slave_async.v:140.15-140.20" *)
  wire _169_;
  (* src = "src/i2c_slave_async.v:140.15-140.20" *)
  wire _170_;
  (* src = "src/i2c_slave_async.v:140.15-140.20" *)
  wire _171_;
  (* src = "src/i2c_slave_async.v:140.15-140.20" *)
  wire _172_;
  (* src = "src/i2c_slave_async.v:140.15-140.20" *)
  wire _173_;
  (* src = "src/i2c_slave_async.v:140.15-140.20" *)
  wire _174_;
  (* src = "src/i2c_slave_async.v:117.10-117.21" *)
  wire _175_;
  (* src = "src/i2c_slave_async.v:96.23-96.30" *)
  wire _176_;
  (* src = "src/i2c_slave_async.v:96.23-96.30" *)
  wire _177_;
  (* src = "src/i2c_slave_async.v:96.23-96.30" *)
  wire _178_;
  (* src = "src/i2c_slave_async.v:96.23-96.30" *)
  wire _179_;
  (* src = "src/i2c_slave_async.v:96.23-96.30" *)
  wire _180_;
  (* src = "src/i2c_slave_async.v:96.23-96.30" *)
  wire _181_;
  (* src = "src/i2c_slave_async.v:96.23-96.30" *)
  wire _182_;
  (* src = "src/i2c_slave_async.v:96.23-96.30" *)
  wire _183_;
  (* src = "src/i2c_slave_async.v:206.15-206.20" *)
  wire _184_;
  (* src = "src/i2c_slave_async.v:206.15-206.20" *)
  wire _185_;
  (* src = "src/i2c_slave_async.v:206.15-206.20" *)
  wire _186_;
  (* src = "src/i2c_slave_async.v:206.15-206.20" *)
  wire _187_;
  (* src = "src/i2c_slave_async.v:206.15-206.20" *)
  wire _188_;
  (* src = "src/i2c_slave_async.v:206.15-206.20" *)
  wire _189_;
  (* src = "src/i2c_slave_async.v:206.15-206.20" *)
  wire _190_;
  (* src = "src/i2c_slave_async.v:206.15-206.20" *)
  wire _191_;
  (* src = "src/i2c_slave_async.v:117.24-117.36" *)
  wire _192_;
  (* src = "src/i2c_slave_async.v:118.24-118.36" *)
  wire _193_;
  (* src = "src/i2c_slave_async.v:232.41-232.57" *)
  wire [7:0] _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire [1:0] _322_;
  wire _323_;
  wire _324_;
  wire [2:0] _325_;
  wire [1:0] _326_;
  wire [3:0] _327_;
  wire [1:0] _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire [2:0] _351_;
  wire _352_;
  wire _353_;
  wire [2:0] _354_;
  wire _355_;
  wire _356_;
  wire [2:0] _357_;
  wire _358_;
  wire _359_;
  wire [2:0] _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  (* src = "src/i2c_slave_async.v:160.38-160.67" *)
  wire _383_;
  (* src = "src/i2c_slave_async.v:186.34-186.48" *)
  wire _384_;
  (* src = "src/i2c_slave_async.v:118.30-118.36" *)
  wire _385_;
  (* src = "src/i2c_slave_async.v:121.34-121.40" *)
  wire _386_;
  (* src = "src/i2c_slave_async.v:203.41-203.46" *)
  wire _387_;
  (* src = "src/i2c_slave_async.v:230.37-230.48" *)
  wire _388_;
  (* src = "src/i2c_slave_async.v:232.37-232.59" *)
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire [7:0] _395_;
  wire [2:0] _396_;
  (* src = "src/i2c_slave_async.v:232.39-232.58" *)
  wire _397_;
  (* src = "src/i2c_slave_async.v:167.44-167.76" *)
  wire [2:0] _398_;
  (* src = "src/i2c_slave_async.v:167.33-167.89" *)
  wire [2:0] _399_;
  (* src = "src/i2c_slave_async.v:141.15-141.22" *)
  wire addr_ok;
  (* src = "src/i2c_slave_async.v:139.15-139.23" *)
  wire [7:0] bit_walk;
  (* src = "src/i2c_slave_async.v:121.10-121.18" *)
  wire busy_clr;
  (* src = "src/i2c_slave_async.v:145.16-145.27" *)
  wire is_last_bit;
  (* src = "src/i2c_slave_async.v:129.15-129.20" *)
  wire [2:0] phase;
  (* src = "src/i2c_slave_async.v:122.10-122.12" *)
  wire qn;
  (* src = "src/i2c_slave_async.v:127.10-127.24" *)
  wire rst_scl_domain;
  (* src = "src/i2c_slave_async.v:203.10-203.26" *)
  wire rst_sdaoe_domain;
  (* src = "src/i2c_slave_async.v:141.24-141.30" *)
  wire rw_bit;
  (* src = "src/i2c_slave_async.v:142.15-142.24" *)
  wire [7:0] rx_data_r;
  (* src = "src/i2c_slave_async.v:200.10-200.15" *)
  wire scl_n;
  (* src = "src/i2c_slave_async.v:114.10-114.15" *)
  wire sda_d;
  (* src = "src/i2c_slave_async.v:205.9-205.17" *)
  wire sda_oe_r;
  (* src = "src/i2c_slave_async.v:140.15-140.20" *)
  (* unused_bits = "7" *)
  wire [7:0] shreg;
  (* src = "src/i2c_slave_async.v:144.16-144.26" *)
  wire [7:0] shreg_next;
  (* src = "src/i2c_slave_async.v:117.10-117.21" *)
  wire start_pulse;
  (* src = "src/i2c_slave_async.v:118.10-118.20" *)
  wire stop_pulse;
  (* src = "src/i2c_slave_async.v:206.15-206.20" *)
  wire [7:0] txreg;
  INV_X1 _400_ (
    .A(_076_),
    .Y(_086_)
  );
  INV_X1 _401_ (
    .A(_166_),
    .Y(_087_)
  );
  INV_X1 _402_ (
    .A(_010_),
    .Y(_088_)
  );
  INV_X1 _403_ (
    .A(_154_),
    .Y(_089_)
  );
  INV_X1 _404_ (
    .A(_165_),
    .Y(_090_)
  );
  NAND3 _405_ (
    .A(_087_),
    .B(_164_),
    .C(_165_),
    .Y(_091_)
  );
  INV_X1 _406_ (
    .A(_091_),
    .Y(_175_)
  );
  AND2_X1 _407_ (
    .A(_152_),
    .B(_091_),
    .Y(_011_)
  );
  INV_X1 _408_ (
    .A(_011_),
    .Y(_153_)
  );
  AND2_X1 _409_ (
    .A(_084_),
    .B(_152_),
    .Y(_012_)
  );
  NOR3 _410_ (
    .A(_151_),
    .B(_008_),
    .C(_007_),
    .Y(_163_)
  );
  NOR3 _411_ (
    .A(_149_),
    .B(_151_),
    .C(_007_),
    .Y(_092_)
  );
  NAND2 _412_ (
    .A(_076_),
    .B(_092_),
    .Y(_093_)
  );
  MUX2 _413_ (
    .A(_173_),
    .B(_161_),
    .S(_093_),
    .Y(_047_)
  );
  MUX2 _414_ (
    .A(_172_),
    .B(_160_),
    .S(_093_),
    .Y(_048_)
  );
  MUX2 _415_ (
    .A(_171_),
    .B(_159_),
    .S(_093_),
    .Y(_049_)
  );
  MUX2 _416_ (
    .A(_170_),
    .B(_158_),
    .S(_093_),
    .Y(_050_)
  );
  MUX2 _417_ (
    .A(_169_),
    .B(_157_),
    .S(_093_),
    .Y(_051_)
  );
  MUX2 _418_ (
    .A(_168_),
    .B(_156_),
    .S(_093_),
    .Y(_052_)
  );
  MUX2 _419_ (
    .A(_166_),
    .B(_155_),
    .S(_093_),
    .Y(_053_)
  );
  NOR3 _420_ (
    .A(_009_),
    .B(_149_),
    .C(_150_),
    .Y(_094_)
  );
  NAND2 _421_ (
    .A(_083_),
    .B(_094_),
    .Y(_095_)
  );
  MUX2 _422_ (
    .A(_182_),
    .B(_190_),
    .S(_095_),
    .Y(_054_)
  );
  MUX2 _423_ (
    .A(_181_),
    .B(_189_),
    .S(_095_),
    .Y(_055_)
  );
  MUX2 _424_ (
    .A(_180_),
    .B(_188_),
    .S(_095_),
    .Y(_056_)
  );
  MUX2 _425_ (
    .A(_179_),
    .B(_187_),
    .S(_095_),
    .Y(_057_)
  );
  MUX2 _426_ (
    .A(_178_),
    .B(_186_),
    .S(_095_),
    .Y(_058_)
  );
  MUX2 _427_ (
    .A(_177_),
    .B(_185_),
    .S(_095_),
    .Y(_059_)
  );
  MUX2 _428_ (
    .A(_176_),
    .B(_184_),
    .S(_095_),
    .Y(_060_)
  );
  NOR3 _429_ (
    .A(_149_),
    .B(_151_),
    .C(_150_),
    .Y(_096_)
  );
  NOR3 _430_ (
    .A(_092_),
    .B(_094_),
    .C(_096_),
    .Y(_097_)
  );
  NOR2 _431_ (
    .A(_076_),
    .B(_097_),
    .Y(_098_)
  );
  NOR3 _432_ (
    .A(_151_),
    .B(_008_),
    .C(_150_),
    .Y(_099_)
  );
  NOR3 _433_ (
    .A(_009_),
    .B(_008_),
    .C(_150_),
    .Y(_100_)
  );
  NOR3 _434_ (
    .A(_163_),
    .B(_099_),
    .C(_100_),
    .Y(_101_)
  );
  AND2_X1 _435_ (
    .A(_097_),
    .B(_101_),
    .Y(_102_)
  );
  NAND2 _436_ (
    .A(_097_),
    .B(_101_),
    .Y(_103_)
  );
  NAND2 _437_ (
    .A(_004_),
    .B(_088_),
    .Y(_104_)
  );
  NAND2 _438_ (
    .A(_099_),
    .B(_104_),
    .Y(_105_)
  );
  AND2_X1 _439_ (
    .A(_166_),
    .B(_100_),
    .Y(_106_)
  );
  NOR2 _440_ (
    .A(_163_),
    .B(_106_),
    .Y(_107_)
  );
  NAND4 _441_ (
    .A(_093_),
    .B(_103_),
    .C(_105_),
    .D(_107_),
    .Y(_108_)
  );
  MUX2 _442_ (
    .A(_108_),
    .B(_150_),
    .S(_098_),
    .Y(_061_)
  );
  AND2_X1 _443_ (
    .A(_076_),
    .B(_094_),
    .Y(_109_)
  );
  NAND2 _444_ (
    .A(_076_),
    .B(_096_),
    .Y(_110_)
  );
  NOR2 _445_ (
    .A(_086_),
    .B(_097_),
    .Y(_062_)
  );
  NAND2 _446_ (
    .A(_082_),
    .B(_102_),
    .Y(_111_)
  );
  NOR2 _447_ (
    .A(_086_),
    .B(_094_),
    .Y(_112_)
  );
  NOR2 _448_ (
    .A(_097_),
    .B(_112_),
    .Y(_113_)
  );
  NAND2 _449_ (
    .A(_083_),
    .B(_113_),
    .Y(_114_)
  );
  NAND2 _450_ (
    .A(_111_),
    .B(_114_),
    .Y(_063_)
  );
  NAND2 _451_ (
    .A(_081_),
    .B(_102_),
    .Y(_115_)
  );
  NAND2 _452_ (
    .A(_082_),
    .B(_113_),
    .Y(_116_)
  );
  NAND2 _453_ (
    .A(_115_),
    .B(_116_),
    .Y(_064_)
  );
  NAND2 _454_ (
    .A(_080_),
    .B(_102_),
    .Y(_117_)
  );
  NAND2 _455_ (
    .A(_081_),
    .B(_113_),
    .Y(_118_)
  );
  NAND2 _456_ (
    .A(_117_),
    .B(_118_),
    .Y(_065_)
  );
  NAND2 _457_ (
    .A(_079_),
    .B(_102_),
    .Y(_119_)
  );
  NAND2 _458_ (
    .A(_080_),
    .B(_113_),
    .Y(_120_)
  );
  NAND2 _459_ (
    .A(_119_),
    .B(_120_),
    .Y(_066_)
  );
  NAND2 _460_ (
    .A(_078_),
    .B(_102_),
    .Y(_121_)
  );
  NAND2 _461_ (
    .A(_079_),
    .B(_113_),
    .Y(_122_)
  );
  NAND2 _462_ (
    .A(_121_),
    .B(_122_),
    .Y(_067_)
  );
  NAND2 _463_ (
    .A(_077_),
    .B(_102_),
    .Y(_123_)
  );
  NAND2 _464_ (
    .A(_078_),
    .B(_113_),
    .Y(_124_)
  );
  NAND2 _465_ (
    .A(_123_),
    .B(_124_),
    .Y(_068_)
  );
  NAND2 _466_ (
    .A(_076_),
    .B(_102_),
    .Y(_125_)
  );
  NAND2 _467_ (
    .A(_077_),
    .B(_113_),
    .Y(_126_)
  );
  NAND2 _468_ (
    .A(_125_),
    .B(_126_),
    .Y(_069_)
  );
  NAND2 _469_ (
    .A(_083_),
    .B(_097_),
    .Y(_127_)
  );
  NAND4 _470_ (
    .A(_093_),
    .B(_101_),
    .C(_110_),
    .D(_127_),
    .Y(_070_)
  );
  OR4 _471_ (
    .A(_006_),
    .B(_005_),
    .C(_173_),
    .D(_170_),
    .Y(_128_)
  );
  NOR4 _472_ (
    .A(_171_),
    .B(_168_),
    .C(_169_),
    .D(_128_),
    .Y(_129_)
  );
  MUX2 _473_ (
    .A(_129_),
    .B(_004_),
    .S(_110_),
    .Y(_071_)
  );
  NAND2 _474_ (
    .A(_004_),
    .B(_089_),
    .Y(_130_)
  );
  NAND2 _475_ (
    .A(_099_),
    .B(_130_),
    .Y(_131_)
  );
  NOR2 _476_ (
    .A(_100_),
    .B(_109_),
    .Y(_132_)
  );
  NAND3 _477_ (
    .A(_103_),
    .B(_131_),
    .C(_132_),
    .Y(_133_)
  );
  MUX2 _478_ (
    .A(_133_),
    .B(_151_),
    .S(_098_),
    .Y(_072_)
  );
  MUX2 _479_ (
    .A(_166_),
    .B(_154_),
    .S(_110_),
    .Y(_073_)
  );
  NOR2 _480_ (
    .A(_183_),
    .B(_095_),
    .Y(_134_)
  );
  MUX2 _481_ (
    .A(_183_),
    .B(_191_),
    .S(_095_),
    .Y(_074_)
  );
  MUX2 _482_ (
    .A(_174_),
    .B(_162_),
    .S(_093_),
    .Y(_075_)
  );
  NAND2 _483_ (
    .A(_079_),
    .B(_187_),
    .Y(_135_)
  );
  NAND2 _484_ (
    .A(_081_),
    .B(_189_),
    .Y(_136_)
  );
  NAND2 _485_ (
    .A(_082_),
    .B(_190_),
    .Y(_137_)
  );
  NAND2 _486_ (
    .A(_078_),
    .B(_186_),
    .Y(_138_)
  );
  AND2_X1 _487_ (
    .A(_076_),
    .B(_184_),
    .Y(_139_)
  );
  NAND2 _488_ (
    .A(_080_),
    .B(_188_),
    .Y(_140_)
  );
  NAND2 _489_ (
    .A(_077_),
    .B(_185_),
    .Y(_141_)
  );
  NAND4 _490_ (
    .A(_135_),
    .B(_137_),
    .C(_138_),
    .D(_140_),
    .Y(_142_)
  );
  NAND2 _491_ (
    .A(_136_),
    .B(_141_),
    .Y(_143_)
  );
  NOR4 _492_ (
    .A(_083_),
    .B(_139_),
    .C(_142_),
    .D(_143_),
    .Y(_144_)
  );
  NAND2 _493_ (
    .A(_094_),
    .B(_144_),
    .Y(_145_)
  );
  AND2_X1 _494_ (
    .A(_004_),
    .B(_099_),
    .Y(_146_)
  );
  NOR3 _495_ (
    .A(_163_),
    .B(_134_),
    .C(_146_),
    .Y(_147_)
  );
  NAND2 _496_ (
    .A(_145_),
    .B(_147_),
    .Y(_003_)
  );
  NAND3 _497_ (
    .A(_166_),
    .B(_164_),
    .C(_090_),
    .Y(_148_)
  );
  NAND2 _498_ (
    .A(_152_),
    .B(_148_),
    .Y(_085_)
  );
  AND2_X1 _499_ (
    .A(_152_),
    .B(_091_),
    .Y(_013_)
  );
  AND2_X1 _500_ (
    .A(_152_),
    .B(_091_),
    .Y(_014_)
  );
  AND2_X1 _501_ (
    .A(_152_),
    .B(_091_),
    .Y(_015_)
  );
  AND2_X1 _502_ (
    .A(_152_),
    .B(_091_),
    .Y(_016_)
  );
  AND2_X1 _503_ (
    .A(_152_),
    .B(_091_),
    .Y(_017_)
  );
  AND2_X1 _504_ (
    .A(_152_),
    .B(_091_),
    .Y(_018_)
  );
  AND2_X1 _505_ (
    .A(_152_),
    .B(_091_),
    .Y(_019_)
  );
  AND2_X1 _506_ (
    .A(_152_),
    .B(_091_),
    .Y(_020_)
  );
  AND2_X1 _507_ (
    .A(_152_),
    .B(_091_),
    .Y(_021_)
  );
  AND2_X1 _508_ (
    .A(_152_),
    .B(_091_),
    .Y(_022_)
  );
  AND2_X1 _509_ (
    .A(_152_),
    .B(_091_),
    .Y(_023_)
  );
  AND2_X1 _510_ (
    .A(_152_),
    .B(_091_),
    .Y(_024_)
  );
  AND2_X1 _511_ (
    .A(_084_),
    .B(_152_),
    .Y(_025_)
  );
  AND2_X1 _512_ (
    .A(_084_),
    .B(_152_),
    .Y(_026_)
  );
  AND2_X1 _513_ (
    .A(_084_),
    .B(_152_),
    .Y(_027_)
  );
  AND2_X1 _514_ (
    .A(_084_),
    .B(_152_),
    .Y(_028_)
  );
  AND2_X1 _515_ (
    .A(_084_),
    .B(_152_),
    .Y(_029_)
  );
  AND2_X1 _516_ (
    .A(_084_),
    .B(_152_),
    .Y(_030_)
  );
  AND2_X1 _517_ (
    .A(_084_),
    .B(_152_),
    .Y(_031_)
  );
  AND2_X1 _518_ (
    .A(_152_),
    .B(_091_),
    .Y(_032_)
  );
  AND2_X1 _519_ (
    .A(_152_),
    .B(_091_),
    .Y(_033_)
  );
  AND2_X1 _520_ (
    .A(_152_),
    .B(_091_),
    .Y(_034_)
  );
  AND2_X1 _521_ (
    .A(_152_),
    .B(_091_),
    .Y(_035_)
  );
  AND2_X1 _522_ (
    .A(_152_),
    .B(_091_),
    .Y(_036_)
  );
  AND2_X1 _523_ (
    .A(_152_),
    .B(_091_),
    .Y(_037_)
  );
  AND2_X1 _524_ (
    .A(_152_),
    .B(_091_),
    .Y(_038_)
  );
  AND2_X1 _525_ (
    .A(_152_),
    .B(_091_),
    .Y(_039_)
  );
  AND2_X1 _526_ (
    .A(_152_),
    .B(_091_),
    .Y(_040_)
  );
  AND2_X1 _527_ (
    .A(_152_),
    .B(_091_),
    .Y(_041_)
  );
  AND2_X1 _528_ (
    .A(_152_),
    .B(_091_),
    .Y(_042_)
  );
  AND2_X1 _529_ (
    .A(_152_),
    .B(_091_),
    .Y(_043_)
  );
  AND2_X1 _530_ (
    .A(_084_),
    .B(_152_),
    .Y(_044_)
  );
  AND2_X1 _531_ (
    .A(_152_),
    .B(_091_),
    .Y(_045_)
  );
  AND2_X1 _532_ (
    .A(_152_),
    .B(_091_),
    .Y(_046_)
  );
  (* src = "src/i2c_slave_async.v:147.5-192.8" *)
  DFFRB _533_ (
    .CK(scl),
    .D(_315_),
    .Q(bit_walk[0]),
    .QB(_225_),
    .RSTB(_262_)
  );
  (* src = "src/i2c_slave_async.v:147.5-192.8" *)
  DFFRB _534_ (
    .CK(scl),
    .D(_314_),
    .Q(bit_walk[1]),
    .QB(_224_),
    .RSTB(_263_)
  );
  (* src = "src/i2c_slave_async.v:147.5-192.8" *)
  DFFRB _535_ (
    .CK(scl),
    .D(_313_),
    .Q(bit_walk[2]),
    .QB(_223_),
    .RSTB(_264_)
  );
  (* src = "src/i2c_slave_async.v:147.5-192.8" *)
  DFFRB _536_ (
    .CK(scl),
    .D(_312_),
    .Q(bit_walk[3]),
    .QB(_222_),
    .RSTB(_265_)
  );
  (* src = "src/i2c_slave_async.v:147.5-192.8" *)
  DFFRB _537_ (
    .CK(scl),
    .D(_311_),
    .Q(bit_walk[4]),
    .QB(_221_),
    .RSTB(_266_)
  );
  (* src = "src/i2c_slave_async.v:147.5-192.8" *)
  DFFRB _538_ (
    .CK(scl),
    .D(_310_),
    .Q(bit_walk[5]),
    .QB(_220_),
    .RSTB(_267_)
  );
  (* src = "src/i2c_slave_async.v:147.5-192.8" *)
  DFFRB _539_ (
    .CK(scl),
    .D(_309_),
    .Q(bit_walk[6]),
    .QB(_219_),
    .RSTB(_268_)
  );
  (* src = "src/i2c_slave_async.v:147.5-192.8" *)
  DFFS _540_ (
    .CK(scl),
    .D(_316_),
    .Q(bit_walk[7]),
    .QB(_226_),
    .SET(rst_scl_domain)
  );
  (* src = "src/i2c_slave_async.v:147.5-192.8" *)
  DFFRB _541_ (
    .CK(scl),
    .D(_317_),
    .Q(addr_ok),
    .QB(_231_),
    .RSTB(_261_)
  );
  (* src = "src/i2c_slave_async.v:147.5-192.8" *)
  DFFRB _542_ (
    .CK(scl),
    .D(_308_),
    .Q(phase[0]),
    .QB(_218_),
    .RSTB(_269_)
  );
  (* src = "src/i2c_slave_async.v:147.5-192.8" *)
  DFFRB _543_ (
    .CK(scl),
    .D(_307_),
    .Q(phase[1]),
    .QB(_217_),
    .RSTB(_270_)
  );
  (* src = "src/i2c_slave_async.v:147.5-192.8" *)
  DFFRB _544_ (
    .CK(scl),
    .D(_318_),
    .Q(phase[2]),
    .QB(_227_),
    .RSTB(_260_)
  );
  (* src = "src/i2c_slave_async.v:147.5-192.8" *)
  DFFRB _545_ (
    .CK(scl),
    .D(_319_),
    .Q(rw_bit),
    .QB(_228_),
    .RSTB(_259_)
  );
  (* src = "src/i2c_slave_async.v:219.5-238.8" *)
  DFFRB _546_ (
    .CK(scl_n),
    .D(_306_),
    .Q(txreg[0]),
    .QB(_216_),
    .RSTB(_271_)
  );
  (* src = "src/i2c_slave_async.v:219.5-238.8" *)
  DFFRB _547_ (
    .CK(scl_n),
    .D(_305_),
    .Q(txreg[1]),
    .QB(_215_),
    .RSTB(_272_)
  );
  (* src = "src/i2c_slave_async.v:219.5-238.8" *)
  DFFRB _548_ (
    .CK(scl_n),
    .D(_304_),
    .Q(txreg[2]),
    .QB(_214_),
    .RSTB(_273_)
  );
  (* src = "src/i2c_slave_async.v:219.5-238.8" *)
  DFFRB _549_ (
    .CK(scl_n),
    .D(_303_),
    .Q(txreg[3]),
    .QB(_213_),
    .RSTB(_274_)
  );
  (* src = "src/i2c_slave_async.v:219.5-238.8" *)
  DFFRB _550_ (
    .CK(scl_n),
    .D(_302_),
    .Q(txreg[4]),
    .QB(_212_),
    .RSTB(_275_)
  );
  (* src = "src/i2c_slave_async.v:219.5-238.8" *)
  DFFRB _551_ (
    .CK(scl_n),
    .D(_301_),
    .Q(txreg[5]),
    .QB(_211_),
    .RSTB(_276_)
  );
  (* src = "src/i2c_slave_async.v:219.5-238.8" *)
  DFFRB _552_ (
    .CK(scl_n),
    .D(_300_),
    .Q(txreg[6]),
    .QB(_210_),
    .RSTB(_277_)
  );
  (* src = "src/i2c_slave_async.v:219.5-238.8" *)
  DFFRB _553_ (
    .CK(scl_n),
    .D(_320_),
    .Q(txreg[7]),
    .QB(_197_),
    .RSTB(_290_)
  );
  (* src = "src/i2c_slave_async.v:147.5-192.8" *)
  DFFRB _554_ (
    .CK(scl),
    .D(_299_),
    .Q(rx_data_r[0]),
    .QB(_209_),
    .RSTB(_278_)
  );
  (* src = "src/i2c_slave_async.v:147.5-192.8" *)
  DFFRB _555_ (
    .CK(scl),
    .D(_298_),
    .Q(rx_data_r[1]),
    .QB(_208_),
    .RSTB(_279_)
  );
  (* src = "src/i2c_slave_async.v:147.5-192.8" *)
  DFFRB _556_ (
    .CK(scl),
    .D(_297_),
    .Q(rx_data_r[2]),
    .QB(_207_),
    .RSTB(_280_)
  );
  (* src = "src/i2c_slave_async.v:147.5-192.8" *)
  DFFRB _557_ (
    .CK(scl),
    .D(_296_),
    .Q(rx_data_r[3]),
    .QB(_206_),
    .RSTB(_281_)
  );
  (* src = "src/i2c_slave_async.v:147.5-192.8" *)
  DFFRB _558_ (
    .CK(scl),
    .D(_295_),
    .Q(rx_data_r[4]),
    .QB(_205_),
    .RSTB(_282_)
  );
  (* src = "src/i2c_slave_async.v:147.5-192.8" *)
  DFFRB _559_ (
    .CK(scl),
    .D(_294_),
    .Q(rx_data_r[5]),
    .QB(_204_),
    .RSTB(_283_)
  );
  (* src = "src/i2c_slave_async.v:147.5-192.8" *)
  DFFRB _560_ (
    .CK(scl),
    .D(_293_),
    .Q(rx_data_r[6]),
    .QB(_203_),
    .RSTB(_284_)
  );
  (* src = "src/i2c_slave_async.v:147.5-192.8" *)
  DFFRB _561_ (
    .CK(scl),
    .D(_321_),
    .Q(rx_data_r[7]),
    .QB(_195_),
    .RSTB(_292_)
  );
  (* src = "src/i2c_slave_async.v:219.5-238.8" *)
  DFFRB _562_ (
    .CK(scl_n),
    .D(_002_),
    .Q(sda_oe_r),
    .QB(_229_),
    .RSTB(_258_)
  );
  (* src = "src/i2c_slave_async.v:147.5-192.8" *)
  DFFRB _563_ (
    .CK(scl),
    .D(sda_in),
    .Q(shreg[0]),
    .QB(_199_),
    .RSTB(_288_)
  );
  (* src = "src/i2c_slave_async.v:147.5-192.8" *)
  DFFRB _564_ (
    .CK(scl),
    .D(shreg[0]),
    .Q(shreg[1]),
    .QB(_198_),
    .RSTB(_289_)
  );
  (* src = "src/i2c_slave_async.v:147.5-192.8" *)
  DFFRB _565_ (
    .CK(scl),
    .D(shreg[1]),
    .Q(shreg[2]),
    .QB(_201_),
    .RSTB(_286_)
  );
  (* src = "src/i2c_slave_async.v:147.5-192.8" *)
  DFFRB _566_ (
    .CK(scl),
    .D(shreg[2]),
    .Q(shreg[3]),
    .QB(_202_),
    .RSTB(_285_)
  );
  (* src = "src/i2c_slave_async.v:147.5-192.8" *)
  DFFRB _567_ (
    .CK(scl),
    .D(shreg[3]),
    .Q(shreg[4]),
    .QB(_196_),
    .RSTB(_291_)
  );
  (* src = "src/i2c_slave_async.v:147.5-192.8" *)
  DFFRB _568_ (
    .CK(scl),
    .D(shreg[4]),
    .Q(shreg[5]),
    .QB(_230_),
    .RSTB(_257_)
  );
  (* src = "src/i2c_slave_async.v:147.5-192.8" *)
  DFFRB _569_ (
    .CK(scl),
    .D(shreg[5]),
    .Q(shreg[6]),
    .QB(_200_),
    .RSTB(_287_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/i2c_slave_async.v:115.10-115.65" *)
  DEL1 u_del_sda (
    .A(sda_in),
    .GND(GND),
    .VDD(VDD),
    .Y(sda_d)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/i2c_slave_async.v:201.12-201.64" *)
  INV_X1 u_inv_scl (
    .A(scl),
    .GND(GND),
    .VDD(VDD),
    .Y(scl_n)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/i2c_slave_async.v:123.10-123.78" *)
  NOR2 u_lat_q (
    .A(busy_clr),
    .B(qn),
    .GND(GND),
    .VDD(VDD),
    .Y(busy)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "src/i2c_slave_async.v:124.10-124.78" *)
  NOR2 u_lat_qn (
    .A(start_pulse),
    .B(busy),
    .GND(GND),
    .VDD(VDD),
    .Y(qn)
  );
  assign _322_[1] = _248_;
  assign _395_[7] = bit_walk[0];
  assign _396_[2] = _396_[0];
  assign _399_[0] = 1'h0;
  assign { _398_[2], _398_[0] } = { rw_bit, 1'h0 };
  assign is_last_bit = bit_walk[0];
  assign shreg_next = { shreg[6:0], sda_in };
  assign rw = rw_bit;
  assign addr_match = addr_ok;
  assign rx_data = rx_data_r;
  assign _252_ = _196_;
  assign _253_ = _200_;
  assign _250_ = _217_;
  assign _249_ = _218_;
  assign _251_ = _227_;
  assign _398_[1] = _228_;
  assign sda_oe = _229_;
  assign rst_scl_domain = _153_;
  assign _257_ = _011_;
  assign _258_ = _012_;
  assign _259_ = _013_;
  assign _260_ = _014_;
  assign _261_ = _015_;
  assign _262_ = _016_;
  assign _263_ = _017_;
  assign _264_ = _018_;
  assign _265_ = _019_;
  assign _266_ = _020_;
  assign _267_ = _021_;
  assign _268_ = _022_;
  assign _269_ = _023_;
  assign _270_ = _024_;
  assign _271_ = _025_;
  assign _272_ = _026_;
  assign _273_ = _027_;
  assign _274_ = _028_;
  assign _275_ = _029_;
  assign _276_ = _030_;
  assign _277_ = _031_;
  assign _278_ = _032_;
  assign _279_ = _033_;
  assign _280_ = _034_;
  assign _281_ = _035_;
  assign _282_ = _036_;
  assign _283_ = _037_;
  assign _284_ = _038_;
  assign _285_ = _039_;
  assign _009_ = _227_;
  assign _076_ = bit_walk[0];
  assign _149_ = phase[0];
  assign _151_ = phase[2];
  assign _083_ = bit_walk[7];
  assign _082_ = bit_walk[6];
  assign _081_ = bit_walk[5];
  assign _080_ = bit_walk[4];
  assign _079_ = bit_walk[3];
  assign _078_ = bit_walk[2];
  assign _077_ = bit_walk[1];
  assign _008_ = _218_;
  assign _150_ = phase[1];
  assign _286_ = _040_;
  assign _287_ = _041_;
  assign _288_ = _042_;
  assign _166_ = sda_in;
  assign rx_valid = _163_;
  assign _004_ = addr_ok;
  assign _190_ = txreg[6];
  assign _189_ = txreg[5];
  assign _188_ = txreg[4];
  assign _187_ = txreg[3];
  assign _186_ = txreg[2];
  assign _185_ = txreg[1];
  assign _184_ = txreg[0];
  assign _010_ = _228_;
  assign _007_ = _217_;
  assign _154_ = rw_bit;
  assign _289_ = _043_;
  assign _006_ = _200_;
  assign _005_ = _196_;
  assign _173_ = shreg[5];
  assign _170_ = shreg[2];
  assign _171_ = shreg[3];
  assign _168_ = shreg[0];
  assign _169_ = shreg[1];
  assign _172_ = shreg[4];
  assign _174_ = shreg[6];
  assign _161_ = rx_data_r[6];
  assign _293_ = _047_;
  assign _160_ = rx_data_r[5];
  assign _294_ = _048_;
  assign _159_ = rx_data_r[4];
  assign _295_ = _049_;
  assign _158_ = rx_data_r[3];
  assign _296_ = _050_;
  assign _157_ = rx_data_r[2];
  assign _297_ = _051_;
  assign _156_ = rx_data_r[1];
  assign _298_ = _052_;
  assign _155_ = rx_data_r[0];
  assign _299_ = _053_;
  assign _182_ = tx_data[6];
  assign _300_ = _054_;
  assign _181_ = tx_data[5];
  assign _301_ = _055_;
  assign _180_ = tx_data[4];
  assign _302_ = _056_;
  assign _179_ = tx_data[3];
  assign _303_ = _057_;
  assign _178_ = tx_data[2];
  assign _304_ = _058_;
  assign _177_ = tx_data[1];
  assign _305_ = _059_;
  assign _176_ = tx_data[0];
  assign _306_ = _060_;
  assign _307_ = _061_;
  assign _308_ = _062_;
  assign _309_ = _063_;
  assign _310_ = _064_;
  assign _311_ = _065_;
  assign _312_ = _066_;
  assign _313_ = _067_;
  assign _314_ = _068_;
  assign _315_ = _069_;
  assign _316_ = _070_;
  assign _317_ = _071_;
  assign _318_ = _072_;
  assign _319_ = _073_;
  assign _191_ = txreg[7];
  assign _183_ = tx_data[7];
  assign _320_ = _074_;
  assign _290_ = _044_;
  assign _291_ = _045_;
  assign _162_ = rx_data_r[7];
  assign _321_ = _075_;
  assign _002_ = _003_;
  assign _167_ = sda_oe_r;
  assign _084_ = busy;
  assign _152_ = rst_n;
  assign _292_ = _046_;
  assign start_pulse = _175_;
  assign busy_clr = _085_;
  assign _164_ = scl;
  assign _165_ = sda_d;
endmodule
