/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, Clang /workspace/YoWASP/yosys/wasi-sdk-33.0-x86_64-linux/share/cmake/../..//bin/clang++ 22.1.0) */

(* top =  1  *)
(* src = "i2c_slave_async.v:63.1-196.10" *)
module i2c_slave_async(VDD, GND, rst_n, scl, sda_in, sda_oe, tx_data, rx_data, rx_valid, addr_match, rw, busy);
  (* src = "i2c_slave_async.v:66.23-66.26" *)
  input VDD;
  wire VDD;
  (* src = "i2c_slave_async.v:66.28-66.31" *)
  input GND;
  wire GND;
  (* src = "i2c_slave_async.v:67.23-67.28" *)
  input rst_n;
  wire rst_n;
  (* src = "i2c_slave_async.v:68.23-68.26" *)
  input scl;
  wire scl;
  (* src = "i2c_slave_async.v:69.23-69.29" *)
  input sda_in;
  wire sda_in;
  (* src = "i2c_slave_async.v:70.23-70.29" *)
  output sda_oe;
  wire sda_oe;
  (* src = "i2c_slave_async.v:72.23-72.30" *)
  input [7:0] tx_data;
  wire [7:0] tx_data;
  (* src = "i2c_slave_async.v:73.23-73.30" *)
  output [7:0] rx_data;
  wire [7:0] rx_data;
  (* src = "i2c_slave_async.v:74.23-74.31" *)
  output rx_valid;
  wire rx_valid;
  (* src = "i2c_slave_async.v:75.23-75.33" *)
  output addr_match;
  wire addr_match;
  (* src = "i2c_slave_async.v:76.23-76.25" *)
  output rw;
  wire rw;
  (* src = "i2c_slave_async.v:77.23-77.27" *)
  output busy;
  wire busy;
  (* src = "i2c_slave_async.v:174.5-193.8" *)
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire RSTB1;
  wire RSTB2;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  (* unused_bits = "0" *)
  wire _110_;
  (* unused_bits = "0" *)
  wire _111_;
  (* unused_bits = "0" *)
  wire _112_;
  (* unused_bits = "0" *)
  wire _113_;
  (* unused_bits = "0" *)
  wire _114_;
  (* unused_bits = "0" *)
  wire _115_;
  (* unused_bits = "0" *)
  wire _116_;
  (* unused_bits = "0" *)
  wire _117_;
  (* unused_bits = "0" *)
  wire _118_;
  (* unused_bits = "0" *)
  wire _119_;
  (* unused_bits = "0" *)
  wire _120_;
  (* unused_bits = "0" *)
  wire _121_;
  (* unused_bits = "0" *)
  wire _122_;
  (* unused_bits = "0" *)
  wire _123_;
  (* unused_bits = "0" *)
  wire _124_;
  (* unused_bits = "0" *)
  wire _125_;
  (* unused_bits = "0" *)
  wire _126_;
  (* unused_bits = "0" *)
  wire _127_;
  (* unused_bits = "0" *)
  wire _128_;
  (* unused_bits = "0" *)
  wire _129_;
  (* unused_bits = "0" *)
  wire _130_;
  (* unused_bits = "0" *)
  wire _131_;
  (* unused_bits = "0" *)
  wire _132_;
  (* force_downto = 32'd1 *)
  (* src = "i2c_slave_async.v:187.43-187.56|/share/techmap.v:135.22-135.23" *)
  (* unused_bits = "4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _133_;
  (* force_downto = 32'd1 *)
  (* src = "i2c_slave_async.v:187.44-187.55|/share/techmap.v:279.21-279.23" *)
  wire [31:0] _134_;
  (* src = "i2c_slave_async.v:108.15-108.22" *)
  wire addr_ok;
  (* src = "i2c_slave_async.v:106.15-106.22" *)
  wire [3:0] bit_cnt;
  (* src = "i2c_slave_async.v:97.10-97.18" *)
  wire busy_clr;
  (* src = "i2c_slave_async.v:105.15-105.20" *)
  wire [2:0] phase;
  (* src = "i2c_slave_async.v:98.10-98.12" *)
  wire qn;
  (* src = "i2c_slave_async.v:108.24-108.30" *)
  wire rw_bit;
  (* src = "i2c_slave_async.v:109.15-109.24" *)
  wire [7:0] rx_data_r;
  (* src = "i2c_slave_async.v:166.10-166.15" *)
  wire scl_n;
  (* src = "i2c_slave_async.v:90.10-90.15" *)
  wire sda_d;
  (* src = "i2c_slave_async.v:171.9-171.17" *)
  wire sda_oe_r;
  (* src = "i2c_slave_async.v:107.15-107.20" *)
  (* unused_bits = "7" *)
  wire [7:0] shreg;
  (* src = "i2c_slave_async.v:111.16-111.26" *)
  wire [7:0] shreg_next;
  (* src = "i2c_slave_async.v:93.10-93.21" *)
  wire start_pulse;
  (* src = "i2c_slave_async.v:172.15-172.20" *)
  wire [7:0] txreg;
  wire scl_row0;
  wire scl_row1;
  wire scl_row2;
  wire scl_row3;
  wire scl_n_row1;
  wire scl_n_row2;
  INV_X1 _135_ (
    .A(bit_cnt[0]),
    .Y(_034_)
  );
  INV_X1 _136_ (
    .A(bit_cnt[1]),
    .Y(_035_)
  );
  INV_X1 _137_ (
    .A(bit_cnt[2]),
    .Y(_036_)
  );
  INV_X1 _138_ (
    .A(_134_[3]),
    .Y(_037_)
  );
  INV_X1 _139_ (
    .A(_006_),
    .Y(_038_)
  );
  INV_X1 _140_ (
    .A(rw_bit),
    .Y(_039_)
  );
  INV_X1 _141_ (
    .A(rst_n),
    .Y(_040_)
  );
  INV_X1 _142_ (
    .A(sda_d),
    .Y(_041_)
  );
  NAND2 _143_ (
    .A(scl_row2),
    .B(sda_d),
    .Y(_042_)
  );
  NOR2 _144_ (
    .A(sda_in),
    .B(_042_),
    .Y(start_pulse)
  );
  NOR2 _145_ (
    .A(_040_),
    .B(start_pulse),
    .Y(RSTB1)
  );
  AND2_X1 _146_ (
    .A(busy),
    .B(rst_n),
    .Y(RSTB2)
  );
  OR2 _147_ (
    .A(phase[2]),
    .B(_004_),
    .Y(_043_)
  );
  NOR2 _148_ (
    .A(_001_),
    .B(_043_),
    .Y(rx_valid)
  );
  AND2_X1 _149_ (
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .Y(_044_)
  );
  NAND2 _150_ (
    .A(bit_cnt[2]),
    .B(_044_),
    .Y(_045_)
  );
  OR2 _151_ (
    .A(phase[1]),
    .B(phase[0]),
    .Y(_046_)
  );
  NOR2 _152_ (
    .A(_005_),
    .B(_046_),
    .Y(_047_)
  );
  INV_X1 _153_ (
    .A(_047_),
    .Y(_048_)
  );
  NOR2 _154_ (
    .A(phase[2]),
    .B(_046_),
    .Y(_049_)
  );
  NOR2 _155_ (
    .A(phase[0]),
    .B(_043_),
    .Y(_050_)
  );
  NOR3 _156_ (
    .A(_047_),
    .B(_049_),
    .C(_050_),
    .Y(_051_)
  );
  OR3 _157_ (
    .A(_047_),
    .B(_049_),
    .C(_050_),
    .Y(_052_)
  );
  NOR4 _158_ (
    .A(bit_cnt[3]),
    .B(_133_[0]),
    .C(_133_[2]),
    .D(_133_[1]),
    .Y(_053_)
  );
  OR2 _159_ (
    .A(_051_),
    .B(_053_),
    .Y(_054_)
  );
  AND2_X1 _160_ (
    .A(_048_),
    .B(_054_),
    .Y(_055_)
  );
  NAND2 _161_ (
    .A(_048_),
    .B(_054_),
    .Y(_056_)
  );
  NAND2 _162_ (
    .A(_045_),
    .B(_056_),
    .Y(_057_)
  );
  OR2 _163_ (
    .A(_001_),
    .B(phase[1]),
    .Y(_058_)
  );
  NOR2 _164_ (
    .A(_005_),
    .B(_058_),
    .Y(_059_)
  );
  NOR2 _165_ (
    .A(phase[2]),
    .B(_058_),
    .Y(_060_)
  );
  NOR4 _166_ (
    .A(rx_valid),
    .B(_052_),
    .C(_059_),
    .D(_060_),
    .Y(_061_)
  );
  INV_X1 _167_ (
    .A(_061_),
    .Y(_062_)
  );
  NAND2 _168_ (
    .A(_057_),
    .B(_062_),
    .Y(_063_)
  );
  NAND2 _169_ (
    .A(_044_),
    .B(_056_),
    .Y(_064_)
  );
  NAND2 _170_ (
    .A(_036_),
    .B(_064_),
    .Y(_065_)
  );
  AND2_X1 _171_ (
    .A(_063_),
    .B(_065_),
    .Y(_009_)
  );
  NAND2 _172_ (
    .A(bit_cnt[1]),
    .B(_061_),
    .Y(_066_)
  );
  NOR2 _173_ (
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .Y(_067_)
  );
  OR3 _174_ (
    .A(_044_),
    .B(_055_),
    .C(_067_),
    .Y(_068_)
  );
  NAND2 _175_ (
    .A(_066_),
    .B(_068_),
    .Y(_010_)
  );
  NAND2 _176_ (
    .A(bit_cnt[0]),
    .B(_061_),
    .Y(_069_)
  );
  NAND2 _177_ (
    .A(_133_[0]),
    .B(_052_),
    .Y(_070_)
  );
  NAND2 _178_ (
    .A(_069_),
    .B(_070_),
    .Y(_011_)
  );
  NAND2 _179_ (
    .A(_050_),
    .B(_053_),
    .Y(_071_)
  );
  MUX2 _180_ (
    .A(shreg[5]),
    .B(rx_data_r[6]),
    .S(_071_),
    .Y(_012_)
  );
  MUX2 _181_ (
    .A(shreg[4]),
    .B(rx_data_r[5]),
    .S(_071_),
    .Y(_013_)
  );
  MUX2 _182_ (
    .A(shreg[3]),
    .B(rx_data_r[4]),
    .S(_071_),
    .Y(_014_)
  );
  MUX2 _183_ (
    .A(shreg[2]),
    .B(rx_data_r[3]),
    .S(_071_),
    .Y(_015_)
  );
  MUX2 _184_ (
    .A(shreg[1]),
    .B(rx_data_r[2]),
    .S(_071_),
    .Y(_016_)
  );
  MUX2 _185_ (
    .A(shreg[0]),
    .B(rx_data_r[1]),
    .S(_071_),
    .Y(_017_)
  );
  MUX2 _186_ (
    .A(sda_in),
    .B(rx_data_r[0]),
    .S(_071_),
    .Y(_018_)
  );
  NOR2 _187_ (
    .A(bit_cnt[3]),
    .B(bit_cnt[2]),
    .Y(_072_)
  );
  NAND2 _188_ (
    .A(_067_),
    .B(_072_),
    .Y(_073_)
  );
  OR2 _189_ (
    .A(_048_),
    .B(_073_),
    .Y(_074_)
  );
  MUX2 _190_ (
    .A(tx_data[6]),
    .B(txreg[6]),
    .S(_074_),
    .Y(_019_)
  );
  MUX2 _191_ (
    .A(tx_data[5]),
    .B(txreg[5]),
    .S(_074_),
    .Y(_020_)
  );
  MUX2 _192_ (
    .A(tx_data[4]),
    .B(txreg[4]),
    .S(_074_),
    .Y(_021_)
  );
  MUX2 _193_ (
    .A(tx_data[3]),
    .B(txreg[3]),
    .S(_074_),
    .Y(_022_)
  );
  MUX2 _194_ (
    .A(tx_data[2]),
    .B(txreg[2]),
    .S(_074_),
    .Y(_023_)
  );
  MUX2 _195_ (
    .A(tx_data[1]),
    .B(txreg[1]),
    .S(_074_),
    .Y(_024_)
  );
  MUX2 _196_ (
    .A(tx_data[0]),
    .B(txreg[0]),
    .S(_074_),
    .Y(_025_)
  );
  NAND2 _197_ (
    .A(addr_ok),
    .B(_038_),
    .Y(_075_)
  );
  AND2_X1 _198_ (
    .A(_060_),
    .B(_075_),
    .Y(_076_)
  );
  NAND2 _199_ (
    .A(sda_in),
    .B(_059_),
    .Y(_077_)
  );
  NAND2 _200_ (
    .A(_071_),
    .B(_077_),
    .Y(_078_)
  );
  NAND2 _201_ (
    .A(_054_),
    .B(_062_),
    .Y(_079_)
  );
  NOR4 _202_ (
    .A(rx_valid),
    .B(_076_),
    .C(_078_),
    .D(_079_),
    .Y(_080_)
  );
  NOR2 _203_ (
    .A(phase[1]),
    .B(_054_),
    .Y(_081_)
  );
  NOR2 _204_ (
    .A(_080_),
    .B(_081_),
    .Y(_026_)
  );
  AND2_X1 _205_ (
    .A(_052_),
    .B(_053_),
    .Y(_027_)
  );
  NOR2 _206_ (
    .A(phase[2]),
    .B(_054_),
    .Y(_082_)
  );
  NAND2 _207_ (
    .A(addr_ok),
    .B(_039_),
    .Y(_083_)
  );
  AND2_X1 _208_ (
    .A(_060_),
    .B(_083_),
    .Y(_084_)
  );
  NOR4 _209_ (
    .A(_047_),
    .B(_059_),
    .C(_079_),
    .D(_084_),
    .Y(_085_)
  );
  NOR2 _210_ (
    .A(_082_),
    .B(_085_),
    .Y(_028_)
  );
  NAND2 _211_ (
    .A(_049_),
    .B(_053_),
    .Y(_086_)
  );
  MUX2 _212_ (
    .A(sda_in),
    .B(rw_bit),
    .S(_086_),
    .Y(_029_)
  );
  NOR2 _213_ (
    .A(tx_data[7]),
    .B(_074_),
    .Y(_087_)
  );
  MUX2 _214_ (
    .A(tx_data[7]),
    .B(txreg[7]),
    .S(_074_),
    .Y(_030_)
  );
  MUX2 _215_ (
    .A(shreg[6]),
    .B(rx_data_r[7]),
    .S(_071_),
    .Y(_031_)
  );
  NAND3 _216_ (
    .A(bit_cnt[0]),
    .B(_035_),
    .C(txreg[6]),
    .Y(_088_)
  );
  NAND2 _217_ (
    .A(txreg[7]),
    .B(_067_),
    .Y(_089_)
  );
  NAND2 _218_ (
    .A(txreg[4]),
    .B(_044_),
    .Y(_090_)
  );
  NAND3 _219_ (
    .A(_034_),
    .B(bit_cnt[1]),
    .C(txreg[5]),
    .Y(_091_)
  );
  NAND4 _220_ (
    .A(_088_),
    .B(_089_),
    .C(_090_),
    .D(_091_),
    .Y(_092_)
  );
  NAND2 _221_ (
    .A(_133_[2]),
    .B(_092_),
    .Y(_093_)
  );
  NAND2 _222_ (
    .A(_036_),
    .B(_093_),
    .Y(_094_)
  );
  NAND2 _223_ (
    .A(txreg[3]),
    .B(_067_),
    .Y(_095_)
  );
  NAND3 _224_ (
    .A(bit_cnt[0]),
    .B(_035_),
    .C(txreg[2]),
    .Y(_096_)
  );
  NAND3 _225_ (
    .A(_034_),
    .B(bit_cnt[1]),
    .C(txreg[1]),
    .Y(_097_)
  );
  NAND2 _226_ (
    .A(txreg[0]),
    .B(_044_),
    .Y(_098_)
  );
  NAND4 _227_ (
    .A(_095_),
    .B(_096_),
    .C(_097_),
    .D(_098_),
    .Y(_099_)
  );
  NOR2 _228_ (
    .A(_036_),
    .B(_099_),
    .Y(_100_)
  );
  NOR3 _229_ (
    .A(bit_cnt[3]),
    .B(_037_),
    .C(_100_),
    .Y(_101_)
  );
  NAND2 _230_ (
    .A(_094_),
    .B(_101_),
    .Y(_102_)
  );
  NAND3 _231_ (
    .A(_047_),
    .B(_073_),
    .C(_102_),
    .Y(_103_)
  );
  AND2_X1 _232_ (
    .A(addr_ok),
    .B(_060_),
    .Y(_104_)
  );
  NOR3 _233_ (
    .A(rx_valid),
    .B(_087_),
    .C(_104_),
    .Y(_105_)
  );
  NAND2 _234_ (
    .A(_103_),
    .B(_105_),
    .Y(_000_)
  );
  NOR2 _235_ (
    .A(_045_),
    .B(_055_),
    .Y(_106_)
  );
  MUX2 _236_ (
    .A(_106_),
    .B(_063_),
    .S(bit_cnt[3]),
    .Y(_032_)
  );
  NAND3 _237_ (
    .A(sda_in),
    .B(scl_row2),
    .C(_041_),
    .Y(_107_)
  );
  NAND2 _238_ (
    .A(rst_n),
    .B(_107_),
    .Y(busy_clr)
  );
  OR4 _239_ (
    .A(_002_),
    .B(_003_),
    .C(shreg[5]),
    .D(shreg[2]),
    .Y(_108_)
  );
  NOR4 _240_ (
    .A(shreg[3]),
    .B(shreg[0]),
    .C(shreg[1]),
    .D(_108_),
    .Y(_109_)
  );
  MUX2 _241_ (
    .A(_109_),
    .B(addr_ok),
    .S(_086_),
    .Y(_033_)
  );
  (* src = "i2c_slave_async.v:113.5-158.8" *)
  DFFR _242_ (
    .CK(scl_row0),
    .D(_027_),
    .Q(phase[0]),
    .QB(_001_),
    .RSTB(RSTB1)
  );
  (* src = "i2c_slave_async.v:113.5-158.8" *)
  DFFR _243_ (
    .CK(scl_row0),
    .D(_026_),
    .Q(phase[1]),
    .QB(_004_),
    .RSTB(RSTB1)
  );
  (* src = "i2c_slave_async.v:113.5-158.8" *)
  DFFR _244_ (
    .CK(scl_row0),
    .D(_028_),
    .Q(phase[2]),
    .QB(_005_),
    .RSTB(RSTB1)
  );
  (* src = "i2c_slave_async.v:113.5-158.8" *)
  DFFR _245_ (
    .CK(scl_row0),
    .D(_029_),
    .Q(rw_bit),
    .QB(_006_),
    .RSTB(RSTB1)
  );
  (* src = "i2c_slave_async.v:174.5-193.8" *)
  DFFR _246_ (
    .CK(scl_n_row2),
    .D(_025_),
    .Q(txreg[0]),
    .QB(_128_),
    .RSTB(RSTB2)
  );
  (* src = "i2c_slave_async.v:174.5-193.8" *)
  DFFR _247_ (
    .CK(scl_n_row2),
    .D(_024_),
    .Q(txreg[1]),
    .QB(_127_),
    .RSTB(RSTB2)
  );
  (* src = "i2c_slave_async.v:174.5-193.8" *)
  DFFR _248_ (
    .CK(scl_n_row2),
    .D(_023_),
    .Q(txreg[2]),
    .QB(_126_),
    .RSTB(RSTB2)
  );
  (* src = "i2c_slave_async.v:174.5-193.8" *)
  DFFR _249_ (
    .CK(scl_n_row2),
    .D(_022_),
    .Q(txreg[3]),
    .QB(_125_),
    .RSTB(RSTB2)
  );
  (* src = "i2c_slave_async.v:174.5-193.8" *)
  DFFR _250_ (
    .CK(scl_n_row2),
    .D(_021_),
    .Q(txreg[4]),
    .QB(_124_),
    .RSTB(RSTB2)
  );
  (* src = "i2c_slave_async.v:174.5-193.8" *)
  DFFR _251_ (
    .CK(scl_n_row2),
    .D(_020_),
    .Q(txreg[5]),
    .QB(_123_),
    .RSTB(RSTB2)
  );
  (* src = "i2c_slave_async.v:174.5-193.8" *)
  DFFR _252_ (
    .CK(scl_n_row1),
    .D(_019_),
    .Q(txreg[6]),
    .QB(_122_),
    .RSTB(RSTB2)
  );
  (* src = "i2c_slave_async.v:174.5-193.8" *)
  DFFR _253_ (
    .CK(scl_n_row1),
    .D(_030_),
    .Q(txreg[7]),
    .QB(_112_),
    .RSTB(RSTB2)
  );
  (* src = "i2c_slave_async.v:113.5-158.8" *)
  DFFR _254_ (
    .CK(scl_row3),
    .D(_018_),
    .Q(rx_data_r[0]),
    .QB(_121_),
    .RSTB(RSTB1)
  );
  (* src = "i2c_slave_async.v:113.5-158.8" *)
  DFFR _255_ (
    .CK(scl_row3),
    .D(_017_),
    .Q(rx_data_r[1]),
    .QB(_120_),
    .RSTB(RSTB1)
  );
  (* src = "i2c_slave_async.v:113.5-158.8" *)
  DFFR _256_ (
    .CK(scl_row3),
    .D(_016_),
    .Q(rx_data_r[2]),
    .QB(_119_),
    .RSTB(RSTB1)
  );
  (* src = "i2c_slave_async.v:113.5-158.8" *)
  DFFR _257_ (
    .CK(scl_row3),
    .D(_015_),
    .Q(rx_data_r[3]),
    .QB(_118_),
    .RSTB(RSTB1)
  );
  (* src = "i2c_slave_async.v:113.5-158.8" *)
  DFFR _258_ (
    .CK(scl_row3),
    .D(_014_),
    .Q(rx_data_r[4]),
    .QB(_117_),
    .RSTB(RSTB1)
  );
  (* src = "i2c_slave_async.v:113.5-158.8" *)
  DFFR _259_ (
    .CK(scl_row3),
    .D(_013_),
    .Q(rx_data_r[5]),
    .QB(_116_),
    .RSTB(RSTB1)
  );
  (* src = "i2c_slave_async.v:113.5-158.8" *)
  DFFR _260_ (
    .CK(scl_row3),
    .D(_012_),
    .Q(rx_data_r[6]),
    .QB(_115_),
    .RSTB(RSTB1)
  );
  (* src = "i2c_slave_async.v:113.5-158.8" *)
  DFFR _261_ (
    .CK(scl_row3),
    .D(_031_),
    .Q(rx_data_r[7]),
    .QB(_111_),
    .RSTB(RSTB1)
  );
  (* src = "i2c_slave_async.v:113.5-158.8" *)
  DFFR _262_ (
    .CK(scl_row0),
    .D(_011_),
    .Q(bit_cnt[0]),
    .QB(_133_[0]),
    .RSTB(RSTB1)
  );
  (* src = "i2c_slave_async.v:113.5-158.8" *)
  DFFR _263_ (
    .CK(scl_row1),
    .D(_010_),
    .Q(bit_cnt[1]),
    .QB(_133_[1]),
    .RSTB(RSTB1)
  );
  (* src = "i2c_slave_async.v:113.5-158.8" *)
  DFFR _264_ (
    .CK(scl_row1),
    .D(_009_),
    .Q(bit_cnt[2]),
    .QB(_133_[2]),
    .RSTB(RSTB1)
  );
  (* src = "i2c_slave_async.v:113.5-158.8" *)
  DFFR _265_ (
    .CK(scl_row1),
    .D(_032_),
    .Q(bit_cnt[3]),
    .QB(_134_[3]),
    .RSTB(RSTB1)
  );
  (* src = "i2c_slave_async.v:113.5-158.8" *)
  DFFR _266_ (
    .CK(scl_row3),
    .D(_033_),
    .Q(addr_ok),
    .QB(_132_),
    .RSTB(RSTB1)
  );
  (* src = "i2c_slave_async.v:174.5-193.8" *)
  DFFR _267_ (
    .CK(scl_n_row1),
    .D(_000_),
    .Q(sda_oe_r),
    .QB(_130_),
    .RSTB(RSTB2)
  );
  (* src = "i2c_slave_async.v:113.5-158.8" *)
  DFFR _268_ (
    .CK(scl_row2),
    .D(sda_in),
    .Q(shreg[0]),
    .QB(_131_),
    .RSTB(RSTB1)
  );
  (* src = "i2c_slave_async.v:113.5-158.8" *)
  DFFR _269_ (
    .CK(scl_row2),
    .D(shreg[0]),
    .Q(shreg[1]),
    .QB(_110_),
    .RSTB(RSTB1)
  );
  (* src = "i2c_slave_async.v:113.5-158.8" *)
  DFFR _270_ (
    .CK(scl_row2),
    .D(shreg[1]),
    .Q(shreg[2]),
    .QB(_129_),
    .RSTB(RSTB1)
  );
  (* src = "i2c_slave_async.v:113.5-158.8" *)
  DFFR _271_ (
    .CK(scl_row2),
    .D(shreg[2]),
    .Q(shreg[3]),
    .QB(_113_),
    .RSTB(RSTB1)
  );
  (* src = "i2c_slave_async.v:113.5-158.8" *)
  DFFR _272_ (
    .CK(scl_row3),
    .D(shreg[3]),
    .Q(shreg[4]),
    .QB(_003_),
    .RSTB(RSTB1)
  );
  (* src = "i2c_slave_async.v:113.5-158.8" *)
  DFFR _273_ (
    .CK(scl_row3),
    .D(shreg[4]),
    .Q(shreg[5]),
    .QB(_114_),
    .RSTB(RSTB1)
  );
  (* src = "i2c_slave_async.v:113.5-158.8" *)
  DFFR _274_ (
    .CK(scl_row3),
    .D(shreg[5]),
    .Q(shreg[6]),
    .QB(_002_),
    .RSTB(RSTB1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "i2c_slave_async.v:91.10-91.65" *)
  DEL1 u_del_sda (
    .A(sda_in),
    .GND(GND),
    .VDD(VDD),
    .Y(sda_d)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "i2c_slave_async.v:167.12-167.64" *)
  INV_X1 u_inv_scl (
    .A(scl_row2),
    .GND(GND),
    .VDD(VDD),
    .Y(scl_n)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "i2c_slave_async.v:99.10-99.78" *)
  NOR2 u_lat_q (
    .A(busy_clr),
    .B(qn),
    .GND(GND),
    .VDD(VDD),
    .Y(busy)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "i2c_slave_async.v:100.10-100.78" *)
  NOR2 u_lat_qn (
    .A(start_pulse),
    .B(busy),
    .GND(GND),
    .VDD(VDD),
    .Y(qn)
  );
  assign { _133_[31:5], _133_[3] } = { _133_[4], _133_[4], _133_[4], _133_[4], _133_[4], _133_[4], _133_[4], _133_[4], _133_[4], _133_[4], _133_[4], _133_[4], _133_[4], _133_[4], _133_[4], _133_[4], _133_[4], _133_[4], _133_[4], _133_[4], _133_[4], _133_[4], _133_[4], _133_[4], _133_[4], _133_[4], _133_[4], bit_cnt[3] };
  assign { _134_[31:4], _134_[2:0] } = { 28'hfffffff, _133_[2:0] };
  assign shreg_next = { shreg[6:0], sda_in };
  assign rw = rw_bit;
  assign addr_match = addr_ok;
  assign rx_data = rx_data_r;
  assign sda_oe = sda_oe_r;

  BUF_X1 u_buf_scl_row0 (
    .A(scl),
    .Y(scl_row0),
    .VDD(VDD),
    .GND(GND)
  );

  BUF_X1 u_buf_scl_row1 (
    .A(scl),
    .Y(scl_row1),
    .VDD(VDD),
    .GND(GND)
  );

  BUF_X1 u_buf_scl_row2 (
    .A(scl),
    .Y(scl_row2),
    .VDD(VDD),
    .GND(GND)
  );

  BUF_X1 u_buf_scl_row3 (
    .A(scl),
    .Y(scl_row3),
    .VDD(VDD),
    .GND(GND)
  );

  BUF_X1 u_buf_scl_n_row1 (
    .A(scl_n),
    .Y(scl_n_row1),
    .VDD(VDD),
    .GND(GND)
  );

  BUF_X1 u_buf_scl_n_row2 (
    .A(scl_n),
    .Y(scl_n_row2),
    .VDD(VDD),
    .GND(GND)
  );

endmodule
