/* Generated by Yosys 0.67 (git sha1 2d1509d1b, Release, Clang /workspace/YoWASP/yosys/wasi-sdk-33.0-x86_64-linux/share/cmake/../..//bin/clang++ 22.1.0) */

module i2c_slave_async(VDD, GND, rst_n, scl, sda_in, sda_oe, tx_data, rx_data, rx_valid, addr_match, rw, busy);
  input VDD;
  wire VDD;
  input GND;
  wire GND;
  input rst_n;
  wire rst_n;
  input scl;
  wire scl;
  input sda_in;
  wire sda_in;
  output sda_oe;
  wire sda_oe;
  input [7:0] tx_data;
  wire [7:0] tx_data;
  output [7:0] rx_data;
  wire [7:0] rx_data;
  output rx_valid;
  wire rx_valid;
  output addr_match;
  wire addr_match;
  output rw;
  wire rw;
  output busy;
  wire busy;
  wire [3:0] _000_;
  wire [2:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire [1:0] _254_;
  wire _255_;
  wire [2:0] _256_;
  wire [1:0] _257_;
  wire [1:0] _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire [1:0] _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire [2:0] _277_;
  wire _278_;
  wire _279_;
  wire [2:0] _280_;
  wire _281_;
  wire _282_;
  wire [2:0] _283_;
  wire _284_;
  wire _285_;
  wire [2:0] _286_;
  wire _287_;
  wire _288_;
  wire [1:0] _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire [2:0] _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire [3:0] _321_;
  wire [31:0] _322_;
  wire [0:0] _323_;
  wire [3:0] _324_;
  wire [3:0] _325_;
  wire [23:0] _326_;
  wire [23:0] _327_;
  wire [23:0] _328_;
  wire [23:0] _329_;
  wire [31:0] _330_;
  wire [31:0] _331_;
  wire _332_;
  wire _333_;
  wire [2:0] _334_;
  wire [2:0] _335_;
  wire addr_ok;
  wire [3:0] bit_cnt;
  wire busy_clr;
  wire [2:0] phase;
  wire qn;
  wire rst_scl_domain;
  wire rst_sdaoe_domain;
  wire rw_bit;
  wire [7:0] rx_data_r;
  wire scl_n;
  wire sda_d;
  wire sda_oe_r;
  wire [7:0] shreg;
  wire [7:0] shreg_next;
  wire start_pulse;
  wire stop_pulse;
  wire [7:0] txreg;
  INV_X1 _336_ (
    .A(_040_),
    .Y(_110_),
    .VDD(VDD),
    .GND(GND)
  );
  INV_X1 _337_ (
    .A(_041_),
    .Y(_111_),
    .VDD(VDD),
    .GND(GND)
  );
  INV_X1 _338_ (
    .A(_042_),
    .Y(_112_),
    .VDD(VDD),
    .GND(GND)
  );
  INV_X1 _339_ (
    .A(_005_),
    .Y(_113_),
    .VDD(VDD),
    .GND(GND)
  );
  INV_X1 _340_ (
    .A(_006_),
    .Y(_114_),
    .VDD(VDD),
    .GND(GND)
  );
  INV_X1 _341_ (
    .A(_128_),
    .Y(_115_),
    .VDD(VDD),
    .GND(GND)
  );
  INV_X1 _342_ (
    .A(_125_),
    .Y(_116_),
    .VDD(VDD),
    .GND(GND)
  );
  INV_X1 _343_ (
    .A(_139_),
    .Y(_117_),
    .VDD(VDD),
    .GND(GND)
  );
  OR2 _344_ (
    .A(_124_),
    .B(_008_),
    .Y(_118_),
    .VDD(VDD),
    .GND(GND)
  );
  NOR2 _345_ (
    .A(_014_),
    .B(_118_),
    .Y(_137_),
    .VDD(VDD),
    .GND(GND)
  );
  NOR2 _346_ (
    .A(_122_),
    .B(_118_),
    .Y(_119_),
    .VDD(VDD),
    .GND(GND)
  );
  OR2 _347_ (
    .A(_123_),
    .B(_122_),
    .Y(_120_),
    .VDD(VDD),
    .GND(GND)
  );
  NOR2 _348_ (
    .A(_124_),
    .B(_120_),
    .Y(_121_),
    .VDD(VDD),
    .GND(GND)
  );
  NOR2 _349_ (
    .A(_007_),
    .B(_120_),
    .Y(_046_),
    .VDD(VDD),
    .GND(GND)
  );
  INV_X1 _350_ (
    .A(_046_),
    .Y(_047_),
    .VDD(VDD),
    .GND(GND)
  );
  NOR3 _351_ (
    .A(_119_),
    .B(_121_),
    .C(_046_),
    .Y(_048_),
    .VDD(VDD),
    .GND(GND)
  );
  OR3 _352_ (
    .A(_119_),
    .B(_121_),
    .C(_046_),
    .Y(_049_),
    .VDD(VDD),
    .GND(GND)
  );
  OR2 _353_ (
    .A(_014_),
    .B(_123_),
    .Y(_050_),
    .VDD(VDD),
    .GND(GND)
  );
  NOR2 _354_ (
    .A(_007_),
    .B(_050_),
    .Y(_051_),
    .VDD(VDD),
    .GND(GND)
  );
  NOR2 _355_ (
    .A(_124_),
    .B(_050_),
    .Y(_052_),
    .VDD(VDD),
    .GND(GND)
  );
  NOR4 _356_ (
    .A(_137_),
    .B(_049_),
    .C(_051_),
    .D(_052_),
    .Y(_053_),
    .VDD(VDD),
    .GND(GND)
  );
  INV_X1 _357_ (
    .A(_053_),
    .Y(_054_),
    .VDD(VDD),
    .GND(GND)
  );
  AND2_X1 _358_ (
    .A(_040_),
    .B(_041_),
    .Y(_055_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND2 _359_ (
    .A(_042_),
    .B(_055_),
    .Y(_056_),
    .VDD(VDD),
    .GND(GND)
  );
  NOR4 _360_ (
    .A(_043_),
    .B(_009_),
    .C(_011_),
    .D(_010_),
    .Y(_057_),
    .VDD(VDD),
    .GND(GND)
  );
  OR2 _361_ (
    .A(_048_),
    .B(_057_),
    .Y(_058_),
    .VDD(VDD),
    .GND(GND)
  );
  AND2_X1 _362_ (
    .A(_047_),
    .B(_058_),
    .Y(_059_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND2 _363_ (
    .A(_047_),
    .B(_058_),
    .Y(_060_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND2 _364_ (
    .A(_056_),
    .B(_060_),
    .Y(_061_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND2 _365_ (
    .A(_054_),
    .B(_061_),
    .Y(_062_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND2 _366_ (
    .A(_055_),
    .B(_060_),
    .Y(_063_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND2 _367_ (
    .A(_112_),
    .B(_063_),
    .Y(_064_),
    .VDD(VDD),
    .GND(GND)
  );
  AND2_X1 _368_ (
    .A(_062_),
    .B(_064_),
    .Y(_015_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND2 _369_ (
    .A(_041_),
    .B(_053_),
    .Y(_065_),
    .VDD(VDD),
    .GND(GND)
  );
  NOR2 _370_ (
    .A(_040_),
    .B(_041_),
    .Y(_066_),
    .VDD(VDD),
    .GND(GND)
  );
  OR3 _371_ (
    .A(_055_),
    .B(_059_),
    .C(_066_),
    .Y(_067_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND2 _372_ (
    .A(_065_),
    .B(_067_),
    .Y(_016_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND2 _373_ (
    .A(_040_),
    .B(_053_),
    .Y(_068_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND2 _374_ (
    .A(_009_),
    .B(_049_),
    .Y(_069_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND2 _375_ (
    .A(_068_),
    .B(_069_),
    .Y(_017_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND2 _376_ (
    .A(_119_),
    .B(_057_),
    .Y(_070_),
    .VDD(VDD),
    .GND(GND)
  );
  MUX2 _377_ (
    .A(_146_),
    .B(_135_),
    .S(_070_),
    .Y(_018_),
    .VDD(VDD),
    .GND(GND)
  );
  MUX2 _378_ (
    .A(_145_),
    .B(_134_),
    .S(_070_),
    .Y(_019_),
    .VDD(VDD),
    .GND(GND)
  );
  MUX2 _379_ (
    .A(_144_),
    .B(_133_),
    .S(_070_),
    .Y(_020_),
    .VDD(VDD),
    .GND(GND)
  );
  MUX2 _380_ (
    .A(_143_),
    .B(_132_),
    .S(_070_),
    .Y(_021_),
    .VDD(VDD),
    .GND(GND)
  );
  MUX2 _381_ (
    .A(_142_),
    .B(_131_),
    .S(_070_),
    .Y(_022_),
    .VDD(VDD),
    .GND(GND)
  );
  MUX2 _382_ (
    .A(_141_),
    .B(_130_),
    .S(_070_),
    .Y(_023_),
    .VDD(VDD),
    .GND(GND)
  );
  MUX2 _383_ (
    .A(_140_),
    .B(_129_),
    .S(_070_),
    .Y(_024_),
    .VDD(VDD),
    .GND(GND)
  );
  NOR2 _384_ (
    .A(_043_),
    .B(_042_),
    .Y(_071_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND2 _385_ (
    .A(_066_),
    .B(_071_),
    .Y(_072_),
    .VDD(VDD),
    .GND(GND)
  );
  OR2 _386_ (
    .A(_047_),
    .B(_072_),
    .Y(_073_),
    .VDD(VDD),
    .GND(GND)
  );
  MUX2 _387_ (
    .A(_155_),
    .B(_163_),
    .S(_073_),
    .Y(_025_),
    .VDD(VDD),
    .GND(GND)
  );
  MUX2 _388_ (
    .A(_154_),
    .B(_162_),
    .S(_073_),
    .Y(_026_),
    .VDD(VDD),
    .GND(GND)
  );
  MUX2 _389_ (
    .A(_153_),
    .B(_161_),
    .S(_073_),
    .Y(_027_),
    .VDD(VDD),
    .GND(GND)
  );
  MUX2 _390_ (
    .A(_152_),
    .B(_160_),
    .S(_073_),
    .Y(_028_),
    .VDD(VDD),
    .GND(GND)
  );
  MUX2 _391_ (
    .A(_151_),
    .B(_159_),
    .S(_073_),
    .Y(_029_),
    .VDD(VDD),
    .GND(GND)
  );
  MUX2 _392_ (
    .A(_150_),
    .B(_158_),
    .S(_073_),
    .Y(_030_),
    .VDD(VDD),
    .GND(GND)
  );
  MUX2 _393_ (
    .A(_149_),
    .B(_157_),
    .S(_073_),
    .Y(_031_),
    .VDD(VDD),
    .GND(GND)
  );
  NOR2 _394_ (
    .A(_123_),
    .B(_058_),
    .Y(_074_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND2 _395_ (
    .A(_004_),
    .B(_114_),
    .Y(_075_),
    .VDD(VDD),
    .GND(GND)
  );
  AND2_X1 _396_ (
    .A(_052_),
    .B(_075_),
    .Y(_076_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND2 _397_ (
    .A(_140_),
    .B(_051_),
    .Y(_077_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND2 _398_ (
    .A(_070_),
    .B(_077_),
    .Y(_078_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND2 _399_ (
    .A(_054_),
    .B(_058_),
    .Y(_079_),
    .VDD(VDD),
    .GND(GND)
  );
  NOR4 _400_ (
    .A(_137_),
    .B(_076_),
    .C(_078_),
    .D(_079_),
    .Y(_080_),
    .VDD(VDD),
    .GND(GND)
  );
  NOR2 _401_ (
    .A(_074_),
    .B(_080_),
    .Y(_032_),
    .VDD(VDD),
    .GND(GND)
  );
  AND2_X1 _402_ (
    .A(_049_),
    .B(_057_),
    .Y(_033_),
    .VDD(VDD),
    .GND(GND)
  );
  NOR2 _403_ (
    .A(_124_),
    .B(_058_),
    .Y(_081_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND2 _404_ (
    .A(_004_),
    .B(_115_),
    .Y(_082_),
    .VDD(VDD),
    .GND(GND)
  );
  AND2_X1 _405_ (
    .A(_052_),
    .B(_082_),
    .Y(_083_),
    .VDD(VDD),
    .GND(GND)
  );
  NOR4 _406_ (
    .A(_046_),
    .B(_051_),
    .C(_079_),
    .D(_083_),
    .Y(_084_),
    .VDD(VDD),
    .GND(GND)
  );
  NOR2 _407_ (
    .A(_081_),
    .B(_084_),
    .Y(_034_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND2 _408_ (
    .A(_121_),
    .B(_057_),
    .Y(_085_),
    .VDD(VDD),
    .GND(GND)
  );
  MUX2 _409_ (
    .A(_140_),
    .B(_128_),
    .S(_085_),
    .Y(_035_),
    .VDD(VDD),
    .GND(GND)
  );
  NOR2 _410_ (
    .A(_156_),
    .B(_073_),
    .Y(_086_),
    .VDD(VDD),
    .GND(GND)
  );
  MUX2 _411_ (
    .A(_156_),
    .B(_164_),
    .S(_073_),
    .Y(_036_),
    .VDD(VDD),
    .GND(GND)
  );
  MUX2 _412_ (
    .A(_147_),
    .B(_136_),
    .S(_070_),
    .Y(_037_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND3 _413_ (
    .A(_040_),
    .B(_111_),
    .C(_163_),
    .Y(_087_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND2 _414_ (
    .A(_164_),
    .B(_066_),
    .Y(_088_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND2 _415_ (
    .A(_161_),
    .B(_055_),
    .Y(_089_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND3 _416_ (
    .A(_110_),
    .B(_041_),
    .C(_162_),
    .Y(_090_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND4 _417_ (
    .A(_087_),
    .B(_088_),
    .C(_089_),
    .D(_090_),
    .Y(_091_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND2 _418_ (
    .A(_011_),
    .B(_091_),
    .Y(_092_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND2 _419_ (
    .A(_112_),
    .B(_092_),
    .Y(_093_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND2 _420_ (
    .A(_160_),
    .B(_066_),
    .Y(_094_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND3 _421_ (
    .A(_040_),
    .B(_111_),
    .C(_159_),
    .Y(_095_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND3 _422_ (
    .A(_110_),
    .B(_041_),
    .C(_158_),
    .Y(_096_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND2 _423_ (
    .A(_157_),
    .B(_055_),
    .Y(_097_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND4 _424_ (
    .A(_094_),
    .B(_095_),
    .C(_096_),
    .D(_097_),
    .Y(_098_),
    .VDD(VDD),
    .GND(GND)
  );
  NOR2 _425_ (
    .A(_112_),
    .B(_098_),
    .Y(_099_),
    .VDD(VDD),
    .GND(GND)
  );
  NOR3 _426_ (
    .A(_043_),
    .B(_113_),
    .C(_099_),
    .Y(_100_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND2 _427_ (
    .A(_093_),
    .B(_100_),
    .Y(_101_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND3 _428_ (
    .A(_046_),
    .B(_072_),
    .C(_101_),
    .Y(_102_),
    .VDD(VDD),
    .GND(GND)
  );
  AND2_X1 _429_ (
    .A(_004_),
    .B(_052_),
    .Y(_103_),
    .VDD(VDD),
    .GND(GND)
  );
  NOR3 _430_ (
    .A(_137_),
    .B(_086_),
    .C(_103_),
    .Y(_104_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND2 _431_ (
    .A(_102_),
    .B(_104_),
    .Y(_003_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND2 _432_ (
    .A(_044_),
    .B(_125_),
    .Y(_127_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND2 _433_ (
    .A(_138_),
    .B(_139_),
    .Y(_105_),
    .VDD(VDD),
    .GND(GND)
  );
  NOR2 _434_ (
    .A(_140_),
    .B(_105_),
    .Y(_148_),
    .VDD(VDD),
    .GND(GND)
  );
  OR2 _435_ (
    .A(_116_),
    .B(_148_),
    .Y(_126_),
    .VDD(VDD),
    .GND(GND)
  );
  NOR2 _436_ (
    .A(_056_),
    .B(_059_),
    .Y(_106_),
    .VDD(VDD),
    .GND(GND)
  );
  MUX2 _437_ (
    .A(_106_),
    .B(_062_),
    .S(_043_),
    .Y(_038_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND3 _438_ (
    .A(_140_),
    .B(_138_),
    .C(_117_),
    .Y(_107_),
    .VDD(VDD),
    .GND(GND)
  );
  NAND2 _439_ (
    .A(_125_),
    .B(_107_),
    .Y(_045_),
    .VDD(VDD),
    .GND(GND)
  );
  OR4 _440_ (
    .A(_013_),
    .B(_012_),
    .C(_146_),
    .D(_143_),
    .Y(_108_),
    .VDD(VDD),
    .GND(GND)
  );
  NOR4 _441_ (
    .A(_144_),
    .B(_141_),
    .C(_142_),
    .D(_108_),
    .Y(_109_),
    .VDD(VDD),
    .GND(GND)
  );
  MUX2 _442_ (
    .A(_109_),
    .B(_004_),
    .S(_085_),
    .Y(_039_),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _443_ (
    .CK(scl),
    .D(_246_),
    .Q(phase[0]),
    .QB(_196_),
    .RST(rst_scl_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _444_ (
    .CK(scl),
    .D(_245_),
    .Q(phase[1]),
    .QB(_175_),
    .RST(rst_scl_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _445_ (
    .CK(scl),
    .D(_247_),
    .Q(phase[2]),
    .QB(_173_),
    .RST(rst_scl_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _446_ (
    .CK(scl),
    .D(_248_),
    .Q(rw_bit),
    .QB(_172_),
    .RST(rst_scl_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _447_ (
    .CK(scl_n),
    .D(_244_),
    .Q(txreg[0]),
    .QB(_176_),
    .RST(rst_sdaoe_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _448_ (
    .CK(scl_n),
    .D(_243_),
    .Q(txreg[1]),
    .QB(_177_),
    .RST(rst_sdaoe_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _449_ (
    .CK(scl_n),
    .D(_242_),
    .Q(txreg[2]),
    .QB(_178_),
    .RST(rst_sdaoe_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _450_ (
    .CK(scl_n),
    .D(_241_),
    .Q(txreg[3]),
    .QB(_179_),
    .RST(rst_sdaoe_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _451_ (
    .CK(scl_n),
    .D(_240_),
    .Q(txreg[4]),
    .QB(_180_),
    .RST(rst_sdaoe_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _452_ (
    .CK(scl_n),
    .D(_239_),
    .Q(txreg[5]),
    .QB(_181_),
    .RST(rst_sdaoe_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _453_ (
    .CK(scl_n),
    .D(_238_),
    .Q(txreg[6]),
    .QB(_182_),
    .RST(rst_sdaoe_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _454_ (
    .CK(scl_n),
    .D(_249_),
    .Q(txreg[7]),
    .QB(_198_),
    .RST(rst_sdaoe_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _455_ (
    .CK(scl),
    .D(_237_),
    .Q(rx_data_r[0]),
    .QB(_183_),
    .RST(rst_scl_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _456_ (
    .CK(scl),
    .D(_236_),
    .Q(rx_data_r[1]),
    .QB(_184_),
    .RST(rst_scl_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _457_ (
    .CK(scl),
    .D(_235_),
    .Q(rx_data_r[2]),
    .QB(_185_),
    .RST(rst_scl_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _458_ (
    .CK(scl),
    .D(_234_),
    .Q(rx_data_r[3]),
    .QB(_186_),
    .RST(rst_scl_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _459_ (
    .CK(scl),
    .D(_233_),
    .Q(rx_data_r[4]),
    .QB(_187_),
    .RST(rst_scl_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _460_ (
    .CK(scl),
    .D(_232_),
    .Q(rx_data_r[5]),
    .QB(_188_),
    .RST(rst_scl_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _461_ (
    .CK(scl),
    .D(_231_),
    .Q(rx_data_r[6]),
    .QB(_189_),
    .RST(rst_scl_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _462_ (
    .CK(scl),
    .D(_250_),
    .Q(rx_data_r[7]),
    .QB(_199_),
    .RST(rst_scl_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _463_ (
    .CK(scl),
    .D(_230_),
    .Q(bit_cnt[0]),
    .QB(_190_),
    .RST(rst_scl_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _464_ (
    .CK(scl),
    .D(_229_),
    .Q(bit_cnt[1]),
    .QB(_191_),
    .RST(rst_scl_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _465_ (
    .CK(scl),
    .D(_228_),
    .Q(bit_cnt[2]),
    .QB(_192_),
    .RST(rst_scl_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _466_ (
    .CK(scl),
    .D(_251_),
    .Q(bit_cnt[3]),
    .QB(_169_),
    .RST(rst_scl_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _467_ (
    .CK(scl),
    .D(_252_),
    .Q(addr_ok),
    .QB(_168_),
    .RST(rst_scl_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _468_ (
    .CK(scl_n),
    .D(_002_),
    .Q(sda_oe_r),
    .QB(_171_),
    .RST(rst_sdaoe_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _469_ (
    .CK(scl),
    .D(sda_in),
    .Q(shreg[0]),
    .QB(_170_),
    .RST(rst_scl_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _470_ (
    .CK(scl),
    .D(shreg[0]),
    .Q(shreg[1]),
    .QB(_167_),
    .RST(rst_scl_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _471_ (
    .CK(scl),
    .D(shreg[1]),
    .Q(shreg[2]),
    .QB(_174_),
    .RST(rst_scl_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _472_ (
    .CK(scl),
    .D(shreg[2]),
    .Q(shreg[3]),
    .QB(_197_),
    .RST(rst_scl_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _473_ (
    .CK(scl),
    .D(shreg[3]),
    .Q(shreg[4]),
    .QB(_193_),
    .RST(rst_scl_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _474_ (
    .CK(scl),
    .D(shreg[4]),
    .Q(shreg[5]),
    .QB(_194_),
    .RST(rst_scl_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DFFR _475_ (
    .CK(scl),
    .D(shreg[5]),
    .Q(shreg[6]),
    .QB(_195_),
    .RST(rst_scl_domain),
    .VDD(VDD),
    .GND(GND)
  );
  DEL1 u_del_sda (
    .A(sda_in),
    .GND(GND),
    .VDD(VDD),
    .Y(sda_d)
  );
  INV_X1 u_inv_scl (
    .A(scl),
    .GND(GND),
    .VDD(VDD),
    .Y(scl_n)
  );
  NOR2 u_lat_q (
    .A(busy_clr),
    .B(qn),
    .GND(GND),
    .VDD(VDD),
    .Y(busy)
  );
  NOR2 u_lat_qn (
    .A(start_pulse),
    .B(busy),
    .GND(GND),
    .VDD(VDD),
    .Y(qn)
  );
  assign { _322_[31:5], _322_[3] } = { _322_[4], _322_[4], _322_[4], _322_[4], _322_[4], _322_[4], _322_[4], _322_[4], _322_[4], _322_[4], _322_[4], _322_[4], _322_[4], _322_[4], _322_[4], _322_[4], _322_[4], _322_[4], _322_[4], _322_[4], _322_[4], _322_[4], _322_[4], _322_[4], _322_[4], _322_[4], _322_[4], bit_cnt[3] };
  assign _329_[8] = 1'hx;
  assign _328_[12:8] = 5'hxx;
  assign _326_[15:8] = 8'hxx;
  assign _327_[14:8] = 7'hxx;
  assign _325_[0] = _322_[0];
  assign { _330_[31:4], _330_[2:0] } = { 28'hfffffff, _322_[2:0] };
  assign _254_[1] = _219_;
  assign _289_[1] = _227_;
  assign _315_[1] = _315_[0];
  assign { _331_[31:4], _331_[2:0] } = { _331_[3], _331_[3], _331_[3], _331_[3], _331_[3], _331_[3], _331_[3], _331_[3], _331_[3], _331_[3], _331_[3], _331_[3], _331_[3], _331_[3], _331_[3], _331_[3], _331_[3], _331_[3], _331_[3], _331_[3], _331_[3], _331_[3], _331_[3], _331_[3], _331_[3], _331_[3], _331_[3], _331_[3], 3'h7 };
  assign _335_[0] = 1'h0;
  assign { _334_[2], _334_[0] } = { rw_bit, 1'h0 };
  assign _324_[0] = bit_cnt[0];
  assign shreg_next = { shreg[6:0], sda_in };
  assign rw = rw_bit;
  assign addr_match = addr_ok;
  assign rx_data = rx_data_r;
  assign sda_oe = sda_oe_r;
  assign _330_[3] = _169_;
  assign _334_[1] = _172_;
  assign _222_ = _173_;
  assign _221_ = _175_;
  assign _322_[0] = _190_;
  assign _322_[1] = _191_;
  assign _322_[2] = _192_;
  assign _223_ = _193_;
  assign _224_ = _195_;
  assign _220_ = _196_;
  assign rx_valid = _137_;
  assign _040_ = bit_cnt[0];
  assign _140_ = sda_in;
  assign _164_ = txreg[7];
  assign _043_ = bit_cnt[3];
  assign _157_ = txreg[0];
  assign _014_ = _196_;
  assign _123_ = phase[1];
  assign _124_ = phase[2];
  assign _007_ = _173_;
  assign _041_ = bit_cnt[1];
  assign _122_ = phase[0];
  assign _009_ = _190_;
  assign _042_ = bit_cnt[2];
  assign _008_ = _175_;
  assign _160_ = txreg[3];
  assign _004_ = addr_ok;
  assign _005_ = _169_;
  assign _011_ = _192_;
  assign _158_ = txreg[1];
  assign _162_ = txreg[5];
  assign _159_ = txreg[2];
  assign _010_ = _191_;
  assign _006_ = _172_;
  assign _128_ = rw_bit;
  assign _013_ = _195_;
  assign _012_ = _193_;
  assign _146_ = shreg[5];
  assign _143_ = shreg[2];
  assign _144_ = shreg[3];
  assign _141_ = shreg[0];
  assign _142_ = shreg[1];
  assign _145_ = shreg[4];
  assign _163_ = txreg[6];
  assign _147_ = shreg[6];
  assign _228_ = _015_;
  assign _229_ = _016_;
  assign _230_ = _017_;
  assign _135_ = rx_data_r[6];
  assign _231_ = _018_;
  assign _134_ = rx_data_r[5];
  assign _232_ = _019_;
  assign _133_ = rx_data_r[4];
  assign _233_ = _020_;
  assign _132_ = rx_data_r[3];
  assign _234_ = _021_;
  assign _131_ = rx_data_r[2];
  assign _235_ = _022_;
  assign _130_ = rx_data_r[1];
  assign _236_ = _023_;
  assign _129_ = rx_data_r[0];
  assign _237_ = _024_;
  assign _155_ = tx_data[6];
  assign _238_ = _025_;
  assign _154_ = tx_data[5];
  assign _239_ = _026_;
  assign _161_ = txreg[4];
  assign _153_ = tx_data[4];
  assign _240_ = _027_;
  assign _152_ = tx_data[3];
  assign _241_ = _028_;
  assign _151_ = tx_data[2];
  assign _242_ = _029_;
  assign _150_ = tx_data[1];
  assign _243_ = _030_;
  assign _149_ = tx_data[0];
  assign _244_ = _031_;
  assign _245_ = _032_;
  assign _246_ = _033_;
  assign _247_ = _034_;
  assign _248_ = _035_;
  assign _156_ = tx_data[7];
  assign _249_ = _036_;
  assign _136_ = rx_data_r[7];
  assign _250_ = _037_;
  assign _002_ = _003_;
  assign rst_sdaoe_domain = _127_;
  assign _044_ = busy;
  assign _125_ = rst_n;
  assign start_pulse = _148_;
  assign rst_scl_domain = _126_;
  assign _251_ = _038_;
  assign busy_clr = _045_;
  assign _138_ = scl;
  assign _139_ = sda_d;
  assign _252_ = _039_;
endmodule
